### ISSUE TITLE
No authToken when refresh

### ISSUE THREAD

**Issue by KCypher13** [SocketCluster/socketcluster#104]
Hi,

I have a middleware subscribe who check if you've got the right to subscribe in function of your authToken.

In localhost there is no problem, it's working.
But when I go to pre-prod, I doesn't have any authToken when I do a getAuthToken() when i'm refreshing the page.
So I can connect without problem, but when I'm refreshing the page, I don't have the AuthToken on the worker

My client application is hosted on a CDN, and my SocketCluster run on an other server. (they don't have the same DNS)
It looks like socketcluster doesn't send the authToken cookie when reconnecting : 

Localhost request cookie : 
Cookie:n/app/io=w0_5JT1-W0CYeuFPxWkAAAI; n/app/auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjU1Yzg4NzFlMzBkOTNjNWMyNjZmMDljOCIsImFjY2Vzc1Rva2VuIjoidEdBV3NSMVQ0WUo5NFhUeEFZM24ybE5BUWE4OVlaaWwyQmVQa0hSSGFZeGNkZmx5bWVXUHVIejkyeHZMRmg5diIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTQ0MDY3MDU4NSwiZXhwIjoxNDQwNzU2OTg1fQ.kfx_a6RP6m84zeu12ikB04UHqwTypJLAZO-7BMZFk0Y

Pre prod request cookie :
Cookie:n/app/io=w1_TAqybUFFJbyprj_2AAAD

I don't know if it's an error in my code, or in my server configuration...
Any idea ?

PS : I'm on SC1

**Comment by jondubois** [comment]
@KCypher13 Ah yes, that looks like an issue specific to SC1 which uses cookies to store and transmit the JWT token. I guess that's an issue if the script is loaded from a different host from origin?

This is one of the few areas where SC1 diverges from SC2 - This is low priority though, I have a lot do do. Feel free to submit a pull request if you can fix the issue.

**Comment by KCypher13** [comment]
Yeah I load the script from a different host.

I'm on it, I try to add the socket domain to the cookie generated with SCSocket.prototype._setCookie.

**Comment by KCypher13** [comment]
I've create a PR on socketCluster Client for this issues :
https://github.com/SocketCluster/socketcluster-client/pull/18
