### ISSUE TITLE
Messages not arriving

### ISSUE THREAD

**Issue by waltergms** [SocketCluster/socketcluster#113]
Good morning Jonathan, 
Before anything i would like to thank you about the support that you give, the application is running more stable now!
The only problem that still needs to be fixed and to be honest I don't know if it's a socketcluster problem is...
We built a client side control that run on receive message event (socket.emit) and trigger a event on server that set the "read" status of the message to 1... We are getting a 40% messages not read and we cant figure out why this is happening, because we don't show offline users, so every message should be delivered and read... We suspecting about 2 things...

1º - The users are getting offline and the server dont get it right...
2º - The users are online and the message are not delivered... 

Im guessing if have some way to check before emit the message through the global.publish if the channel have someone online OR some channel control to run time by time to check their users status...

**Comment by jondubois** [comment]
If a user navigates away from the page before their client responds to an event, then you could miss some acknowledgements but 40% sounds extremely high.

Another possible scenario:

- An error is being thrown on the client-side (not necessarily related to SC) which is preventing the SC client from sending the acknowledgement to the server (even though they did receive the message).

It's also possible (if your site/app has lots of mobile users), that if their mobile device goes to sleep while they are looking at your website/app, that SC may not realize that they are offline until the ping timeout happens and they could miss some messages from the server.

The SC client will automatically disconnect if the user navigates away from the current page but sleeps are a bit trickier to detect but the connections should 'ping timeout' and disconnect on their own in this case - The ping timeout could take a few seconds to kick in though.

**Comment by waltergms** [comment]
We have a meeting with the infrastructure team and we have decided to move to a mini-farm of 2 computers running linux... So, lets forget about it for now.

**Comment by jondubois** [comment]
Closing this... Feel free to open a new issue if something else comes up.
