### ISSUE TITLE
Changes to adapt for horizontal scale...

### ISSUE THREAD

**Issue by waltergms** [SocketCluster/socketcluster#114]
Hi Jonathan, 
Im doing some modifications in the code and in the servers to put loadbalancer, redis and sc-redis to make the sharing between the servers... Do you have some example ready? Im lost about what to do first and how do all... 
in my readings I arrived at the conclusion that :
1 - Adapt the broker.js and server.js on my socketcluster chat to connect the brokers on the Redis server...
2 - When the client create a channel the Redis is able to send publish to that channels, ok!

So, Redis have all the channels and i need to send a message from a client on server1 to a client on server2, so i have to change the socket.global.publish to broker.publish?

**Comment by jondubois** [comment]
@waltergms No you shouldn't have to change any of your code.
You can fork/copy the code from this repo: https://github.com/SocketCluster/sc-redis and then modify it to suit your specific needs (if necessary). You can modify it to relay subscriptions/messages to any pub/sub or distributed message queue you like without having to chnge any of your code in SC.

Some people used sc-redis as-is, others used NSQ and ioredis with a Redis cluster.

**Comment by waltergms** [comment]
Really? WOW!
So the only ajusts that i have to do is change the broker.js to attach sc-redis to broker and in server.js specify in the broker options the host and port for the redis?

**Comment by waltergms** [comment]
Another thing i was forgetting...
Should i use more than 1 broker on each socketcluster instance? Today im using 4 workers and 3 brokers on 1 socketcluster instance with no horizontal scale.

**Comment by jondubois** [comment]
@waltergms You can have as many brokers as you like and you shouldn't have to change any code.

SC shards channels evenly between your brokers so it should just work.

**Comment by waltergms** [comment]
Good mornin Jonathan my good friend!
Great news, everything is working almost perfect... Now we have 2 servers running linux and a farm server making the balance between them.. The only issue that are preventing we reach perfectness is a latency on client connection... its getting around 1 minute after load all stuff and connect socket to receive data back from server... Do you have some clue what could be slowing things down?

**Comment by waltergms** [comment]
Man you are the "MAN"
I change the load balance from the company that hold our servers and im using yours LoadBalancer now... the latency has gone, everything is fine now!

**Comment by jondubois** [comment]
@waltergms Nice!! It sounds like there were some issues with your previous loadbalancing solution. 

LoadBalancer,js is pretty lightweight (and easy to use), if you ever need something more advanced in the future, feel free to use nginx or HAProxy (just make sure you use a new version which supports WebSockets)... They should work as well.

Or feel free to contribute to LoadBalancer.js too if you want to add more features. That's good too :p

**Comment by jondubois** [comment]
Sounds like this has been resolved.
