### ISSUE TITLE
Socket Error: Socket hung up

### ISSUE THREAD

**Issue by bamoo456** [SocketCluster/socketcluster#115]
Hi, SocketCluster team,

Currently, I got some error logs reported from `socketCluster` module:
```
[Notice] Error: Socket Error: Socket hung up
```

When this log is shown, the related clients will get offline. 
Just curious that what kind of situations will cause this error ?  Does the connected client has a poor network environment ?

**Comment by tilleps** [comment]
Here is one situation that can result in "Socket hung up":

```javascript
scServer.addMiddleware(scServer.MIDDLEWARE_HANDSHAKE,
  function (req, next) {
  
    next();
    
    // Calling next() again can cause "Socket hung up"
    next();
  }
);
```

**Comment by jondubois** [comment]
I'll have to look into the calling ```next()``` twice issue - That's a separate thing.

Socket hung up errors/notices can happen often for a lot of different reasons (usually not a big deal).
It just means that the socket closed without first sending a close control frame.

Maybe the user is on a mobile device and it just went to sleep. Maybe the user's machine just crashed/froze abruptly for an unrelated reason. Basically it just means that the socket was closed abruptly.

**Comment by jondubois** [comment]
As of v2.3.25, if you call ```next()``` twice, it will emit a notice but will ignore the second call.
