### ISSUE TITLE
Feature request: Pre-execution

### ISSUE THREAD

**Issue by IngwiePhoenix** [SocketCluster/socketcluster#116]
People enjoy using stuff like different JavaScript dialects as well as modding `require` itself for a variety of reasons. SocketCluster should, in my opinion, respect that.

The easiest way to do so is to apply this change::

- Add option `preRun`, which specifies one JavaScript file that should be executed BEFORE the actual process runs. Pseudo example:
```javascript
var preScript = SocketCluster.config.preRun; // obtain the preRun script name, should be resolved and alike.
var actualScript = SocketCluster.config.{...}; // Get the actual script to launch. Like the broker or worker script.

if(typeof preScript != "undefined") {
    require(preScript);
}
// Global environment may or may not be modified, 
// allowing even a .coffee or .jsx file to be included now.
require(actualScript);
```

This would allow the user to take all the freedom to register a CoffeeScript-capable require function or alike. It also would allow stuff like `globalize` to auto-load modules, or add whatever is most commonly used into glboal scope!

Alternatively, we could also have the `preScript` export a function with a callback, which would probably look like this:
```javascript
module.exports = function PreScript(run) {
    // Example using my oj-node package:
    require("oj-node");
    run();

    // Async function example
    var redis = require("redis");
    var rc = redis.createClient();
    rc.get("myValue", function(res, err){
        if(err) throw err;
        global.__mySpecialVar = res;
        run();
    });
}
```

How about it? :)

**Comment by jondubois** [comment]
@IngwiePhoenix Yes, I think the second approach makes the most sense.
I think what you're describing is a kind of middleware function which does stuff/modifies the environment all children scripts get executed.

We should try to follow existing conventions relating to middleware functions: See the addMiddleware() method: http://socketcluster.io/#!/docs/api-scserver - We could add a new addMiddleware(...) function on the SocketCluster master instance: http://socketcluster.io/#!/docs/api-socketcluster and the middleware type could be MIDDLEWARE_EXEC 'exec' or MIDDLEWARE_RUN 'run'.

This would be a nice feature. Would you feel comfortable forking SC and implementing this? I will accept a pull request.

You can see how SC implements middleware, here: https://github.com/SocketCluster/socketcluster/blob/master/lib/scworker.js#L168-170 and https://github.com/SocketCluster/socketcluster/blob/master/lib/scworker.js#L195-203

**Comment by jondubois** [comment]
I guess this logic will have to run before workerController and brokerController scripts get required.

See https://github.com/SocketCluster/socketcluster/blob/master/lib/scworker.js#L222-L223

The brokerController logic is actually not directly part of SC (although it follows the same conventions). It's part of nData; see: https://github.com/SocketCluster/ndata/blob/master/server.js#L169-L173

**Comment by jondubois** [comment]
Or maybe this shouldn't be a normal middleware (since passing the function across different processes will be difficult). Maybe it can be an option to the SocketCluster master instance (as you suggested) - Maybe the user should provide the path to the module which is responsible for preprocessing/prerun. I like the idea of this module calling a ```next()``` method when it has finished preprocessing.

**Comment by IngwiePhoenix** [comment]
@jondubois Well, good day. I basically have no internet at my dorm, so when i checked back here only to see so much response, I was like "well, g'day man!" XD.

Okay, but now for real.

As I am not currently really internet-equipped, there is not much I can do as of right now. I do have  mobile data, so I will try to fork SC, commit changes into that, and PR it.

As you seem to like a sort of combination of the first and second approach - the configuration part and the callback part - I will be heading to implement that very thing.

The implementation will have the user supply the path to a module - much like the controllers are supplied as just the file paths. This module will then be loaded, the `module.export`ed function executed with one `next()` parameter, which essentially triggers the next step.

But one things I would like to mention ahead: SC is huge, I'm small :). So I'll do my best to provide that PR!

**Comment by jondubois** [comment]
@IngwiePhoenix Haha, well trying is what counts :p It sounds like we figured out a good solution. I can always make minor changes afterwards to ensure consistency so don't worry about it too much.

I don't have much time right now so even if you have a partial solution, that would help get things started.

**Comment by IngwiePhoenix** [comment]
@jondubois So I just took some time to look at the pieces of code you pointed out. For the WorkerController, it seems totally straight forward to add something by the lines of

```javascript
this.PrerunFunction = require(this._paths.prerunScript);
this.PrerunFunction.run(this);
```

right above it, per-se.

But what about the other controllers? If the Broker is part of nData, what would be the most suitable way to pre-run a script on that one? I will look at the Broker related code next.

**Comment by IngwiePhoenix** [comment]
Looks like `iocluster` is the default module that is required for the Broker stuff. Can you point me towards the right spot to properly pick up in this module?

**Comment by jondubois** [comment]
That's the hardest part. The iocluster module is only responsible for launching a cluster of nData instances and figuring out how to exchange data between them (basically it only manages multiple nData servers).

You probably don't need to think about iocluster. It's easier to just look at an nData server.
This part here is were the nData server receives the workerController filePath: https://github.com/SocketCluster/ndata/blob/master/server.js#L12

Then later, it gets used here: https://github.com/SocketCluster/ndata/blob/master/server.js#L171

The BROKER_OPTIONS here: https://github.com/SocketCluster/ndata/blob/master/server.js#L15 is the same as the initial options object (configs) which you pass to the master SocketCluster instance when initializing.

**Comment by IngwiePhoenix** [comment]
So - both, the actual `socketcluster` module as well as `ndata` need to understand the `prerunScript` option?

**Comment by jondubois** [comment]
Yes, I guess

**Comment by IngwiePhoenix** [comment]
Alright. I better get started! :)

**Comment by IngwiePhoenix** [comment]
All PRs have landed:

https://github.com/SocketCluster/socketcluster/pull/121
https://github.com/SocketCluster/iocluster/pull/3
https://github.com/SocketCluster/ndata/pull/18

Got myself a pizza and some good music and put the changes in. I also have extended the sample app to test the new stuff. It works well! :) 

`let` me know if there is anything that I need to fix. (I love puns.)

**Comment by jondubois** [comment]
Merged.
