### ISSUE TITLE
Trying to use EJS templates in worker

### ISSUE THREAD

**Issue by pandafinity** [SocketCluster/socketcluster#119]
Hi,

I'm new to using SocketCluster, which I think is great but I am having problems with the Server.  I am trying to use SocketCluster with an existing app but when I use the code there is no response from the client, which suggests it's not being connected.

```javascript
module.exports.run = function (worker) {
  console.log('   >> Worker PID:', process.pid);

  var httpServer = worker.httpServer;
  var scServer = worker.scServer;
  var app = express();
  var router = require('../controllers');
  var publicPath = path.join(__dirname,'../../client/public');
  var viewsPath = path.join(__dirname, '../../client/views');

  app.use(express.static(publicPath));

  httpServer.on('req', app);
  dummyData.attach(scServer);
  accessControl.attach(scServer);

  app.set('view engine', 'ejs');
  app.set('views', viewsPath);

  app.use(compression({ threshold: 512 })); //gzip
	app.use(bodyParser.urlencoded({ extended: true }));
	app.use(bodyParser.json());
	app.get('/',router);

  scServer.on('connection', function (socket) {
    authentication.attach(scServer, socket);
    var restOptions = {
      pageSize: 5
    };
    realtimeRest.attach(scServer, socket, restOptions);
  });
};
```
What is it I am not seeing?
Your example uses:
```javascript
var app = require('express')();
```
Where I use :
```javascript
var app = require('express');
```
But I am not sure if it is just that...

Any info would be greatly appreciated :)

Thank you

**Comment by jondubois** [comment]
It should be
```
httpServer.on('request', app);
```

On 'req' is the old way.

**Comment by jondubois** [comment]
Where did you find this snippet?

**Comment by pandafinity** [comment]
Will try that now - thanks.
What snippet?

**Comment by pandafinity** [comment]
Thank you that solved - such a little thing annoyed me for hours :) thank you.

If by the 'snippet' you mean code, it was something I wrote

**Comment by pandafinity** [comment]
(with bits of your 'sc-sample-inventory' thrown in as wanted to see how you added modules and data to the server)

Thanks :)
