### ISSUE TITLE
direct message

### ISSUE THREAD

**Issue by ab4drinkadvisor** [SocketCluster/socketcluster#122]
Hi!
Is there way to send direct message from one client to another ?
Thank you for advice!

**Comment by jondubois** [comment]
@ab4drinkadvisor If you use channels, you can send a message "directly" between clients (the message will pass through the server but you don't have to write any serverside code to handle this).

To subscribe to a new channel:
```js
// Client-side code
// Assume the current user's username is bob123
var userChannel = socket.subscribe('channel_of_bob123');
userChannel.watch(function (data) {
// Handle the data published to the 'channel_of_bob13' channel by other users
});
```

Then if another user wants to send a message to bob, they can just call:
```js
// Client-side code
// Note that the second argument can be any valid JSON object/type
// you don't need to have a from or message field...
socket.publish('channel_of_bob123', {from: 'alice456', message: 'Hi bob!'});
```

**Comment by ab4drinkadvisor** [comment]
Thank you!
But is there another way?
Because if I use your solution, i have to create private channel for each user.
It is not good for performance.

Is there some function like in Socket.io

io.sockets.socket(savedSocketId).emit(...)

**Comment by jondubois** [comment]
@ab4drinkadvisor SC is quite efficient at dealing with channels. It's OK to have hundreds of channels per client.

**Comment by jondubois** [comment]
You can use middleware to restrict which users are allowed to subscribe to what channels (for access control). See section on middleware at the bottom of this page: http://socketcluster.io/#!/docs/api-scserver
