### ISSUE TITLE
next(true) doesn't seem to work

### ISSUE THREAD

**Issue by Anaphase** [SocketCluster/socketcluster#123]
Forgive me if my understanding is wrong, but according to [the single example on this page](http://socketcluster.io/#!/docs/middleware-and-authorization) it appears as if calling `next(true)` within middleware should prevent the event from being published without raising a notice. I can't seem to get this functionality to work; I always get an error like this:

```
1445966195626 - Origin: Master
    [Error] TypeError: Cannot read property 'stack' of undefined
  at EventEmitter.SocketCluster.noticeHandler (/Users/user-name/project-name/node_modules/socketcluster/index.js:334:13)
  at EventEmitter.SocketCluster._workerNoticeHandler (/Users/user-name/project-name/node_modules/socketcluster/index.js:403:8)
  at ChildProcess.workerHandler (/Users/user-name/project-name/node_modules/socketcluster/index.js:497:12)
  at ChildProcess.emit (events.js:98:17)
  at handleMessage (child_process.js:322:10)
  at Pipe.channel.onread (child_process.js:349:11)
```

Since this feature is documented poorly (it's just a comment in an example...), I may be interpreting it wrong, but after perusing the source the can't seem to find anything that would handle `next(true)`... The above error is coming from [SocketCluster.prototype.noticeHandler](https://github.com/SocketCluster/socketcluster/blob/601b42f7e057f9fa9c69cdd0fc84751e7ba8d44d/index.js#L334) - should there be some sort of check [on this line](https://github.com/SocketCluster/socketcluster/blob/601b42f7e057f9fa9c69cdd0fc84751e7ba8d44d/index.js#L497) or in [SocketCluster.prototype._workerNoticeHandler](https://github.com/SocketCluster/socketcluster/blob/601b42f7e057f9fa9c69cdd0fc84751e7ba8d44d/index.js#L398) to check if the error is `true`? Maybe I'm missing something here...

**Comment by jondubois** [comment]
@Anaphase The documentation needs to be fixed. This feature only exists for the publishOut middleware because publishOut tends to get called often and you sometimes want to make it quiet.

Note that if you don't want to see notices, you can raise the logLevel setting in the main SocketCluster config.

It would be nice to implement the same feature for other middleware in the near future.

**Comment by jondubois** [comment]
@Anaphase As of v 2.3.25, if the ```next()``` callback is called with ```true``` as first argument, it will quiety block the action (without emitting any notices on the server or logging to the console). Be careful with this feature though - Notices are a nice way to keep track of what's happening in your system.

**Comment by Anaphase** [comment]
Thanks! This helps fix an annoying bug in my server.
