### ISSUE TITLE
How to send a SocketID a message

### ISSUE THREAD

**Issue by roblav96** [SocketCluster/socketcluster#129]
I have this so far:

server:
```
			redis.get( 'updates:' + message.uname + ':socketID' ).then( function ( doc ) {
				console.log( 'doc >', doc )
				// doc would be the users SocketID
				worker.getSCServer().clients[ doc ].emit( 'message', 'for your eyes only' )
			} )
```
 and on the client:
```
		self.channels.server = self.socket.subscribe( 'message' )
		self.channels.server.watch( function ( res ) {
			console.log( 'res >', res )
		})
```

I just can't seem to get this one way message to work. Is there a
```
socket.to()
```
method of any sort?

**Comment by roblav96** [comment]
I ended up using:
```
worker.getSCServer().clients[ doc ].send( 'dataaaa' )
```
and
```
self.socket.on( 'raw', function ( res ) {})
```

I must have skimmed through the APIs too quickly :X

**Comment by jondubois** [comment]
Looks like you may have mixed up socket.emit(...)/socket.on(...) with pub/sub actions socket.subscribe(...) and socket.publish(...).

Using emit and on allows your to do simple client/server communication, pub/sub channels are separate from this (a higher level of abstraction).
