### ISSUE TITLE
Kickout only works through socket.on( 'message' )

### ISSUE THREAD

**Issue by roblav96** [SocketCluster/socketcluster#130]
The server side kickOut() function can not be understood by the client using socket.on('kickOut') but only by socket.on('message')

server:
```
client.kickOut( data.uname )
```

client:
```
			// works
			self.socket.on( 'message', function ( msg, channel ) {
				console.log( 'msg >', msg )
			} )
			
			// doesnt work
			self.socket.on( 'kickOut', function ( msg, channel ) {
				console.log( 'msg >', msg )
			} )
```

This has been driving me nuts all day. lol I feel stupid for trying the message event so late.

**Comment by jondubois** [comment]
@roblav96 It works for me. What is your client and server version? Do ```socketCluster.version``` on the client to see the client version.

**Comment by roblav96** [comment]
My brains must have been fried eggs the other day. I was trying to kick client out of a channel that didn't exist :X
