### ISSUE TITLE
Sending messages remotely

### ISSUE THREAD

**Issue by kenzik** [SocketCluster/socketcluster#131]
Hello,
is it possible to publish messages from another server to socketcluster, so: server -> socketcluster -> clients (so basically I want to notify socketcluster to emit messages from another server)

I was thinking about using something like json-rpc, but surely there must be a better way to do this.

**Comment by IngwiePhoenix** [comment]
You can either use the socketcluster-client on the other server or use a Redis bridge; i.e., if the broker process and the "remote" are both able to connect to the same redis, you can send messages into a Redis channel, pick them up from the Broker process, which can then emit to the SC clients it has.

**Comment by jondubois** [comment]
As @IngwiePhoenix you can hook SC into Redis or another message queue and SC will automatically sync its channels with Redis. https://github.com/SocketCluster/sc-redis
