### ISSUE TITLE
How to properly store data as a global that every workers can access?

### ISSUE THREAD

**Issue by sainttail** [SocketCluster/socketcluster#132]
I saw from this #82 that propose something like `.get()` and `.set()` and I also saw that i ndata module there actually has those methods https://github.com/SocketCluster/ndata/blob/master/index.js#L478 and https://github.com/SocketCluster/ndata/blob/master/index.js#L364. 

But the documentation in http://socketcluster.io/#!/docs/api-exchange state no information about those functions at all so are those methods usable?

Thanks.

**Comment by jondubois** [comment]
the Exchange object is a cluster of nData clients and has the same methods as an nData client: https://github.com/SocketCluster/ndata
