### ISSUE TITLE
Add support for workers/brokers written with babel/es2015 syntax

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster#135]
In my case, I already had a worker written in es2015 syntax. Unfortunately, since my file is called via a dynamic name instead of a require (it gets the dynamic name in the server.js), i get 'reserved word' errors. The easiest fix (albeit not super eloquent) is to stick this at the top of the 2 files in the `lib`: `require('babel-core/register');`

**Comment by IngwiePhoenix** [comment]
Or, you use the new initController param.
That allows you to have one file that calls the babel registrar for you. That is exactly what this is meant for :)

**Comment by mattkrick** [comment]
Oh man, feel free to tell me to RTFM next time, I can't believe I missed that. Works beautifully, thanks!

**Comment by IngwiePhoenix** [comment]
Funnily, I was the one who introduced and PRd this feature - its pretty new, yknow :)
So no worries! Thats what questions are for.

Enjoy!
