### ISSUE TITLE
Managing user-specific subscriptions

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster#136]
Wondering about structuring a semi-private subscribe... Let's say I have a `todo` table & each todo item has a `userId` and `teamId`. Each user belongs to 1 or more teams. Let's say a user (`userId:123, teamId:['blue', 'red]`) wants to subscribe to all the blue team's todos. 

To subscribe, I'd call something like `socket.subscribe('todo?teamId=blue')`. Then, in the middleware, I'd grab the `userId` from the JWT (I manually stored it there), look up the user's doc in the DB, verify that the user belongs to the blue team, & if so, allow the subscription.

Is there a more eloquent way? Doing this causes an extra hit to the DB for every subscribe to check permissions (but I guess it beats saving the  `teamId` array in the JWT). Plus, it requires writing a middleware for each subscription type.

**Comment by jondubois** [comment]
I think storing channel permissions in the JWT upon successful login is actually a good strategy for reducing hits on the database - You just establish all channel permissions up front. Then in the subscribe middleware, you could just check the JWT token (```socket.getAuthToken()```) and if the channel name matches one of the entries in the token, then you can allow the user, otherwise you block them.

**Comment by jondubois** [comment]
Making a database call in the middleware is good if you need down-to-the-millisecond accuracy regarding the user's access rights. Storing it in the token theoretically gives the user access to the channel so long as the token is not expired.

**Comment by mattkrick** [comment]
this helps! Checking around the web I saw a few cases where arrays are used in JWTs too (so long as theyre not huge or arrays of objects, i guess that's a slippery slope). As for the middleware, for database pulls I suppose 1 middleware per server publication is the best way to go about it. thanks!
