### ISSUE TITLE
SocketCluster v4 RFC

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#137]
This is the plan for SC version 4 - The main goal of this release will be to improve the flow related to:

- Authentication
- Authorization
- Middleware
- Error handling
- Token expiry
- Channel subscriptions

... And how they relate/interact with one another.

Feel free to post comments here if you wish to add something or want to make suggestions.
This release might break some stuff, but we should try to keep it mostly compatible with previous versions (so migration shouldn't be too difficult).

Note that implementation of v4 is currently in progress. Changes are currently being added/merged to the ```v4``` branches of various SocketCluster repos.

**Current changes proposal** - This is open to review/changes. Completed tasks have been ticked.

- [x] Make middleware APIs consistent across different middleware types. "Currently, each one has different args. Let's offer two: a request object and a next function.
The request object's properties are populated based on the type of middleware.
For example, subscription has a socket and channel prop." - @mattkrick

- [x] Add a private (not visible to SC users) ```MIDDLEWARE_AUTHENTICATE``` middleware which will sit in front of all other middleware types (and thereby intercept all inbound messages/actions from the client) and its purpose will be to check the JWT token expiry - If it finds that the token has expired, it will remove the (expired) token from the server-side socket (so the ```socket.getAuthToken()``` method will return null/undefined) and emit a ```deauthenticate``` event on the client-side socket. It will also add an ```authTokenError``` property to the req object. This middleware will not block the request (even if token is expired), it will just pass it along to the following middleware and that middleware will be the one to decide whether or not the block the request/event.

- [x] Implement client-initiated and server-initiated deauthentication. See https://github.com/SocketCluster/socketcluster/issues/137#issuecomment-160970767

- [x] Middleware errors can be triggered by the developer by passing a string or error to the ```next()``` callback inside middleware and will cause the 'error' event to be triggered on the client socket. Errors will have a name which will identify the error.

E.g.
```js
socket.on('error', function (err) {
  if (err.name == 'UnauthenticatedSubscribeError') {
    console.log(err.message); // -> 'Not allowed to subscribe to the foo channel'
    console.log(err.channel); // -> 'foo'
    // ...
  } else if (err.name == 'UnauthenticatedPublishError') {
    // ...
  } else if (err.name == 'UnauthenticatedEmitError') {
    // ...
  } else {
    // ...
  }
});
```
The user can customize the properties of the Error object from the server by passing an object to the ```next()``` callback on the server. E.g:
```js
next({
  name: 'UnauthenticatedSubscribeError',
  message: 'Could not subscribe to ' + req.channel + ' without a valid auth token'
});
```
The error provided can also be a custom error object:
```
next(new MyCustomError('Custom error'));
// OR
next(req.authTokenError)
```
If the user provides a string (allowed for backwards compatibility reasons), it will be cast into an error behind the scenes (maybe on the client-side).

- [x] Errors emitted on the client should always be ```Error``` objects and never strings. If errors originated from middleware on the server (as strings), we should rehydrate them to be ```Error``` objects when on the client-side.

- [x] The subscribe method should accept an optional options argument ```socket.subscribe(channelName, [options])``` - This options object could have a ```waitForAuth``` (boolean) property which could allow the user to specify that this channel should wait for the socket to be authenticated before trying to subscribe.

- [x] Passing an error to the emit response ```respond(err)``` should not trigger an 'error' event on the client-side. It's a business logic (soft) error and not a socket error.

- [x] Will need to make sure that all errors throughout SC (client and server) have a appropriate types (and should never be strings - Always inherit from Error object) - Example client-side timeout errors: https://github.com/SocketCluster/socketcluster/issues/137#issuecomment-160613867 

**Discussions**

- https://github.com/SocketCluster/socketcluster-server/issues/1
- https://github.com/SocketCluster/socketcluster-client/pull/28

Thanks to @mattkrick for all the input.

**Comment by mattkrick** [comment]
Thanks for getting this all together! Couple thoughts:
 - Is it too verbose to have a listener for each error class? (I say error class where 1 class can have many types). Since the dev will have to do this parsing by error type anyways (eg `'subscribeError'` is a class that can contain a `tokenError` or `permissionError` or something user defined), the workflow doesn't change, but we do save 6 or 7 listeners from being created on the client if we emit them all under `'error'` and it keeps the API lightweight. Not sure which is right...

- should we have a `waitForAuth` on emit? That'd make it: socket.emit(event, data,[options],[callback]), where the callback is determined by seeing if the last arg is a function. 4 args is pushing it, but it doesn't seem right to only give that functionality to `subscribe`.

**Comment by mattkrick** [comment]
1 housekeeping item for v4: the website should show return values for events. Eg `'subscribeFail'`: returns `error, channelName`. Maybe a table with with 3 columns: listener, return values, description?

**Comment by jondubois** [comment]
I was thinking that the error passed to the 'subscribeError' handler would always be of type 'MiddlewareBlockedError' (or similar).
The token-expiry error would have its own event - E.g. 'authenticateError'

So if a token expires during a subscribe request, the private authentication middleware on the server would
emit an 'authenticateError' on the client and then the subscribe middleware might block the request and therefore emit a 'subscribeError'
on the client immediately after.

But even so, you raise a fair point.

Do we prefer this:

```js
socket.on('authenticateError', function (err) {
  console.log(err.message); // -> 'The JWT token has expired'
  // Redirect the user to the login screen.
  // ...
});

socket.on('subscribeError', function (err) {
  // err.message is whatever error was provided to the next(error) call in the middleware on the server
  console.log(err.message); // -> 'Socket is not allowed to subscribe to the foo channel because the socket did not have a valid token'
  console.log(err.channel); // -> 'foo'
  // We can notify all relevant components that they are not
  // authorized to subscribe to the 'foo' channel.
  // ...
});

socket.on('publishError', function (err) {
  // ...
});

socket.on('emitError', function (err) {
  // ...
});
```

Or this:

```js
socket.on('error', function (err) {
  if (err.type == 'AuthenticateError') {
    console.log(err.message); // -> 'The JWT token has expired'
    // Redirect the user to the login screen.
    // ...
  } else if (err.type == 'SubscribeError') {
    console.log(err.message); // -> 'Socket is not allowed to subscribe to the foo channel because the socket did not have a valid token'
    console.log(err.channel); // -> 'foo'
    // We can notify all relevant components that they are not
    // authorized to subscribe to the 'foo' channel.
    // ...
  } else if (err.type == 'PublishError') {
    // ...
  } else if (err.type == 'EmitError') {
    // ...
  } else {
    // ...
  }
});
```

**Comment by jondubois** [comment]
So my idea at the moment is to trigger both the 'authenticateError' and the 'subscribeError' independently (this approach considers the authentication problem as being completely independent from the authorization problem).

I think one of the earlier ideas thrown around was that if the middleware blocked the request, it would trigger a single error event on the client and that error would be either an authentication error or an authorization but not both.

The second approach is a bit like HTTP status 401 (not authenticated) vs 403 (forbidden). Each HTTP request can only have a single response so it can only be 401 or 403 but not both.

I feel that the first approach offers better decoupling, but at the same time, I'm not decided on which one is more practical.

**Comment by mattkrick** [comment]
I like where this is going. I remember you earlier mentioned you wanted to allow for user-defined errors within middleware. Is that still the plan? I also like the parity to HTTP codes where the token fail is a 401 and a middleware fail is like a 403.
I'm not a fan of 1 event triggering 2 listeners though, I think the errors should happen is a series: first authentication, then authorization. If authentication fails (and the middleware cares about it failing), it should short circuit before hitting the authorization. Maybe something like this?

```
//comes from jwt-middleware after a failed token
const req = {
  socket: SCSocket,
  channel: 'user123',
  data: {foo: 'bar'},
  tokenError: TokenError
}

function userDefinedMiddleware(req, next) {
  if (req.tokenError) {
    //don't bother authorizing if authentication failed
    return next(req.tokenError)
  }
  const token = getAuthToken();
  if (token.channel !== req.channel) {
    return next(new AuthorizationError('User not allowed in channel'))
  }
  next(req);
}

//verifyInboundEvent shortcircuits if 'req instanceof Error'
```

**Comment by mattkrick** [comment]
One other consideration-- callback errors. Right now, if the first arg isn't null, if get's sent through the 'error' listener. That means if a dev wants to receive an error from their callback that isn't an Error object, or doesn't want that to trigger an `error` listener, they have to put the error in the 2nd argument. Personally, I'm not a fan of this side effect behavior since callbacks & events serve the same purpose, but understand that 'error' was originally designed as a catchall. 

For v4, I say callbacks shouldn't trigger any errors since they're used for things like failed schema validation, failed DB inserts, etc, Whereas the 'error' event can be for Error objects like ack timeout, token expire, and middleware fails (assuming they're all left under the 'error' heading).

**Comment by jondubois** [comment]
@mattkrick Ok, I made more changes to the specs based on new feedback. I also added a 'deauthenticate' event which will be triggered on the clientside (initiated by the AUTHORIZATION/TOKEN_EXPIRY middleware). Note that this is not an error event. We have an 'authenticate' event, so we should also have a 'deauthenticate'/'unauthenticate' event too.

**Comment by jondubois** [comment]
Errors will have a name which indicate specifically what kind of error it is. E.g. 'SubscribeError' and optionally also a type which tells us what kind of error this is. E.g. 'AuthenticationError'.
The user can also add custom properties to the error object (whatever they feel necessary to help them handle the errors effectively on the client-side)... They could add a 'code' property if they wanted to assign error codes to their errors.

**Comment by mattkrick** [comment]
I like the deauthenticate event. Will `removeAuthToken` trigger that as well or will it use a callback? If the client uses an expired token to subscribe, that means the deauthenticate event will fire (with 0 args) as well as a subscribeFail (with a rehydrated Error), right?

For user-defined errors, will the devs write the errors as objects, or will they write them as an instanceof an Error & then SC dehydrates the Error into an object before sending it on the wire? If it's the latter, will they be able to import SC errors like 'AuthorizationError' so they can use them in the middleware?

If I understand correctly, the client will get something roughly like this?
```
| Error Name          | Error Type          | Source                                           | Listener (option #1) | Listener (option #2) |
|---------------------|---------------------|--------------------------------------------------|----------------------|----------------------|
| ConnectionError     | ConnectionError     | Can't connect due to [code] or unknown           | connectionFail       | error                |
| ConnectionError     | HeartbeatError      | Ack timeout                                      | connectionFail       | error                |
| ConnectionError     | HandshakeError      | Handshake failed (include middleware?)           | connectionFail       | error                |
| AuthenticationError | AuthenticationError | Token doesn't exist or is expired                | authenticationFail   | error                |
| SubscribeError      | [userDefined]       | subscribe middleware                             | subscribeFail        | error                |
| PublishError        | [userDefined]       | publish_in or publish_out (separate?) middleware | publishFail          | error                |
```

**Comment by jondubois** [comment]
I'm not sure what we should do with the ```removeAuthToken``` event if we add a deauthenticate event... Should we remove it?
Maybe we could provide an argument to the 'deauthenticate' handler which tells it whether or not the token exired or was removed intentionally
by the server... Not sure.

Regarding middleware errors - I think the user should be able to pass either a plain object, an Error object (or derived class)
or a string (for backwards compatibility). If a string is provided, SC will construct an Error object with a default name
and type depending on the middleware (E.g. name: 'SubscribeError', type: 'UnauthorizedError').

Here's a potential variation to the table of errors you posted earlier ():

```
| Error Name          | Error Type          | Source                                           |
|---------------------|---------------------|--------------------------------------------------|
| ConnectionError     | ConnectionError     | Can't connect due to [code] or unknown           |
| ConnectionError     | HeartbeatError      | Ack timeout                                      |
| ConnectionError     | HandshakeError      | Handshake failed (include middleware?)           |
| ConnectionError     | ...                 | ...                                              |
| AuthenticationError | AuthTokenInvalid    | Provided token was invalid                       |
| AuthenticationError | AuthTokenExpired    | Provided token was expired                       |
| SubscribeError      | [userDefined]       | subscribe middleware                             |
| PublishError        | [userDefined]       | publish_in or publish_out (separate?) middleware |
| ...                 | ...                 | ...                                              |
```

If the error has type ConnectionError, the err object should have a ```code``` property containing the status code.
A lot of generic socket error types can fall under the error name 'ConnectionError'.

I'm leaning more towards all errors going through a single 'error' event - It's nice to have all core error-handling logic in a central place.

**Comment by mattkrick** [comment]
Here's what I'm thinking for deauth:
Client induced:
1. Client calls `removeAuthToken` (takes no args) 
2. Deauth is sent to server & AuthEngine optimistically deletes the local token, sets `isAuthenticated` to false and clears the expiry timeout handler (assuming SocketCluster/socketcluster-client#31). If it can't delete the local token (super rare, but necessary if I'm debugging my custom AuthEngine), locally emit `AuthenticationError Cannot delete local token` under the `error` listener.
3. If deauth is successful on server, emit  `deauthenticate` to client, else emit `AuthenticationError: Cannot delete server token` under the `error` listener. (error case should be super rare)
4. External client listener for `deauthenticate` let's the dev do whatever, no internal listener needed.

The only edge case with this is that the event doesn't guarantee the token is gone locally by the time it's received since we don't control AuthEngine (eg it could sleep 10 seconds before executing the delete, or it could fail), but realistically I think that's acceptable since we can guarantee that `isAuthenticated` is locally set to false so worst case scenario is the state is corrected on the next round-trip.

Server induced starts from the success case of step 3 (if there is an error with deleting the token on the server it should not propagate down to the client, since the client didn't ask to be deauthed).
***
For middleware errors, I think SC should be opinionated & only accept one option (although if backwards compatibility is a big issue, it could accept strings but be undocumented & removed by v5). I don't have a strong preference between objects & Error-objects, but If you go the `instanceof Error` route, here's a good example to follow: https://github.com/neumino/thinky/blob/master/lib/errors.js. This would end up looking like:
```
import {SubscribeError} from 'socketcluster-client`;
customerError = new SubscribeError();
customError.type = 'UserDefinedFail';
next(customError);
```
***
I agree with the single listener & codes in connection error, that should keep the API clean!

**Comment by jondubois** [comment]
@mattkrick I'm happy with your suggestions for the deauth flow - In this case, maybe we should rename ```socket.removeAuthToken()``` to ```socket.deauthenticate()``` since it will now do a bit more than just removing the token.

Also, I'm thinking that maybe we shouldn't have an error 'type' property because it seems confusing (especially since we also have a name property).

Also what would happen if the token had expired and we called ```next(req.authTokenExpiredError);``` inside the subscribe middleware?

The req.authTokenExpiredError would look like this:

```js
{
  name: 'AuthTokenExpiredError',
  type: 'AuthTokenExpiredError',
  message: 'The JWT auth token has expired'
}
```

So when the client would receive this error inside the ```error``` handler, we wouldn't know that it is a ```SubscribeError``` because the name ```AuthTokenExpiredError``` would have overwritten the default ```SubscribeError``` (even though it comes from the subscribe middleware.

We could make it so that ```next(err)``` ignores the name of the error provided and just copies the other properties (and keeps the name as 'SubscribeError') but that seems too magical and confusing for a new developer.

Maybe instead, we should add an ```action``` property (or maybe there is a better name??) to whatever error object is passed to the ```next(myErrorObject)```. For example; for the subscribe middleware, the value of the ```action``` property would be ```subscribe```. For the publishIn middleware, the value would be ```publish```, etc...

So then to check, we could do:

```js
socket.on('error', function (err) {
  if (err.action == 'subscribe') {
    // ... Error while performing 'subscribe' action
  } else if (err.action == 'publish') {
    // ... Error while performing 'publish' action
  } else {
    // ... Other kinds of errors.
  }
});
```

... Or maybe there is a better way.

**Comment by mattkrick** [comment]
Yep, the rename sounds good. 

 >  Also what would happen if the token had expired and we called next(req.authTokenExpiredError); inside the subscribe middleware?

I'm thinking between middlewares we check to see if the object `instanceof Error`. If it's true, we shortcircuit the middleware chain & emit the error to the client. I'm not sold on this syntax, we could also have the user set the error property on the req & then they could write `if (req.error instanceof Error) next()` and then every empty request would emit the Error from the error prop (or make one if it's null).
***
That's a really good point about Error name & action/source. I think I'm overcomplicating it. As a dev, my thought is, "I don't care where the error came from, I care about what it is." If in a special case I *do* need to know what middleware it occurred in, I can create a custom Error (eg `UserDefinedSubscribeError`). This is nice because we don't have to check for all user-defined props on the Error object & only send 2 fields to the client.
```
socket.on('error', function (err) {
  if (err.name == 'AuthTokenInvalid' || err.name == 'UserDefinedSubscribeError') {
    // ... Do stuff
  } else if (err.name == 'AuthTokenExpired'  || err.name == 'HandshakeError') { 
```
This could be useful in a later version, where we also emit it internally on the server. This would open the door to log errors generated by certain users (eg user 'abc' with IP 127.0.0.1 keeps requesting data that doesn't belong to him, ban him).

**Comment by jondubois** [comment]
@mattkrick The reason why I would like to to add a ```type```/```action``` property to the error object is because a single action (E.g. ```socket.publish(...)```) could fail from a number of different causes. A 'middleware blockage' is just one of two ways a publish action could fail - The other way is a timeout - If the connection is bad.

Often, the developer just wants to track if a specific action failed (they might not want to know about all the different kinds of errors which could cause that action to fail). It would be nice to have a way to group multiple errors so that the developer can easily check if an action failed without having to add multiple ```if (error.name == 'PublishBlockedError' || error.name == 'PublishTimeoutError' || ...)``` - If there was a single shared action property, the user could just go ```if (error.action == 'publish')``` and all errors related to that action could be handled in the same place.

Note that it doesn't matter in the case of subscribe because subscribe actions can never timeout... This is because SC manages retry behavior behind the scenes - So the user-defined middleware error is the only possible error in this case, but the publish or emit actions are examples of actions which might each fail from two different causes (userDefined middleware error and connection timeout error).

**Comment by mattkrick** [comment]
Ah, I didn't know there were other points of failure, good to know! So what's the difference between an emit timeout error and a connection heartbeat error? Could we lump emit & publish timeouts in the same heartbeat error & call it a timeout error for the purpose of the client? (Totally OK to shoot the idea down)

**Comment by jondubois** [comment]
@mattkrick I guess grouping errors based on action is not that important. I think the benefits of having a lot of different error types outweighs the inconvenience of having to know about them - So long as they are documented.

If a user wants to know if a specific action failed (for any reason), they can just provide a callback to whatever method they're using. E.g. ```socket.publish('channelName', data, callback)``` - All errors would be passed to that callback (regardless of the error type).

Effectively, the 'error' handler will be useful for adding generic error-handling logic (based on error types), while the callback will be useful for handling failures related to specific actions (without regard for error types). So actually this setup is quite flexible.

We could lump together publish and emit timeout errors under the same 'AckTimeoutError', but this is different from the heartbeat/ping timeout.

The ping timeout might happen beacause of a poor/lost connection. The ackTimeout is separate and it can be caused by two things:

- Poor/lost connection
- The server is taking too long to process the action (even though the connection itself is fine)

We could have a single 'AckTimeoutError' or have separate timeout errors for each type of action: 'PublishTimeoutError', 'EmitTimeoutError'. Maybe the second case is better; these are two different error cases and will often require different handling.

**Comment by jondubois** [comment]
@mattkrick thanks for all the help with this - I'm going to update the specs tomorrow with the stuff about errors and other stuff from our discussions. I think this is getting close to ready (I think it all fits together really nicely so far).

Let me know if you want to get involved with implementation too. I will add more bullet points to the list at the top and you can just pick the ones you want to do. (If you want... No pressure).

**Comment by mattkrick** [comment]
Agreed, I think it all looks pretty good! I'm happy to help, just give me a piece or 2 of the spec & I'll have something in a day or 2. 

Before you start the spec, have you thought anymore about `isAuthenticated` logic on the client? We'll need that for the `deauthenticate` in additional to the new `waitForAuth` proposal. I personally think it'd be a good idea to establish a numeric value of how much faster the server clock is ahead of the client clock (SocketCluster/socketcluster-client#32). If we did that, we'll need to incorporate a timestamp on the client & server ends of the handshake, so this seems like the right time to introduce it.

PS, not sure if it's useful for this discussion, but I plan on holding all these errors (along with the rest of the socket state) in a redux store (https://github.com/mattkrick/redux-socket-cluster#api, or see it in action here https://github.com/mattkrick/meatier). Obviously I'll change the logic to match the socketcluster spec, but maybe it can serve as a user story. Hopefully this explains why I needed socket caching/multiplexing, `isAuthenticated`, and well defined errors.

**Comment by jondubois** [comment]
The flow I had in mind for deauthentication is:

1. ```socket.isAuthenticated``` is ```false``` initially
2. The socket connects, then authenticates itself via the handshake (which will provide a JWT token to the server if one exists)
3. Once the handshake completes sucessfully (assuming there was a valid token), the client-side 'connect' event will trigger and the ```socket.isAuthenticated``` property will be set to ```true```

Client-initiated deauth:
4. Some time later, the frontend calls ```socket.deauthenticate()```
5. The ```socket.isAuthenticated``` status is immediately set to ```false``` on the client, then a ```#deauthenticate``` event is emitted to the server.
6. Once the socket on the server-side receives the #deauthenticate event, it will remove the token from the socket (so, from now onwards, calling ```socket.getAuthToken()``` will now return null/undefined)

Server-initiated deauth:
4. Some time later, the backend calls ```socket.deauthenticate()``` - The token will immediately be removed from the server-side socket.
5. A ```#deauthenticate``` event is emitted to the client
6. When the client receives this event, ```socket.isAuthenticated``` will be set to ```false```.

5.5. For server-initiated deauth, before the client receives the ```#deauthenticate``` event from the server
(and before it changes its ```isAuthenticated``` state to ```false```) - For a brief moment, it will wrongly believe that the socket is
still authenticated (```socket.isAuthenticated``` will be ```true``` on the client even though the token was already removed from the server).
If the client tries to perform an action (e.g. ```socket.publish(...)```) which requires authentication during this short period, the relevant (e.g. publish)
middleware on the server will send back an appropriate user-defined error (e.g. UnauthenticatedPublishError) to the client.
Because of the in-order delivery guarantees offered by TCP, we can guarantee that we will receive the ```#deauthenticate``` event before the 
UnauthenticatedPublishError is triggered (which is nice).

If we go down this path, we don't need to do client-side token expiry. We can let the jwt-expiry middleware handle this. Basically it means that the token expiry won't happen in realtime (it will only happen as a result of a client-server interaction - Which might fail as a result). I think that's fine because we can never guarantee that the server and client are in sync anyway - That's OK, so long as we send the client an appropriate error and allow it to correct its state.

I don't like the idea of trying to synchronize expiry times on different machines - This sounds easy at first but it's actually impossible to do with perfect accuracy. In part because you can never accurately predict the latency between the server and client (the clocks will almost always be a few milliseconds out of sync as a result) - And if the client tries to perform an action during that small millisecond gap, it would be out of sync with the server's authenticated state.

So we would end up adding a lot of complexity and end up with a solution which will be perfect 99.9% of the time but when it will eventually fail (and it will), the error will be confusing (and it will be impossible to reproduce under test conditions because it happens so rarely).

Also there is the unusual case that the client might change their computer's time while they're using the app... Or maybe they're using it when daylight savings kicks in (and the time on their computer immediately increments by one hour) then the client will wrongly believe that the token has expired.

**Comment by mattkrick** [comment]
Very well thought out.
- For client step 5, you're also calling `AuthEngine.removeAuthToken`, right? It doesn't matter when it finishes, but I think it's important to (eventually) remove bad tokens from the client.
- What are your thoughts on token renewal? In your example app, the server renews the token every 3 mins. Is this still the preferred approach? I like that the renewal originates from the server. Any thoughts on building renewals into socketCluster? Maybe an `autoRenew` param with a default of an hour? FWIW, here's what the auth0 guys do: http://stackoverflow.com/questions/26739167/jwt-json-web-token-automatic-prolongation-of-expiration
- Regarding 5.5 and the server-latency heuristic, I think they're the same problem: the client's `isAuthenticated` is wrong (if only for a couple milliseconds). I agree with your approach. As long as there is a sound renewal strategy, this won't even come up.
- Regarding the server-latency heuristic, it doesn't matter if the latency changes or the client changes their clock because the `setTimeout` is initiated during authentication (and if I have a `setTimeout` to execute in 60 seconds, it'll still takes 60 seconds, even if I set my clock 59 seconds faster). That said, I'm cool if the expiry only happens on the server, just wanted to make sure all your assumptions were correct before you made the decision. Assuming renewals are handled properly, I'm splitting hairs over a no-op.

**Comment by jondubois** [comment]
@mattkrick Yes, I forgot to mention that, it will remove the token from the client at step 5.

I think at this stage token renewal should be handled by the client - This offers the most flexibility (and there is an infinite number of ways to do this). It's just a matter of the user calling ```socket.setAuthToken(...)``` from the server.

Yes it's true that the solution I proposed has the same problem as yours ultimately. Also, it's true that a setInterval solution probably wouldn't be affected by a user changing time on his machine (I guess it depends on how it's implemented). I guess I like the approach I described more because the behaviour is more predictable and I prefer to keep the client lightweight.

**Comment by mattkrick** [comment]
Sounds good, except for renewals. The client can't be guaranteed to handle renewals without having at least an estimate of the server time. The JWT has an expiration in server time, so the client effectively doesn't know when the token will expire until it receives an AuthError from the server, which is no good. In 99% of cases, this is fine because the refresh frequency is greater than the token life (unless the difference between server and client is greater than the life of the token, then we have an infinite series of renewal requests).

What might be nice is having the server perform a renew on a 1 hour (or user-defined) interval. That could save us a trip from the client to the server & make the client 100% independent of the server time. Thoughts?

**Comment by jondubois** [comment]
@mattkrick I meant it should be handled by the server (not client) :p I used the wrong word.
As you mentioned, the approach so far has been for the developer to write a setInterval() on each socket on the server after they login which keeps renewing the token.

I don't know if we should automate this. I need to think about it more.

**Comment by jondubois** [comment]
I decided to remove the ```waitForAuth``` option for the ```emit()``` function (but keep with for the ```subscribe()``` function).
There can only ever be one pending subscription per channel. For emit, however, you could have as many pending emit events as you like... This could cause the 'waitForAuth' queue to become massive and freeze the app when the socket finally becomes authenticated. It's too dangerous - It's better if the developer checks themselves whether or not the socket is authenticated - There will be a new fproperty on the socket object which will make this easier.

**Comment by mattkrick** [comment]
sounds reasonable, but (playing devils advocate here) a user could already flood the buffer while the connection is being established. https://github.com/SocketCluster/socketcluster-client/blob/f67df0c793f0557f2da1a8b56460e478c396cf4a/socketcluster.js#L635-L653

An alternative would be to put a LIFO cap on the `_emitBuffer` (eg if `linkedlist.length > 10000` ignore the emit), which would solve both problems. 
Both are such edge cases that it's really only to prevent malicious actions, so I don't have a strong preference either way.

**Comment by jondubois** [comment]
@mattkrick They can't really flood the buffer too much because emitted messages would timeout. With waitForAuth, I'm not sure having a timeout would be appropriate. I will think about the LIFO cap; that might be a soution - I think this should be considered for a later release... Maybe 4.1

**Comment by mattkrick** [comment]
Ahh my bad, I only saw the timeout for durable messages, not for the queue. Thanks for all the work you've put into this!

**Comment by jondubois** [comment]
I removed the point about "removing the subscribeFail event and emitting it as an 'error' event instead" - I think we should keep 'subscribeFail' because:

- Subscription failure is not a socket error - It is an application-level error which is not related to SC itself.
- This approach is consistent with changes introduced in v4; I.e. ```socket.emit('eventName', callback)``` no longer emits an 'error' event on the socket when it fails; the callback is the only place where the error will be handled - That is because it is now considered an application error.
- Pusher.com has both a subscription_succeeded and a subscription_error events so this approach is already quite common.

**Comment by happilymarrieddad** [comment]
Is it possible to have an event that a client can "publish" to that will send an event to every other client except for the client the requested the event at the worker level?

**Comment by mattkrick** [comment]
@happilymarrieddad
Now that i'm done laughing at your awesome username, I do something similar when changes propagate from the DB (and of course the DB doesn't know which `socketId` made the edit):
 - when worker receives an event, it stores the `docId` in a socketId-specific queue
 - on any error, remove the `docId` from the queue, emit error if necessary
 - Before a change is sent to the client, check the queue. If found, remove it & don't emit (emit ack or use callback if necessary)

That way you can achieve an optimistic UI while minimizing data over the wire (at the expense of added state to your worker).

**Comment by mattkrick** [comment]
@jondubois Finally getting time to dig in, here are a couple thoughts after reviewing the new API & website docs, let me know your thoughts:
 - Clearly state that 'pending' is the initial state for `authState`. Or should there be another initial state? Is it possible for a socket to connect without requesting auth? 
 - Are all `SCWorker.error` and `SCWorker.notice` messages safe to send to the client? Can we ignore these & assume that all relevant client info is sent to SCSocket (client) as an error? A list of messages would be useful in an appendix somewhere
 - Client: a list of `SCSocket.error` messages in an appendix would be great to know which ones might be useful to display to the end user or can be used to trigger actions (eg popup a modal if `message === x`)
 - if you refer to prop names like `socket.CONNECTING` as a constant, should we export these directly from the package so folks can use them before calling `connect`? eg `import {CONNECTING, CONNECTED} from 'socketcluster-client'`
 
That's all for now, I might have 1 or 2 once I dig into the errors & notices & middleware. Cheers!

**Comment by jondubois** [comment]
@mattkrick 

- 'pending' generally means that the authState is not yet known but will be known soon. Channels also have the concept of 'pending' and 'subscribe'.
- Yes you can send back any error to the client - They will be dehydrated on the server and rehydrated on the client. If the error is related to SC (not user-defined), then it will be one of these types: https://github.com/SocketCluster/sc-errors/blob/master/index.js (I will make a list of them on the website at some point).
- You can already access those as static properties on the class itself. E.g. ```socketCluster.SCSocket.CONNECTING``` - This should be documented

**Comment by jondubois** [comment]
I guess the bulk of v4 is complete so I'm closing this. Anything new from now on can be raised as a separate issue for a minor release.

**Comment by ibrahim9** [comment]
Any plan to resolve this? https://github.com/SocketCluster/socketcluster/issues/133

**Comment by jondubois** [comment]
@ibrahim9 Presence is outside of the immediate scope of SC but you can get a module for it: https://github.com/coinigy/sc-presence

**Comment by jayesh-sapkale** [comment]
## socket.io
        socket.connected['socket_id'].emit('event-name',data);
## socketCluster
      ?????????????????????????
