### ISSUE TITLE
Socket Connection Issue (China/Mexico/Hungary/Japan)

### ISSUE THREAD

**Issue by ryanpager** [SocketCluster/socketcluster#143]
So, so far I love socket cluster. After converting from socket.io im seeing way better performance, stability, etc. Im having a small issue though, clients in certain regions (china, hungary, mexico, japan) are not able to connect in to the socket server depending on their setup (internet connection / computer).

Our current setup is as follows,
- 1 Elastic Loadbalancer (TCP 80 forwarded to TCP 7000)
- 2 C4.2xlarge EC2 Instances (Running on 7000, 4 workers, 4 brokers)
- Loadbalancer is CName'd to a vanity url for easy connection.
- All of this is on 'HTTP' *not* 'HTTPS'

Load on the server is usually max ~ 5-10% of all cores, but can spike up to about 30-40% if there is a massive spike in usage.

I have all security dropped on the servers, and nothing blocking any connections, so I am completely stumped. The weird thing is, most of these people have 2 internet connections -- 1 works, the other doesnt. Same computer setup, same everything, just different internet connection.

We have ~ 50,000 other people using the server at any given time successfully, so that makes it even more tricky to figure out whats going on with the select few.

Any ideas on this one / anyone run into this problem before?

**Comment by jondubois** [comment]
Is the SC/WebSocket connection over plain HTTP/WS (not HTTPS/WSS)?

Some proxies are known to kill/block long-lived raw WebSocket connections.Users who are connected to the internet through some corporate networks may encounter such issues.
Connecting to SC via HTTPS usually fixes this.
The other thing to consider is that some old browsers don't support WebSocket.I know China is really weird when it comes to browsers; they have a lot of people still using old versions of IE.
- Jon

**Comment by ryanpager** [comment]
@jondubois 

Completely agree with what you explained -- we did have some trouble with long lived socket connections but this wasnt the issue. It was an issue with getting the socket connection the first time. We might need to try HTTPS instead of HTTP, 

Completely weird, will update with what I find out through changes on EC2 / EBS / etc!

**Comment by ryanpager** [comment]
@jondubois 

The problem was with the security groups on EC2 & EBS...weird.

One other question though, very random people (people in japan), are getting socket disconnects. Is there something that can cause this -- or a server setting I can increase to fix disconnects. I looked at "ackTimeout" but im not sure if that has anything to do with disconnects.

Its not consistent which is really annoying.

**Comment by jondubois** [comment]
@ryanpager You can increase the ```pingTimeout``` and ```pingInterval``` option on launch.
http://socketcluster.io/#!/docs/api-socketcluster

**Comment by ryanpager** [comment]
@jondubois 
Wow, I feel like a moron. Yup, that fixed it. We somehow missed a "0" in the pingTimeout, so it was extremely low -- fixed a whole bunch of issues.
