### ISSUE TITLE
Crashing in OSX

### ISSUE THREAD

**Issue by drojas** [SocketCluster/socketcluster#146]
This one is odd:

The following is happening to me with code generated by `$ socketcluster create myApp` and with hand-typed code made while reading the docs.

```bash
   myApp :
   node server.js
   [Busy] Launching SocketCluster
   >> Broker PID: 64290
   >> Worker PID: 64294
   [Active] SocketCluster started
            Version: 4.0.0
            Port: 8000
            Master PID: 64289
            Worker count: 1
            Broker count: 1

internal/child_process.js:586
    var string = JSON.stringify(message) + '\n';
                      ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at process.target._send (internal/child_process.js:586:23)
    at process.target.send (internal/child_process.js:507:12)
    at EventEmitter.handleError (/Users/drojas/Code/myApp/node_modules/socketcluster/lib/workercluster.js:132:13)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.SCWorker.errorHandler (/Users/drojas/Code/myApp/node_modules/socketcluster/lib/scworker.js:349:8)
    at Domain.<anonymous> (/Users/drojas/Code/myApp/node_modules/socketcluster/lib/scworker.js:33:23)
    at emitOne (events.js:77:13)
    at Domain.emit (events.js:169:7)
1452295228118 - Worker 0 exited - Exit code: 7
   >> Worker PID: 64295
1452295228491 - Worker 0 was respawned
internal/child_process.js:586
    var string = JSON.stringify(message) + '\n';
                      ^
```

The _weird_ part is that after a machine reboot, there is no crash at the first run (per app), but if I then kill the process and start it again, the error follows.

I'm still finding where to put a debugger to start tracking it. First I tried to re-define JSON.stringify to land a debugger (on the three javascript files) but so far, no success. After the 'init' message I get no more breakpoints before the error.

I'm not sure if I should report this here so I'll leave some detail:

```bash
myApp :
   uname -v
Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64

   myApp :
   node -v
v4.2.1

   myApp :
   pcat package.json
{
...
  "version": "1.0.0",
...
  "dependencies": {
    "connect": "3.0.1",
    "express": "4.13.1",
    "minimist": "1.1.0",
    "serve-static": "1.8.0",
    "socketcluster": "4.x.x",
    "socketcluster-client": "4.x.x"
  },
...
}
```

btw: Thanks for open-sourcing this library!

Update:
May be related to: https://github.com/tcs-de/nodecache/issues/21
Node v5.4.0 also throws

**Comment by IngwiePhoenix** [comment]
I also use OS X and never had this issue.

Can you provide some version numbers?

**Comment by drojas** [comment]
Yes, what version numbers?

**Comment by jondubois** [comment]
@drojas You may want to do ```npm cache clean``` and then reinstall SC from scratch - There was a bug in the ```sc-errors``` module which caused an issue like this (this has been fixed). You may want to get the latest sc client as well - v4 is a bit unstable right now.

I will push another update of SC today to address a few other minor issues which were introduced in v4.

**Comment by drojas** [comment]
@jondubois that helped, the server is not crashing anymore, but the worker is now. I'm seeing this (again, after a first successful run):

```bash
1452308011427 - Origin: Worker (PID 24950)
   [Error] Error: bind EADDRINUSE null:7173
    at Object.exports._errnoException (util.js:856:11)
    at exports._exceptionWithHostPort (util.js:879:20)
    at cb (net.js:1299:16)
    at shared (cluster.js:588:5)
    at Worker.<anonymous> (cluster.js:562:9)
    at process.<anonymous> (cluster.js:714:8)
    at emitTwo (events.js:92:20)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at internal/child_process.js:497:7

**Comment by IngwiePhoenix** [comment]
Check for zombie processes. You might have a process using the very port here - or it is a debug port problem. But check for zombie procs first.

**Comment by drojas** [comment]
I can confirm that the generated code on _myApp_ works fine after the clean/reinstall, it just fails on another codebase (running inside _electron_, btw). This issue is no longer relevant I guess.

**Comment by drojas** [comment]
For the record (or may be the docs), the "problem" with electron was that I wasn't managing the socketcluster process properly, this is how I'm doing it now and it works.

```
