### ISSUE TITLE
broken npm install (need to npm publish sc-simple-broker)

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster#147]
current message when installing from npm
```
npm ERR! No compatible version found: sc-simple-broker@1.2.x
npm ERR! Valid install targets:
npm ERR! 1.1.0, 1.0.0
```

guessing you didn't publish the latest to npm?

**Comment by jondubois** [comment]
@mattkrick I haven't encountered this problem. sc-simple-broker 1.2.0 is published: https://www.npmjs.com/package/sc-simple-broker

Does doing ```npm cache clean``` fix the issue?

**Comment by mattkrick** [comment]
weird,e up there now! sorry bout that.
