### ISSUE TITLE
Need help on Java client for socketCLuster

### ISSUE THREAD

**Issue by AnandItagi** [SocketCluster/socketcluster#150]
I am new to web socket
Please suggest me If any socket cluster Java client available
we need to send push notification from Java App server to angular app using web socket

**Comment by efkan** [comment]
:+1:

**Comment by jondubois** [comment]
@efkan I'm not currently aware of any good Android client. We have an 'unofficial' iOS client https://github.com/abpopov/SocketCluster-ios-client.

I believe that @abpopov is (or at least was) working on an Android client too (not sure about progress). You can chat with him on Gitter: https://gitter.im/abpopov

**Comment by abpopov** [comment]
We have android client for our project, I hope soon we will make lib for android, which anybody can use.

**Comment by mkgn** [comment]
Currently SocketCluster/socketcluster-client-android doesn't seem to be maintaining properly and seems like a dead project. This client seems to be the next option that is available. Can we publish something workable so that we can move forward with development?

**Comment by tux-world** [comment]
@abpopov hi. Could you share your library? I need to have that on android application. Thanks a lot

**Comment by mkgn** [comment]
Oops, i think my message confuses people. What I wanted to tell was that I am also looking for a native client for Android & since the socketcluster-client-android seems pretty much dead, may be we can get whatever abpopov has done and carry it forward.

**Comment by jondubois** [comment]
I started writing the official SC protocol guide here in case anyone is interested: https://github.com/SocketCluster/socketcluster/blob/master/socketcluster-protocol.md

**Comment by MegaGM** [comment]
https://github.com/SocketCluster/client-drivers
