### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by till** [SocketCluster/socketcluster#152]
Hey, I am not sure I understand how the tests are supposed to work. Also, once I figure this out, would you be open for having the tests run on e.g. Travis-CI?

Anyway, I `npm install`'d in the root of the repo, then `node test/internal/index.js`:

```
module.js:340
    throw err;
          ^
Error: Cannot find module 'socketcluster-client'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/path/socketcluster/test/internal/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by jondubois** [comment]
@till Yes, the tests right now are extremely primitive. It would be nice to use something like mocha and have them run using the ```npm test``` command. Right now, you run the tests by running the index.js files using node. E.g. ```node index.js```. They are just integration tests - On directory has tests for checking the external behavior of SC and the other one checks internal logic like making sure objects are cleaned up internally... I think the internal stuff is pretty basic, but it would be nice to add more 'external' integration tests to validate the behavior of SC.

Feel free to restructure this as you see fit.

You can look at how we did tests for ```sc-broker``` if you need ideas (it is for the broker process in SC): https://github.com/SocketCluster/sc-broker/tree/master/test 

Personally I'm not a huge fan of unit tests in JS (not sure how much value they add vs the cost of keeping them up to date) but feel free to do whatever :p

**Comment by jondubois** [comment]
I can't reproduce your issue though, it works for me. It looks like your socketcluster-client module might be missing though, maybe it didn't get installed properly for some reason.

Also, yes getting TravisCI setup would be awesome.
