### ISSUE TITLE
Does socketcluster ensure emit order?

### ISSUE THREAD

**Issue by Kequc** [SocketCluster/socketcluster#157]
If I send out a whole bunch of emits of different sizes from the client to the server in a sequence, does socketcluster ensure the order of their arrival? Similarly, is it the same from the server to the client? It seems to be true.

But I cannot find documentation that specifically mentions this.

**Comment by jondubois** [comment]
@Kequc Yes, the underling transport is WebSocket/TCP - So you get guaranteed, exactly-once in-order delivery over the life of the connection.

**Comment by Kequc** [comment]
There was some conflicting information on [stackoverflow here](http://stackoverflow.com/questions/14287224/processing-websockets-messages-in-order-of-receiving). This seems like it should be there I'm happy to hear that it is.

I hope it wasn't inappropriate to have asked in a ticket.
