### ISSUE TITLE
Quick (probably simple) Newbie Question

### ISSUE THREAD

**Issue by leedium** [SocketCluster/socketcluster#158]
I'd like to run several SC instances in each of their own Docker container.  Would a generic Node image be sufficient?  Anyone here have experience with socketcluster and Docker?

Cheers!

Thanks!

**Comment by jondubois** [comment]
@leedium SC now has its own Docker image https://github.com/SocketCluster/socketcluster#docker-and-socketcluster - It can even run and scale automatically on Kubernetes. We will add more docs about running it on Kubernetes at some point in the near future.
