### ISSUE TITLE
How to specify multiple redis server instances in brokerOptions

### ISSUE THREAD

**Issue by rohittailor** [SocketCluster/socketcluster#163]
Hi,

We configured socket cluster on two server machines with load balancer. For load balancer we are using two machines and from firewall level load balancer we are pointing to node load balancers (Active-Passive config) 

We have configured two Redis server instance on load balancer machines. 
In socket nodes (both machines) inside socket cluster config we need to mention brokerOptions like below:

 brokerOptions: {
         host: '10.193.118.44',
        port: 6379
  }

Is it possible to set IP addresses of both redis instances in broker options ? or something through which we can detect redis server is up or not and change redis instance address in brokerOptions at runtime ?

**Comment by rohittailor** [comment]
I tried to modify sc-redis and checking redis connection error and trying to connect to other redis server instance but it's trying to connect to OLD instance as well:

subClient.on("error", function (err) {
		console.log("Error in redis server connection to "+subClient.address);
		brokerOptionIndex = brokerOptionIndex == 0 ? 1 : 0;
		brokerOptions = broker.options.brokerOptions[brokerOptionIndex];

		console.log("REDIS HOST "+brokerOptions.host);
		subClient.quit();
		pubClient.quit();
		subClient.unref();// = null;
		pubClient.unref();// = null;

		delete require.cache[require.resolv('redis')];
		redis = require('redis');
		subClient = redis.createClient(brokerOptions.port, brokerOptions.host, brokerOptions);
		pubClient = redis.createClient(brokerOptions.port, brokerOptions.host, brokerOptions);
	});

	subClient.on("ready",function(obj){
		console.log("Connection established to redis server "+subClient.address);
	});

**Comment by jondubois** [comment]
@rohittailor You could provide a domain name (or subdomain) instead of an IP address for your Redis instances - Then you can setup a load balancer on that subdomain and loadbalance between the two Redis instances (the load balancer could detect if a Redis instance is down and stop sending traffic to that instance).

You could try setting up Redis cluster - But I haven't tried it myself so I can't really help much with that.

**Comment by rohittailor** [comment]
I am now checking redis connection error at sc server 'fail' event and making connection to different redis instance in case previous instance terminated.

**Comment by happilymarrieddad** [comment]
I've build a redis cluster module if anyone's interested. It's in my repositories.
