### ISSUE TITLE
FAQs - Authentication and middleware authorization

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#164]
Here are some FAQs relating to authentication and middleware-based authorization - Copied straight from Gitter. Hopefully this will be useful.

**General info**

> atbyrd 01:35
> @jondubois So is "isAuthenticated", in the docs, something that is part of the library or do I need to implement this?
> 
> jondubois 07:42
> @atbyrd There is an authState property here: http://socketcluster.io/#!/docs/api-scsocket-client
> authState can be 'authenticated', 'unauthenticated' or 'pending'
> 
> jondubois 07:52
> When you connect initially, the authState will be 'pending' then once you invoke socket.setAuthToken(myPlainTokenObject) on the server, the client will be sent a signed copy (a JWT token) of the object and the client socket's authState will switch to 'authenticated'. Note that the 'authStateChange' event will trigger on the client socket as well.
> If authentication is lost for whatever reason (e.g. when the user logs out - I.e. By calling socket.deauthenticate() or when the JWT token expires), the authState will switch to 'unauthenticated'.
> 
> jondubois 07:59
> Note that JWT tokens have an expiry date (default is 1 day I believe), but if you want to have a shorter expiry (like 10 minutes), you may want to keep renewing the JWT token by invoking socket.setAuthToken(myPlainTokenObject) on the server-side from time to time (e.g on an interval while the client is still connected - That will stop the token from expiring in the middle of a session). Each time you call setAuthToken, a fresh copy of the token (with new expiry) will be sent to the client.
> 
> jondubois 08:05
> You can configure channels to only subscribe when the client is authenticated (these act like private channels) using the waitForAuth: true option of the client-side socket.subscribe(...) method here http://socketcluster.io/#!/docs/api-scsocket-client
> 
> jondubois 08:13
> Note that for efficiency reasons, JWT tokens will not expire until the client tries to perform an action (E.g. emit(), publish() or subscribe()). So by default the client will still be able to passively receive channel data from channels which they were subscribed to before the JWT token expired. If you want to remove the token as soon as it expires (even if the client just stays idle passively consuming channel data), you can manually force the JWT token to be destroyed by calling socket.deauthenticate() from the server when a timeout is reached (for example).

**Authenticating using a token from an external provider**

> atbyrd 08:15
> The problem that I'm having is that I have another system which is providing authtokens via jwt. I only need to verify that the message is signed with the same secret as SC there is no authentication that I actually need to handle and inside of SC.
> 
> jondubois 08:16
> In that case, you can use the socket.authenticate(myJWTToken) from the client - This is client-initiated authentication
> You can provide the authKey here: http://socketcluster.io/#!/docs/api-socketcluster
> If it matches the secret key of your other provider, then it should just all work automagically
> 
> atbyrd 08:17
> Is there a specific kind of error that will be return that I can return to the client if auth fails?
> This is all done in the Handshake middleware?
> 
> jondubois 08:19
> You should block it in the middleware by sending back an error if you detect that the token has expired.
> It can be done in any middleware
> 
> atbyrd 08:20
> Ok, thanks. Once I rest I should have a better understanding
> 
> jondubois 08:20
> If you look at middlewares here http://socketcluster.io/#!/docs/middleware-and-authorization - The req.authTokenExpiredError property will be set to an Error if SC detects that the token has exired. Otherwise req.authTokenExpiredError will be undefined.
> Typically, you just want to block the request by passing that Error to the next(req.authTokenExpiredError) callback
> But you can pass any error you want... You don't even have to block at all if you don't want (in some odd cases, it may be OK to allow clients with expired tokens to continue). Authentication vs authorization are separate concerns in SC.
> 
> atbyrd 08:22
> a string?
> 
> jondubois 08:22
> It will be an Error object
> You can also provide a string if you like
> 
> atbyrd 08:22
> cool
> 
> jondubois 08:22
> but an Error object with a name property is the best

**Comment by KrishnaPG** [comment]
I am sorry, but even after reading the above, I am kind of lost. Does SC automatically take care of OAuth? 

If not, how easy / difficult it is to integrate with 3rd party middleware such as: http://passportjs.org/

One of the threads pointed in the above discussion is referring to https://github.com/sahat/satellizer but not sure how easy it is to use it (because it looks like the statellizer is only for Angular frontend).

Does SC take care of creating and delivering the front end login-pages automatically on the fly ?
