### ISSUE TITLE
FAQs - One-to-one communication between two users

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#165]
Here are some FAQs relating to one to one communication between two users - Copied straight from Gitter.

**Sending messages between two users; one-to-one**

cailosidfu Mar 22 21:56
I'm creating a chat app in order to learn socketcluster.
But I hit a wall 
Chat has several rooms (i'm using one channel for each room), and users can send private 1-1 messages.
And I'm stuck with 1-1 messages. The "use case" I'm trying to solve is: A wants to send B a private message (My intention was to do: A emits to SC (so SC can check if A is blacklisted by B) and then SC emits the message to B.
I'm using sc-redis to get horizontal scalability, but I have no idea how I can do the private messaging if A is connected to SC-instance1 and B to SC-instance2
Anyone can point me how I can progress?

jondubois 13:51
@cailosidfu emit should primarily be used for client-to-server communication. Otherwise you run into the scalability problem which you just described.
A solution is to setup a 'private' channel for each user and using middleware, you can block anyone who is not that user from subscribing to that channel.
See the section on middleware here http://socketcluster.io/#!/docs/middleware-and-authorization
I've seen a lot of different approaches for dealing with the problem you've described but pubsub is the simplest, most reliable one that actually scales.
A good convention for private channels is to include the username as part of the channel name - So if the username is `bob123`, the channel might be called `private-bob123` (for example) - Or you can have multiple private channels too...

jondubois 13:57
If you look at the subscribe method here http://socketcluster.io/#!/docs/api-scsocket-client - There is also a waitForAuth option which you can specify to make the channel automatically wait for the user to authenticate before it tries to subscribe. When we say 'private channel', we generally mean a channel that has the waitForAuth option set to true.

cailosidfu 17:39
@jondubois so if I understood you right, the flow can be:
A emits to SC-instance1 ("PRIVATE_MSG-B","Hello B")
-SC-instance1 does scWorker.exchange.publish("private-B",{from: "A", message:"Hello B"})
Am I missing something?

jondubois 19:36
You can do that... Or you can publish directly from the client socket (you don't always have to publish from the server).

**Sending back acknowledgements of a message received using channels**

cailosidfu 20:30
and as an additional question, I was intending to use the emit-callback option to ack reception of the private message:
A emits to SC -- > SC emits to B --> B calls callback on SC --> SC calls callback on A
so if I use channels, do I have to implement the callback/ack functionality?

jondubois 23:19
@cailosidfu Another good question! One way is to setup an ack channel for each user so that users can acknowledge receiving each other's messages.
Or you could publish back a specially-formated ack message to the other user's channel... E.g. {type: 'ack', messageId: 'theidofthemessagewhichwasreceievedbytheotheruser'}
Regarding your first question, yes you can enforce access control in MIDDLEWARE_PUBLISH_IN to restrict who can publish to that user's channel. You should also add a middleware in MIDDLEWARE_SUBSCRIBE to make sure that only the user can subscribe to his own channel.

**Comment by zalmoxisus** [comment]
Also, related: https://github.com/SocketCluster/socketcluster-client/issues/39.

Usually you don't want to lose offline messages and want the ability to sync different clients (web and mobile app). So, a more universal solution is to use [sc-crud-rethink](https://github.com/SocketCluster/sc-crud-rethink) and to insert messages in the database. It is easy to subscribe for new messages (new fields) there, and also can remove / edit messages. I'm just exploring this scenario.
