### ISSUE TITLE
Import/require in documentation?

### ISSUE THREAD

**Issue by alphashuro** [SocketCluster/socketcluster#166]
I'm just starting out with socket cluster (with webpack) and I am stumped by your documentation. It contains this as the example for using sockets on the client:
```
// Client code
socket.emit('ping', 'This is a PING message')
```
How do I require that 'socket' object? Please add this to all parts of the documentation as it is actually quite confusing.

**Comment by jondubois** [comment]
@alphashuro Thanks for pointing this out, that was a pretty massive gap in the documentation!

The code snippet should be a bit more clear now. Also, I added links to more docs.
http://socketcluster.io/#!/docs/getting-started

**Comment by alphashuro** [comment]
So I'm not supposed to ```npm install socketcluster-client```? Your documentation only mentions ```var SocketCluster = ('socketcluster').SocketCluster;```, so you're saying thats the object i should use to connect on the client side as well?

**Comment by jondubois** [comment]
@alphashuro If you install the full framework using the CLI ```socketcluster create``` command, it will install the client for you automatically.

But you can install the server and client separately too if you like... Or sometimes you may want to update the client without updating the server, that's fine too.

**Comment by alphashuro** [comment]
Would it not be helpful to include import/require instructions for people who use npm rather than the socketcluster cli, because some people my not start development using any cli's or they might decide to add socketcluster to the existing node project just by npm installing the framework's packages.

**Comment by jondubois** [comment]
Thanks for the feedback.

You install the socketcluster cli through npm using ```npm install -g socketcluster``` then you can generate the project using ```socketcluster create myprojectdir```.

But yes, I agree we should add more instructions to make this clearer and to give the user options.
The website http://socketcluster.io/#!/ is open source https://github.com/socketcluster/socketcluster-website so feel free to contribute if you have any ideas (pull requests welcome).

I've been involved with SC for a while now so it's hard to me to see all the gaps like you would :p

**Comment by jondubois** [comment]
The actual website docs in are in the repo here: https://github.com/SocketCluster/socketcluster-website/tree/master/public/app/views/docs

**Comment by alphashuro** [comment]
:D I didn't realize it was open source, thank you. I will make a pull request and take it from there!

**Comment by jondubois** [comment]
Yeah I should probably encourage everyone to contribute to the docs more. Especially now that the API has become pretty stable.

**Comment by alphashuro** [comment]
That would be awesome, perhaps a link to the docs github page on the introduction of the docs?

**Comment by jondubois** [comment]
Yeah sure :)
