### ISSUE TITLE
RFC: socket.subscribe takes a data object

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster#167]
Currently, the API for socket.subscribe looks like this: `socket.subscribe(channelName [, options])`

I propose `socket.subscribe(channelName [, data] [, options])`

The use case:
You may need to pass in other variables that you don't want to put in the `channelName`. For example if you use GraphQL, you may want to pass in the queryString. If you're subscribing to a single object where the ID won't change, then you can make a user-specific subscription (eg instead of `cars/123` you could just subscribe to `myCar`).

Alternatively, this can currently be done by putting a lookup table on the server. This works as long as the `data` is **not** user-defined.

Open to thoughts on how to tackle this problem!

**Comment by jondubois** [comment]
@mattkrick I like the idea of passing custom data to the options object. So the signature would still be:
```socket.subscribe(channelName[, options])``` but the options object could be like (example with waitForAuth set to true):

```
{
  data: someData,
  waitForAuth: true
}
```

**Comment by jondubois** [comment]
Ok, this was implemented in socketcluster-server v4.1.11 and socketcluster-client v4.3.14
