### ISSUE TITLE
Switch to fs-extra

### ISSUE THREAD

**Issue by kievechua** [SocketCluster/socketcluster#170]
We should upgrade it to maintained module.

wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

**Comment by jondubois** [comment]
Yes that's on my TODO list :)

**Comment by jondubois** [comment]
That's been done... There is now a new warning that comes up related to node-fs-extra... We will upgrade at some point but it's not really a problem anymore.
