### ISSUE TITLE
How does storage work?

### ISSUE THREAD

**Issue by hopewise** [SocketCluster/socketcluster#174]
As mentioned in the features, SC works with any DB, I tried to search about how to store messages at http://socketcluster.io/#!/docs but I didn't find a related docs for DB or storage..

There is an important question also, Would storage affect performance of publishing-receiving messages ?

how would SC store the messages in for ex mongoDB without affecting the performance of SC server? As there might be thousands of messages sent the server per second, how would the storage works if we needed to store all incoming messages? 

is data-sync supported?

**Comment by jondubois** [comment]
@hopewise Yes adding storage would consume extra CPU and memory. There is a CRUD plugin which allows storing data in RethinkDB using CRUD operations from the frontend (with realtime updates) - You can achieve the same results as data sync except without native conflict resolution support.

Data sync with automatic conflict resolution can be really clumsy (and sometimes dangerous), we prefer to let the frontend know that the connection has been lost and let the frontend decide if/how they want to recover from a period of lost connection.

You can have a look at this boilerplate if you want to see a sample app (all data is updated in realtime with pagination) https://github.com/socketcluster/sc-sample-inventory - We also made some Polymer components to bind to the data in realtime.
