### ISSUE TITLE
SocketCluster emit event to specific client(socket)

### ISSUE THREAD

**Issue by jayesh-sapkale** [SocketCluster/socketcluster#175]
## socket.io
        socket.connected['socket_id'].emit('event-name',data);
## socketCluster
    i'have no idea hot to emit to specific client in socketCluster.

**Comment by jayesh-sapkale** [comment]
- i found solution: 
- 
-  var scServer = socketClusterServer.attach(server);
-  var clients=scServer.clients;
-  var specific_client=clients['socket-id'];
-        specific_client.emit("event-name",{});

**Comment by jondubois** [comment]
@jayesh-sapkale Yes that works but be careful though because if you add a second worker process, you may find that the client you're looking for is connected to a different worker than your current one...

Sometimes is' better to use pub/sub channels and let clients subscribe to channels (instead of trying to target specific clients).

**Comment by jayesh-sapkale** [comment]
@jondubois  Thank you for your fast reply.
But i have one another problem can you help me there?

in socket.io express session can easily access by socket.request.session 

but what syntax for access express session  in socketCluster.

**Comment by jondubois** [comment]
@jayesh-sapkale SC also has a ```socket.request``` object on the server-side to access the express session.

**Comment by jayesh-sapkale** [comment]
@jondubois  :: here is my code :::: 
 
session set in express-session already --->  req.session.my_session {hello:'jondubois'};

/*socket cluster code*/
```
 var socketClusterServer = require('socketcluster-server');
 var io = socketClusterServer.attach(server);
      io.on('connection', function(socket){
            /*Connect successfully*/
            console.log(socket.request.session);  //undefined where in regular http request it is accessible
       });
```

**Comment by happilymarrieddad** [comment]
@jayesh-sapkale  One of the things you can do is have each client connect to a channel associated with their id so that you can broadcast on that channel and it will only be intercepted by the client associated with that id. I hope that helps.

**Comment by jayesh-sapkale** [comment]
@happilymarrieddad @jondubois thank you  guys.
