### ISSUE TITLE
Manage sockets/channels subscription from server

### ISSUE THREAD

**Issue by jfsimon** [SocketCluster/socketcluster#178]
Hello,

I can't find a way to subscribe a socket to a channel **from the server**. `SCSocket.subscribe(channel)` is only available on the client. Is there a reason for that?

My use case is:

* each channel represent a team ;
* when a user do something, all teams he belongs to must be notified ;
* a user can not choose which team he's able to subscribe to (this is managed by an admin).

Here is the code I wrote **server side** which does not work:

```js
worker.scServer.on('connection', socket => {
    const teams = [ 1, 2 ];
    _.each(teams, team => socket.subscribe(`team:${team.id}`)));
});
```

How do you think I could implement it?

**Comment by happilymarrieddad** [comment]
@jfsimon  Hey man use the exchange from the worker. For example:

var broadcastChannel = worker.exchange.subscribe('broadcast');
broadcastChannel.watch(function(data) { // Do something with data })

**Comment by jfsimon** [comment]
@happilymarrieddad should I understand there is no way to manage sockets/channels subscriptions from the server? Given your example, how can I send data to the right clients?

**Comment by jfsimon** [comment]
@happilymarrieddad I see a solution:

* let client subscribe to channels
* listen to subscription from server
* us `SCSocket.kickOut()` to cancel unauthorized subscriptions

Let me know if you think there is a better way.
Thanks you for your help!

**Comment by jondubois** [comment]
@jfsimon You can't subscribe on behalf of client sockets from the server directly - It encourages bad habbits.

You can do the approach as you described but the best way is to use the MIDDLEWARE_SUBSCRIBE middleware to block the subscribe request before it is even processed by the SC server. See http://socketcluster.io/#!/docs/api-scserver

**Comment by jfsimon** [comment]
@jondubois oh, it sounds great! If I understand, inside the middleware function, I call `next()` only if the client is allowed to subscribe to the channel, am I right?

**Comment by jondubois** [comment]
@jfsimon ```next()``` to pass ```next(errorObject)``` to block. You SHOULD call next in any case (eventually) otherwise SC will just hang on to the connection until it times out (which works but isn't ideal).

**Comment by jfsimon** [comment]
@jondubois ah, okay. Thank you for the tips, very helpful! I close this issue.
