### ISSUE TITLE
How to pass Express session in socketCluster

### ISSUE THREAD

**Issue by jayesh-sapkale** [SocketCluster/socketcluster#182]
I recentyl change socket.io to socketCLuster 

  var io = require('socket.io')(8081);

        io.use(function(socket, next) {
            sessionMiddleware(socket.request, socket.request.res, next);
        });

in socket.io i  set and get session like : socket.request.session.session_value = 10

how to set and get in socketCluster ??

**Comment by jondubois** [comment]
@jayesh-sapkale There is no 'session' object in SocketCluster. But you can set a JWT token using `socket.setAuthToken({username: 'foo123'})` then later, you can access that token from both the client and the server using `socket.authToken` - You can store any information inside the token but don't store any private data like passwords.

**Comment by jayesh-sapkale** [comment]
@jondubois thank you for information.
