### ISSUE TITLE
Authentication documentation seems outdated

### ISSUE THREAD

**Issue by facundoolano** [SocketCluster/socketcluster#185]
The middleware example in http://socketcluster.io/#!/docs/authentication shows a `function (socket, channel, data, next)` callback which didn't work when I tried it. Changing the callback to `function (req, next)` as shown in http://socketcluster.io/#!/docs/middleware-and-authorization fixed it.

**Comment by jondubois** [comment]
@facundoolano Thanks. Fixed. http://socketcluster.io/#!/docs/authentication
