### ISSUE TITLE
Global emit

### ISSUE THREAD

**Issue by trzyrazyzero** [SocketCluster/socketcluster#190]
Its possible to emit to all connected clients across workers?

**Comment by jondubois** [comment]
@trzyrazyzero Yes, you can setup a global channel like `'some-global-channel'` and make all your client sockets subscribe to it. Then, whenever you want to broadcast a message to EVERY client, you just do `socket.publish('some-global-channel', {foo: 'bar'});`

**Comment by trzyrazyzero** [comment]
Its only way?

**Comment by jondubois** [comment]
No but it's the most scalable way. With this approach, your system can scale infinitely to any number of users. Another approach is to iterate over all `scServer.clients` and call `emit(...)` on each socket individually but this doesn't always scale as easily.

**Comment by trzyrazyzero** [comment]
Okey, thanks for response
