### ISSUE TITLE
swallow warnings?

### ISSUE THREAD

**Issue by seiyria** [SocketCluster/socketcluster#191]
Is it possible to just swallow warnings? I get "Warning: Socket Hung Up" a LOT while in development, and I'd like to turn it off in the case that NODE_ENV isn't production. I've tried adding event handlers for the `'warning'` event everywhere and doing nothing, but that doesn't seem to work.

**Comment by jondubois** [comment]
@seiyria Yes you can set the `logLevel` option to `2`.

**Comment by seiyria** [comment]
Awesome, thanks @jondubois!

**Comment by jondubois** [comment]
@seiyria Sorry I mean logLevel `1` - See http://socketcluster.io/#!/docs/api-socketcluster

**Comment by seiyria** [comment]
No problem. I tried it out real quick and when it didn't work, I knew what to look for. If nothing else, hopefully it will help someone searching the tracker like I was doing.
