### ISSUE TITLE
Publish only to one client

### ISSUE THREAD

**Issue by trzyrazyzero** [SocketCluster/socketcluster#192]
Its it possible?

```javascript
scServer.exchange.publish('Game', {
    test: 1,
    s: 2
});
```
Its publish to all clients.

**Comment by trzyrazyzero** [comment]
```javascript
socket.subscribe('test').watch(function (data) {
    abc(data);
});
```
and i publish it to all clients:
```javascript
scServer.exchange.publish('test', 'some string');
```
but i want too on first client connection send to only to him
```javascript
socket.emit('test', 'some string');
```
doesnt work, so should i do something like this:
```javascript
socket.on('test', function(data) {
    abc(data);
});
```
and on client side i will have ON and SUBSCRIBE same channel?

**Comment by jondubois** [comment]
@trzyrazyzero You could have each client subscribe to their own channel, for example:
```
socket.subscribe('test_alice').watch(function (data) {
  abc(data);
});
```

and then when you want to send a message to the user 'alice', you would go:

```
scServer.exchange.publish('test_alice', 'some string');
```

The trick is to incorporate a username or userid as part of the channel name itself. SC is really good at handling LOTS of unique channels.

**Comment by juxtaposition** [comment]
jondubois has right. The better practices is create a model for you channels, and have a service (handler) for you channel's model. 

for example: 
```
socket.subscribe('alice:UUID_CONTEXT').watch(function(data) {
   log(data);
});

// server side
function sendToSomeone(data) {
  scServer.exchange.publish('alice:context', data);
}```

**Comment by happilymarrieddad** [comment]
@trzyrazyzero Hey man, in our app we have a general broadcast channel, a customer channel and a user channel. For example, we have maybe 100 customers with each customer having 100 users. If we need to emit to a specific user, we publish to that user's channel. If we need to publish to all of one customer's users then we publish on their customer channel and if we need a general publish we publish on the broadcast channel. I hope that helps!
