### ISSUE TITLE
'socketcluster create' fails on windows due to uws

### ISSUE THREAD

**Issue by picitujeromanov** [SocketCluster/socketcluster#195]
Creating app structure...
Installing app dependencies using npm. This could take a while...
npm WARN package.json socketcluster-sample@1.0.0 No repository field.
npm WARN package.json socketcluster-sample@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your operating system or architecture: uws@0.6.2
npm ERR! notsup Valid OS:    darwin,linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64

**Comment by jondubois** [comment]
@picitujeromanov If you do `npm cache clean` and then install again, it should fix it. Let me know if you still get issues. Make sure you get the latest https://www.npmjs.com/package/socketcluster-server dependency.

**Comment by picitujeromanov** [comment]
it works, thank you mate @jondubois

**Comment by efkan** [comment]
Hi @jondubois ,

I wonder that how did you install `SocketCluster` on Windows despite `uws` issue?
I couldn't install the newest version because of `uws` and `windows`. Then I installed `v4.6.0`.

**Comment by jondubois** [comment]
@efkan Make sure you do `npm cache clean` before you install. You need to make sure you have the latest `socketcluster-server` dependency https://www.npmjs.com/package/socketcluster-server

**Comment by efkan** [comment]
Now it works for me too :smile: 

For some reasons I had tried to clean cache manually.

Thanx!
