### ISSUE TITLE
how to support cross-browser/cross-device?

### ISSUE THREAD

**Issue by sfsw** [SocketCluster/socketcluster#196]
hi, my socketcluster servers are behind the firewall, I knew socket.io supports cross-browser/cross-device, so how to combine these?

**Comment by jondubois** [comment]
SC also has cross-browser and cross-device support. Older corporate firewalls can block raw ws:// traffic. In this case you will find that using wss:// should fix the problem. You just have to provide a key and certificate to the main SocketCluster constructor.
