### ISSUE TITLE
SIGSEGV | Node v4.4.6 | SC v4.6.2

### ISSUE THREAD

**Issue by tephro** [SocketCluster/socketcluster#197]
Greetings, Jonathan!

I noticed that sometimes my SC app complaining about segmentation fault, as you can see below.

1467728671013 - Worker 1 exited - Exit code: null, signal: SIGSEGV
1467728671475 - Worker 1 was respawned

Do you have any ideas? The app uses 4 workers (with --max-old-space-size=2048) and lives on Centos 7 x64 (3.10.0-327.22.2) with lots of free RAM.

Thank you.

**Comment by jondubois** [comment]
What do your configs look like? Are you using uws or the default ws module as the WebSocket engine?

**Comment by tephro** [comment]
Right, I'm using uws.

Here is the config.

new SocketCluster({
    wsEngine: 'uws',
    workers: 4,
    brokers: 1,
    port: 80,
    appName: "xxx",
    workerController: __dirname + '/worker.js',
    brokerController: __dirname + '/broker.js',
    socketChannelLimit: 10,
    rebootWorkerOnCrash: true,
    protocol: 'http',
    pingTimeout: 60000,
    pingInterval: 25000,
    ackTimeout: 45000,
    origins: 'xxx:80',
    logLevel: 1,
    propagateNotices: false,
    middlewareEmitNotices: false,
    downgradeToUser: 'xxx'
});

**Comment by jondubois** [comment]
@tephro SC is currently using uws version 0.6.3 - You could try upgrading the dependency to `uws` v 0.7.0 and see if that fixes the problem?

If not, does switching to plain `ws` fix the problem?

**Comment by tephro** [comment]
Thanks, I will try both options and let you know.

**Comment by tephro** [comment]
Not a single segfault under quite heavy load after updating `uws ` to 0.7.0.
Jonathan, thank you for quick suggestion. You're very helpful.

**Comment by jondubois** [comment]
@tephro Cool, I will update the default uws version to 0.7.0. Let me know if you run into new issues.
