### ISSUE TITLE
Microservices - how to multiplex connections?

### ISSUE THREAD

**Issue by vicneanschi** [SocketCluster/socketcluster#199]
I'm building WebSockets microservices that are consumed from the browser. Let's say I have dozens of them. I don't want to have dozens of TCP connections. Correct me if I'm wrong but browsers have limitations on the number of concurrent connections to one host.

From what I understand each microservice is a separate SocketCluster application (server/brokers/workers).

Is there a way to multiplex the connection? For example Socket.io provides the concept of [namespaces](http://socket.io/docs/rooms-and-namespaces/).

Maybe there is a way to host multiple different workers on one SocketCluster server?

**Comment by jrylan** [comment]
Could you have a single SocketCluster service and use channels? I've done some performance testing with SocketCluster and ran into no problem with a browser being subscribed to even 1,000 SocketCluster channels.

**Comment by jondubois** [comment]
@vicneanschi as @jrylan mentioned, you can use channels. SC is designed to handle lots of concurrent channels. Each SC worker can handle over 20K channel subscriptions per second if you're using the uWS engine.

Other than that, SC doesn't have explicit namespaces - All events and channel names are plain strings but you can have your own conventions. You can implement a URL-like scheme when emitting events like `'service-1/event-name'`.

But yeah, I highly recommend trying out channels.

**Comment by vicneanschi** [comment]
I need to host each service in a separate process. They come from different developers and should be deployed independently .

**Comment by jrylan** [comment]
@vicneanschi In my experience a SocketCluster worker can do pretty much anything, you could definitely build in some sort of router into the worker. In my app, the worker sends request to Express, and I have a custom abstraction over Express's built-in routing to send different responses depending on the domain name being requested. 

Maybe something like that and a mixture of namespace prefixed channels would suit your use case?

**Comment by vicneanschi** [comment]
@jrylan I see what  you mean. But it's a bit different.

I want to run different services (business logic) but independently so that they are isolated one from another and failure in one of does not affect other services. 
So I'm thinking that separating services into different processes is the way to go.

In your case the owner of the connection is Express which lives in worker. 
Business logic also runs in worker. How do you restart just one service if they are hosted in one process?

In my understanding microservices are isolated one from another but I don't see how SocketCluster manages this isolation.

Please guide me.

**Comment by jrylan** [comment]
@vicneanschi I'm not sure how many microservices you're going to have, but if it's less than 15 or so, you could maybe get by with spawning a child instance in your worker? You would still need some sort of router in the worker to direct traffic to the correct microservice child process.

Another way to handle it is to just have one process that does nothing but run SocketCluster, and then keep all your microservices as their own independent processes which utilize the `ws` websocket module on NPM to connect each microservice to SC, just as if it were a web browser, from there the microservice could publish, subscribe to channels, anything you need it to do.

If you don't intend for end users to have the ability to publish via SC, then you could use a secret key or something for each message that one of the microservices publishes to SC, and if that key isn't present, then the message doesn't get published to the other listeners in the channel(s).

**Comment by vicneanschi** [comment]
@jrylan Thanks for your post. That's not a bad idea. I would expect microservices framework to provide multiprocess services support out of the box. Otherwise, I have to manage the lifecycle of the spawned processes.

Speaking of end users they need to have the ability to publish via SC. How would they interact with the service otherwise?

**Comment by jrylan** [comment]
@vicneanschi I meant that more as publish directly to the channel. I always opt for setting it up so that an incoming message from an end user must be vetted and screened by the app logic before it is broadcast out and "republished" to all listeners by SC.

**Comment by vicneanschi** [comment]
Alright I'll try to see what I cat get out of SC.
Thanks for fast replies.
