### ISSUE TITLE
Upgrade to uws 0.7.2

### ISSUE THREAD

**Issue by mirague** [SocketCluster/socketcluster#201]
This will add support for Windows:

https://github.com/uWebSockets/uWebSockets/releases

**Comment by jondubois** [comment]
@mirague done. If you upgrade the socketcluster-server dependency to v4.2.9, it will have the latest uWS installed.

**Comment by mirague** [comment]
Thanks for your swift support, as always! @jondubois

**Comment by alexhultman** [comment]
0.7.6 is the latest. Windows support is only for Node.js 6.3.0 (will crash on any other version). Any SSL usage will also crash.
