### ISSUE TITLE
Invalid password was supplied to the broker

### ISSUE THREAD

**Issue by deoqc** [SocketCluster/socketcluster#206]
Not sure why, but after I updated my npm modules [this](https://github.com/SocketCluster/sc-broker/blob/master/server.js#L187) error started to prevent socketcluster from running.

Tried to move back to earlier commits but without success, maybe some *breaking* changes and semver problem? (I keep all dependences in `save-exact=true`). 

---
edit:

I run 2 socketclusters locally: one for dev and one for test. The error only shows when I run both concurrently: `concurrently -k 'npm run socketcluster:test' 'npm run socketcluster:dev'`. Then `secretKeys` seems to get messed up: command secret key of dev is equal to broker secret key of test.

The error don't happen when run individually (but I used to run then `concurrently` w/o problems).

Note also that `dev` is working and `test` is not, when the `concurrently` command is run like above.

**Comment by jondubois** [comment]
@deoqc Running two instances side by side works for me.

- Both your dev and test instances use the same code base?
- Which version of sc-broker-cluster https://www.npmjs.com/package/sc-broker-cluster are you using? (anything 2.1.1 or higher should be fine) 
- Which version of sc-broker https://www.npmjs.com/package/sc-broker are you using? (2.2.0 or higher should be fine)

**Comment by jondubois** [comment]
@deoqc I checked with `concurrently`, it works for me.

**Comment by deoqc** [comment]
- Yes, both are equal except for env variables
- socketcluster v4.6.2 (or v5.0.1 just tested)
- sc-broker v2.2.0
- sc-broker-cluster v2.1.3
- concurrently v2.2.0
-node v5.8.0

It used to work just fine for me, and yesterday after 'npm install' it didn't (so I believe it were some update in the dependency sc-broker).

I printed the keys:
```
[0]    [Busy] Launching SocketCluster
[1]    [Busy] Launching SocketCluster
[0] (Top Level) Broker secretKey 432542019b5f9427f28c77571d37f22803dbef14e4c3af18810599f7e8d402da
[1] (Top Level) Broker secretKey 42fcfe6de8f708326449dc6a65f750a99f6fc63f8facc6114e221d054610e3ae
 [0]    >> Broker PID: 5601
[1]    >> Broker PID: 5602
[1] (Check) Command secretKey 432542019b5f9427f28c77571d37f22803dbef14e4c3af18810599f7e8d402da
[1] (Check) Broker secretKey 42fcfe6de8f708326449dc6a65f750a99f6fc63f8facc6114e221d054610e3ae
[1] (Check) Command secretKey 432542019b5f9427f28c77571d37f22803dbef14e4c3af18810599f7e8d402da
[1] (Check) Broker secretKey 42fcfe6de8f708326449dc6a65f750a99f6fc63f8facc6114e221d054610e3ae
[0] 1470321494617 - Origin: Worker (PID 5605)
[0]    [Error] Error: Invalid password was supplied to the broker
```

(Top level) refers to key [here](https://github.com/SocketCluster/sc-broker/blob/master/server.js#L127) and (Check) to keys [here](https://github.com/SocketCluster/sc-broker/blob/master/server.js#L184).

Strangely, the test [0] doesn't print the (Check) - which is in the line before `if/else` clause - but is the one throwing error.

**Comment by jondubois** [comment]
@deoqc if you create a brand new project from scratch using `socketcluster create my-new-project` and then run it with `concurrently` does it still have the problem? I have everything the same but it works.

What OS are you using?

**Comment by jondubois** [comment]
@deoqc Are you changing environment variables inside your code at runtime?

**Comment by deoqc** [comment]
I don't even need to use `concurrently` for the error to happen, if I start both command rapidly it already does.

I'm using OSX El Capitan v10.11.5.

I use [dotenv](https://www.npmjs.com/package/dotenv) to load env variables at the very top of my call (the 'server/env' call bellow). After it, I don't change anymore.

```Javascript
import 'server/env'
import { SocketCluster } from 'socketcluster'
import { cpus } from 'os'

const numCpus = cpus().length

new SocketCluster({
  workers: numCpus,
  brokers: 1,
  port: process.env.SERVER_PORT,
  appName: 'App',
  initController: __dirname + '/init.js',
  workerController: __dirname + '/worker.js',
  brokerController: __dirname + '/broker.js',
  socketChannelLimit: 1000,
  rebootWorkerOnCrash: true,
})
```

Well, feels like could be it due to async loading, right? Any clues on how to properly do it, or should I try to build a reproducible example?

**Comment by jondubois** [comment]
@deoqc I made an update to socketcluster - Now v5.0.2 - It fixes a separate issue with OSX (which caused issues when running multiple brokers in a single instance). Maybe it will also fix your issue? Let me know.

**Comment by deoqc** [comment]
Tried both, didn't work..

**Comment by jondubois** [comment]
@deoqc Try:
- Removing the appName from your options - Let SC generate it for you.
- If that doesn't work, make is so that the two instances have a different appName (maybe add random numbers at the end?)

**Comment by deoqc** [comment]
Thanks @jondubois, both solutions worked!

And thanks for the amazing working in socketcluster... I want to deepen my knowledge about it
