### ISSUE TITLE
Android Socketcluser Client Library

### ISSUE THREAD

**Issue by sacOO7** [SocketCluster/socketcluster#208]
Are you planning to write down sophisticated socketcluster client library in java which can be used in android as well ? I found socketcluster to be more useful and efficient than socket.io . If there are any future plans for making it more powerful and cross platform , I would like to contribute in it.

**Comment by MegaGM** [comment]
https://github.com/SocketCluster/socketcluster/issues/150

**Comment by chegewara** [comment]
Try this. Maybe its what you need.
https://github.com/chegewara/socketcluster-client-android

**Comment by sacOO7** [comment]
Yeah, I think it uses WebView internally .Still ,I want native REST based library like socket.io client library.

**Comment by chegewara** [comment]
It uses webview just to load javascript socketcluster client, which is used to communicate with server thru socket pub/sub messaging. Its not as sophisticated and clean as @abpopov client, but works good to me.

**Comment by sacOO7** [comment]
Ok , not a problem. I will try it .

**Comment by jondubois** [comment]
@sacOO7 I started writing up the protocol here: https://github.com/SocketCluster/socketcluster/blob/master/socketcluster-protocol.md

**Comment by ayZagen** [comment]
Great framework but we need clients at least in most used languages in mobile technologies such as swift and android.

**Comment by jondubois** [comment]
@ayZagen There is for Swift (iOS), Objective-C (iOS) and Java (Android) https://github.com/socketcluster/client-drivers#list-of-clients
