### ISSUE TITLE
`jsonwebtoken` dependency.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [SocketCluster/socketcluster#217]
Is the `jsonwebtoken` dependency still being used?  It looks like the only reference to it was taken out [in November](https://github.com/SocketCluster/socketcluster/commit/abfc44cd2c615c8a546fc228167857e5ff141727).

**Comment by jondubois** [comment]
@wtgtybhertgeghgtwtg Ah yep, this is now in the sc-auth module. Thanks.
