### ISSUE TITLE
Passport Token and Socket Cluster

### ISSUE THREAD

**Issue by CoveTechnologyAus** [SocketCluster/socketcluster#219]
Hi

I currently have a REST service being authenticated with Passport-jwt and would now like to move to adding real time capabilities with SocketCluster for some of the App.

I have gone through the basic tutorials and I think I understand how to authenticated with SocketCluster by emitting login. But how (or even can I) use the JWT token that the client already has from Passport.

Essentially what I am trying to achieve:
1. User logs into the App (POST to /session endpoint and receives Token from Passport).
2. User works with app in regular why (hitting REST endpoints/routing etc)
3. User now goes to component in App that has real-time capability (a feed for example with SocketCluster) but I don't want them to have to "log in" again, can I use the existing token they have in localstorage from Passport.? and if so, how do I have SocketCluster Server accept this token for it's authentication?

I would have the REST endpoints and SocketCluster server all sitting on the same Server (Express). [or is this a bad idea even?] so I am guessing it would have to be some sort of Middleware but I really cannot get my head around it.

Hopefully this all makes sense. I did see some posts from 2014 asking about similar issues (sort of), but I didn't get anything helpful from them and I think SocketCluster might have changed a lot since then.

PS. I guess on the client I can just send the token from localstorage with SocketCluster Client.

**Comment by jondubois** [comment]
@CoveTechnologyAus SC should be able to pick up and verify your JWT token automatically if it has the same `authKey` as the one which you used to sign the JWT token. Search for `authKey` here: http://socketcluster.io/#!/docs/api-socketcluster

SC client socket will automatically pick up the JWT token from localStorage and pass it to the server during the handshake phase. By default, the client will look for the key `socketCluster.authToken` inside localStorage to get the token.

You can specify a custom localStorage key using the `authTokenName` option when you create the client socket. See http://socketcluster.io/#!/docs/api-socketcluster-client

You can also provide a custom `authEngine` if you want to customize this further; you could change the default authEngine to load from a cookie if you like but this is a more advanced use case.

**Comment by jondubois** [comment]
If you provide your own authEngine to the client, it must be an object which implements the following functions:

- saveToken
- removeToken
- loadToken

The default authEngine is here: https://github.com/SocketCluster/socketcluster-client/blob/master/lib/auth.js

**Comment by CoveTechnologyAus** [comment]
@jondubois , thank you very much for the reply, that cleared things up heaps.
The only question I have is still with the server side, so with what you have explained here:
```SC should be able to pick up and verify your JWT token automatically if it has the same authKey as the one which you used to sign the JWT token.```

Does this mean I should just be able to pass the token along to the SocketCluster server without the need to emit the "login" message to the SocketCluster server. I am guessing I will already have a token on the client that matches the authkey on the server (providing both Passport and SocketCluster are using the same authkey)

I'm sorry if that is an obvious questions, if I have it right then I have been WAY overthinking it all and this is really much simpler and better than I originally thought.

**Comment by jondubois** [comment]
Check https://socketcluster.io/#!/docs/authentication and https://socketcluster.io/#!/docs/middleware-and-authorization
