### ISSUE TITLE
How to get access to query object that has been passed through socketCluster.connect(options) 

### ISSUE THREAD

**Issue by mkgn** [SocketCluster/socketcluster#220]
I use socketCluster.connect(options) from client side. In objects I can send some data using [query] property which has to be a key,value object.

I would like to send some data through this so that I can access them at the handshake.

I couldn't find a way to do that from the server.

**Comment by jondubois** [comment]
@mkgn Inside the MIDDLEWARE_HANDSHAKE middleware, the query string will be part of the URL `req.url` or on a socket, you can use `socket.request.url` you can use the native Node.js module `url.parse(req.url, true)`.
