### ISSUE TITLE
Is it required to close each channel after the user is disconnected?

### ISSUE THREAD

**Issue by ubaidseth** [SocketCluster/socketcluster#222]
Does it take up extra memory if I leave the channel open?

Here's an example of my code:

    socket.on('disconnect', function() {
      logger.info("Client disconnected", socket.id);
      socket.exchange.destroy(socket.id);

    });

But when I do this, whenever I refresh the page (as a client), it doesn't push new data to a different channel. It seems it's destroying ALL the channels.

**Comment by jondubois** [comment]
@ubaidseth I'm not sure what you're trying to do here. `socket.exchange.destroy()` doesn't accept any arguments - It's an undocumented function and its purpose is to destroy the entire pub/sub exchange (which will basically shut down pub/sub message brokering for the entire worker) - You shouldn't use this function - It's only for internal use. Be careful when using undocumented functions.

To answer your question, on the server-side, you don't have to cleanup channels - Channels will automatically get cleaned up and garbage collected once it no longer have any subscribers.

On the client side, if you want to completely remove a channel from memory, you can call `socket.destroyChannel(channelName)` - See http://socketcluster.io/#!/docs/api-scsocket-client

Note that channels use very little memory though so you generally don't need to destroy them unless your app has lots of dynamically-generated channel names which keep piling up.

**Comment by ubaidseth** [comment]
@jondubois Very nice. Thank you for the clear and concise answer.

I was trying to kill the channel from the server end whenever the client disconnects.

The channels were dynamically created - the name of the channel is the client's session ID. I was trying to privatize each client's interaction with the server as not to mix data on one global channel.

**Comment by jondubois** [comment]
@ubaidseth When a client disconnects, all its channels will be automatically unsubscribed (and cleaned up) on the server-side.
