### ISSUE TITLE
I can't emit MongoDB result objects server side

### ISSUE THREAD

**Issue by willypuzzle** [SocketCluster/socketcluster#223]
I noticed that from server side I can't publish or emit arrays. I think that this is a strong limitation.

**Comment by jondubois** [comment]
Are you using the functions correctly?

To emit (event 'arr'):
```
socket.emit('arr', ['This', 'is', 'an', 'array', 123, 456])
```

To publish (the 'arr' channel):
```
scServer.exchange.publish('arr', ['This', 'is', 'an', 'array', 123, 456])
```

**Comment by happilymarrieddad** [comment]
I just tested as well and it worked great

**Comment by willypuzzle** [comment]
Have you tried array of objects and/or objects that contains arrays of objects?

**Comment by jondubois** [comment]
@willypuzzle What are you emitting exactly?

**Comment by willypuzzle** [comment]
@jondubois I would emit mongoose find results of complex objects stored in MongoDB database.

**Comment by jondubois** [comment]
@willypuzzle How is it not working? Do you receive an events on the other side?
Do you use `socket.on('eventName', function (data) {/*...*/})`?

**Comment by jondubois** [comment]
Or you get nothing at all?

**Comment by jondubois** [comment]
Are you using a reserved event name? https://github.com/SocketCluster/socketcluster-client/blob/416982105e86494e4f6b12f0244b67b702618588/lib/scsocket.js#L56-L71

**Comment by willypuzzle** [comment]
@jondubois I don't receive event at all but If I "Objectify" the arrays all works fine. I'm using socketcluster-server 5.1.0.

**Comment by willypuzzle** [comment]
I upgraded to the latest version of server (5.1.1) but the problem persists

**Comment by jondubois** [comment]
Can you paste a simplified version of your code so that I can reproduce the problem it on my machine?

**Comment by jondubois** [comment]
Also, did you add any custom SC middleware? Check that you're not blocking anything inside your middleware.

**Comment by willypuzzle** [comment]
I have to correct myself, the event is emitted by the array I receive in client side is always empty.

This is an example:

```
var mongoose = require('mongoose');
var Promise = require('promise');

mongoose.Promise = Promise;

const modelName = 'chat';

var schema = new mongoose.Schema({
    attributes: {
        type: [mongoose.Schema.Types.Mixed],
        default: []
    },
    touched_by_an_operator: {
        type: Boolean,
        default: false
    },
    operators: {
        type: [mongoose.Schema.Types.Mixed],
        default: []
    },
    users: {
        type: [mongoose.Schema.Types.Mixed],
        default: []
    },
    ended: {
        type: mongoose.Schema.Types.Mixed,
        default: {
            value: false,
            reason: null
        }
    },
    created_at: Date,
    updated_at: Date
});

var Model = mongoose.model(modelName, schema);

/*You have to retrieve a correct socket instance that is a instance of SCSocket (server, worker)*/

socket.on('chat_list_request', function (data, res) {
    Model.find({ 'ended.value': false, touched_by_an_operator: false }).exec().then(function (chat) {
	socket.emit("chat_list", chats);
	res(null, 'Success');
    });
});
```

**Comment by jondubois** [comment]
@willypuzzle Are you sure you are emitting a raw object and not a function/class? Maybe Mongo returns a special Model instance (not a raw JSON-compatible object)?

**Comment by willypuzzle** [comment]
I discovered that the broadcast system (scServer.exchange.publish()) fails to convert ObjectId (_id of MongoDB) into string when build the json to send. 
Maybe the system is not able to deal with Date Object or ObjectId when emit the event. 
This because the objects got from MongoDb are not all string but there are Javascript Object too.
Maybe this is the reason I can't put a MongoDB object directly in the emit stream.

**Comment by willypuzzle** [comment]
I have found a workaround if I wrap the Mongodb results with 

`JSON.parse(JSON.stringify(results)) `

it works.

**Comment by willypuzzle** [comment]
I have found a workaround if I wrap the Mongodb results with 

`JSON.parse(JSON.stringify(results)) `

it works.

**Comment by jondubois** [comment]
@willypuzzle That's strange because SC essentially just calls JSON.stringify on the object, sends it over the wire and then passes the string to JSON.parse so this would use up extra CPU for no good reason.

Can you reproduce the issue without using MongoDB? Can you create a dummy hard-coded object or array that doesn't work?

**Comment by willypuzzle** [comment]
I can't reproduce it without MongoDB because the issue was on _id field. It fails in ObjectId objects. When I have a few of time I will post the complete stack error.

**Comment by jondubois** [comment]
@willypuzzle Ok, I made a change to the `sc-formatter` module which should make SC better at dealing with complex objects such as Mongoose model instances... Make sure you npm update the `sc-formatter` dependency to the latest version. You may also want to update the `socketcluster-client` to v 5.0.13.

**Comment by willypuzzle** [comment]
Now the situation is better, the result objects/array comes to the client side but the ObjectId fields are not correct. Instead of the normal value e.g. "57f2126f3f45ed18d9942ad4" it returns values as "0" or "1". The problem doesn't persist if I transform ObjectId (for example _id field) into string before sending.
I think the issue is in the conversion of ObjectId field into string before sending.

**Comment by jondubois** [comment]
@willypuzzle If you call `JSON.stringify` on the MongoDB model, how does the ObjectId get stringified? Does it also become "1" or "0"?

**Comment by willypuzzle** [comment]
@jondubois If I call JSON.stringify directly on the model results the ObjectId fields are correct string with the correct value e.g. "57f2126f3f45ed18d9942ad4"

**Comment by jondubois** [comment]
@willypuzzle I tested SC with the latest sc-formatter and sent a mongoose model to a client socket (I tried both publish and emit) and the _id field (of type ObjectID) got stringified correctly (in the format "546fa534f65f5d0200855501"). That's strange. Are you sure you have the latest sc-formatter `v2.0.2` dependency.

I cannot reproduce this issue. Do you have any SC middleware defined which might be messing with the _id field in the output?

**Comment by willypuzzle** [comment]
@jondubois I had tried to catch the error in the middleware but I haven't found anything. However I'll check very carefully and I will let you know.

**Comment by willypuzzle** [comment]
@jondubois I have tested in other parts of my code and, as you said, it works correctly. So I think it is a issue of my code. I'm sorry for the wasting of time.

**Comment by jondubois** [comment]
@willypuzzle No time was wasted. I made a small improvement to sc-formatter as a result of this discussion so it was useful... Even if it ends up not being directly related.

Sometimes it's hard to tell where the root of problem is... Feel free to reopen this issue later if it turns out to be SC-related.

**Comment by nguyenhaian** [comment]
Try to call .lean() before call .exec() to get json object. Otherwise you get a Mongoose Object which can call some special function.

```
socket.on('chat_list_request', function (data, res) {
    Model.find({ 'ended.value': false, touched_by_an_operator: false }).lean().exec().then(function (chats) {
    socket.emit("chat_list", chats);
    res(null, 'Success');
    });
});
```
