### ISSUE TITLE
Got errors when run in ssl mode

### ISSUE THREAD

**Issue by hustcer** [SocketCluster/socketcluster#224]
Got errors when run in ssl mode, however, when run in non ssl mode it works fine:
```
1474625965853 - Origin: Worker (PID 40324)
   [Error] TypeError: SCSocket.prototype.stringify is not a function
    at EventEmitter.Client._handleExchangeMessage (/Users/hustcer/github/lark/node_modules/sc-broker-cluster/index.js:645:54)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.emit (/Users/hustcer/github/lark/node_modules/sc-domain/index.js:12:31)
    at EventEmitter.handleMessage (/Users/hustcer/github/lark/node_modules/sc-broker-cluster/clientcluster.js:10:15)
    at emitTwo (events.js:111:20)
    at EventEmitter.emit (events.js:191:7)
    at EventEmitter.emit (/Users/hustcer/github/lark/node_modules/sc-domain/index.js:12:31)
    at Socket.<anonymous> (/Users/hustcer/github/lark/node_modules/sc-broker/index.js:233:12)
    at emitOne (events.js:96:13)
1474625965860 - Worker 0 exited - Exit code: 1
```
And the error causing worker to crash/respawn.

**Comment by hustcer** [comment]
The sc-broker-cluster/index.js:645 line: 
```javascript
emitOptions.stringifiedData = SCSocket.prototype.stringify({
      event: '#publish',
      data: packet
    });
```
But there is no `stringify` definition in `socketcluster-server/scsocket.js`

**Comment by happilymarrieddad** [comment]
this is the same error I've been getting on our staging server... I updated from 5.0.10 to 5.0.15 is all I've done.

**Comment by jondubois** [comment]
@hustcer @happilymarrieddad Sorry. My fault. I renamed a function to encode instead of stringify and forgot to update it in sc-broker-cluster.

If you npm update sc-broker-cluster to version 2.1.5 that should fix it.

**Comment by happilymarrieddad** [comment]
@jondubois hey man now I'm getting this error

![selection_157](https://cloud.githubusercontent.com/assets/6416323/18797821/06395bc8-818d-11e6-8630-9bf972ea91fa.png)

**Comment by happilymarrieddad** [comment]
Two atoms are talking and one atom says, "Hey man, I think I lost an electron". The other atom says, "Are you positive?"...

**Comment by jondubois** [comment]
@happilymarrieddad Arghh, yep I'm on it now...

**Comment by happilymarrieddad** [comment]
That's it.. I quit. I'm rewriting everything in Perl...

**Comment by happilymarrieddad** [comment]
There are two guys drinking in the two towers. One guy says hey man check this out. He goes over to the window, opens it up, jumps out, fly's around, and then comes back inside unharmed. The other guys is blown away. He says, "How did you do it?" The first guy says, "The wind between the towers will hold you up." The other guy says, "I'm going to try it." He goes over to the window, opens it up, jumps out, and then falls and dies." The bartender looks at the first guy and says, "Superman, you're a jerk when you're drunk."

**Comment by jondubois** [comment]
@happilymarrieddad ;p

Ok, I fixed it for real this time (and tested) you have to update socketcluster to v5.0.16 and make sure you have all the latest dependencies including sc-broker-cluster v2.1.7

**Comment by hustcer** [comment]
sc-broker-cluster@2.1.7 works, I think socketcluster should be updated too, because it depends on sc-broker-cluster

**Comment by happilymarrieddad** [comment]
is it possible to remove those few bad versions from NPM?

**Comment by jondubois** [comment]
@happilymarrieddad I don't think npm allows this for security reasons.

**Comment by happilymarrieddad** [comment]
that makes sense. Thanks!

**Comment by jondubois** [comment]
I just have to be more careful. Maybe I should wait till the weekend to publish risky changes. Even well established projects will occasionally release a buggy version.

I really should write more tests and think of adding CI to prevent these kinds of issues.

**Comment by happilymarrieddad** [comment]
Yea, how dare you create the best framework that I've ever encountered and make one mistake.. HOW DARE YOU JOHN! lol no worries man. We have a 3 step deployment process and nothing should ever get to production. Thanks!!!!!!

**Comment by happilymarrieddad** [comment]
I can confirm it is working great! Thanks!

**Comment by jondubois** [comment]
@happilymarrieddad Haha. Let me assure you that the specific individual(s) responsible for this issue have been swiftly reprimanded. It won't happen again.

**Comment by happilymarrieddad** [comment]
@jondubois hey man I think we can close this one.
