### ISSUE TITLE
single process mode?

### ISSUE THREAD

**Issue by wmertens** [SocketCluster/socketcluster#226]
I know of the `--inspect-workers` flag, but for debugging it can sometimes be even simpeler to have everything running in one process.
One really nice use case would be to use hot module reloading on the server side, so that you can change handlers live without having to restart workers. (https://github.com/ericclemmons/webpack-hot-server-example)

So, basically, if it would be easy for you to have a single-process mode, I would be really happy :)

**Comment by jondubois** [comment]
@wmertens There is, you can run the server directly https://github.com/socketcluster/socketcluster-server - The client-side API is 100% the same. On the server side the API is also the same except that there is no `server.exchange` object. You just have to add a bit of extra code to attach the server to a Node.js http server object.

**Comment by wmertens** [comment]
Oh cool! Thanks :)

**Comment by jondubois** [comment]
In theory, assuming that you don't use the `scServer.exchange` object; you could run socketcluster-server for development and use the full socketcluster framework (with multiple processes) in production only.

**Comment by wmertens** [comment]
@jondubois This is no longer possible with v9, what is the recommended way now? I learned a lot about hot reload so I can help out with that part…
