### ISSUE TITLE
SC auth error

### ISSUE THREAD

**Issue by ivopc** [SocketCluster/socketcluster#231]
when I try to send an authentication data (in the manually MIDDLEWARE_HANDSHAKE middleware) which is not a JSON the SC throw me this error:

```
    var Socket = socketCluster.connect({
        query: new NotAJsonData
    });
```

```
/nodejs/node_modules/socketcluster/index.js:384
  if (warning.stack == null) {
             ^

TypeError: Cannot read property 'stack' of null
    at EventEmitter.SocketCluster.warningHandler (/nodejs/node_modules/socketcluster/index.js:384:14)
    at EventEmitter.SocketCluster._workerWarningHandler (/nodejs/node_modules/socketcluster/index.js:459:8)
    at ChildProcess.workerHandler (/nodejs/node_modules/socketcluster/index.js:574:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at ChildProcess.EventEmitter.emit (/nodejs/node_modules/sc-domain/index.js:12:31)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I think there are a lot of a data where is not sanitized in server inputs, it is very potentially dangerous...

**Comment by ivopc** [comment]
Here are the most "correct" thing to deal with this error:

```
SocketCluster.prototype.warningHandler = function (warning, origin) {

  warning = warning || new UnknownError(warning);

  warning.stack = warning.stack || warning.message;

  warning.origin = origin;
  warning.time = Date.now();

  this.emit(this.EVENT_WARNING, warning);

  if (this.options.logLevel > 1) {
    this._logObject(warning, 'Warning');
  }
};
```

I do not understand how exactly warning object is passed.

**Comment by jondubois** [comment]
@ivopc I tried passing a number and a ArrayBuffer as `query` instead of NotAJsonData but could not reproduce. What version of SC are you using? What are you passing as `NotAJsonData`?

**Comment by jondubois** [comment]
I've made a change in SC v5.0.18 which makes it handle bad errors/warnings such as `null` so that should stop workers crashing. It's still strange because errors/warnings should never be null... So I'm not sure what's happening there. Make sure that your `sc-errors` dependency is updated to v 1.0.6.

**Comment by jondubois** [comment]
Let me know how I can reproduce the error before though (what should I make `NotAJsonData`)?

**Comment by ivopc** [comment]
the data is just a:
```
Object.create({
    "any": "data"
})
```

and my version is 5.0.16

**Comment by jondubois** [comment]
@ivopc Maybe there isn't something else happening in your code which is causing this issue? I can't reproduce this.

**Comment by ivopc** [comment]
I really don't know what is causing it, my code is like any other. I'll update my SC version and'll give you the feedback.

**Comment by jondubois** [comment]
The lack of follow-up seems to indicate that it all worked out in the end?
