### ISSUE TITLE
Missing licenses in sub repositories

### ISSUE THREAD

**Issue by carlmathisen** [SocketCluster/socketcluster#232]
Hi,

I'm currently creating an overview of all licenses brought in by npm dependencies in a project, and while doing so I found that several of the sub repositories in the SocketCluster organisation are lacking licence info.

For instance sc-broker-cluster: https://github.com/SocketCluster/sc-broker-cluster

Can I assume all these repositories also have an MIT license, such as the main project repo? I can gladly help adding PRs to the repos with an updated README.

PS, for anyone out there interested, I found https://github.com/marcello3d/node-licensecheck to be the best one out there. If you are using open-source tools in your company, it costs very little to get an overview of your licences and stay safe.

**Comment by jondubois** [comment]
@carlmathisen Yep, the MIT license in the main SocketCluster repo covers all sc-related dependencies. Feel free to make PRs.

**Comment by jondubois** [comment]
It's all MIT.
