### ISSUE TITLE
Update documentation on option data subscription

### ISSUE THREAD

**Issue by deoqc** [SocketCluster/socketcluster#235]
Just a remainder to update documentation as is explained [here](https://github.com/SocketCluster/socketcluster/issues/167).

*ps: feel free to close if don't fell like doing it. =]*

**Comment by jondubois** [comment]
@deoqc Thanks. I've updated the docs http://socketcluster.io/#!/docs/api-scsocket-client and http://socketcluster.io/#!/docs/api-scchannel-client - See the `subscribe` method.

**Comment by deoqc** [comment]
Thx. Maybe should also update the middleware?

Also I think the Publish [middlewares](http://socketcluster.io/#!/docs/middleware-and-authorization) should have the data option (maybe `req.subscribeOptions`) available to them. 

A use case would be verifying credentials for publish in based on the data, or filtering out messages in publish out.

**Comment by jondubois** [comment]
@deoqc That is not practical to implement - It won't scale across multiple workers - There is no guarantee that the publish action will be processed by the same worker (or server) than the one which processed the subscribe action. You can use the data in the published message itself to filter out messages. And you can use `req.socket.authToken` to verify credentials in any middleware.

**Comment by deoqc** [comment]
The use case I wanted was to use `subscribe('some_channel', { data: {id: 'my_id'}})` instead of `subscribe('some_channel-my_id')`. So I needed to filter out each message in server to send only relevant / authorized data. 

But I think this would be very inefficient against the first option. It would actually try to mimic the first option (and its middlewares) with a clearer syntax.

I don't think it is actually worth the hassle. 

Thx for the great support.
