### ISSUE TITLE
Minimum supported `node` version.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [SocketCluster/socketcluster#237]
What is the minimum supported version of `node` for `socketcluster`?

**Comment by happilymarrieddad** [comment]
We have one of our servers running everything except uws on 0.12.

**Comment by jondubois** [comment]
@wtgtybhertgeghgtwtg In the latest versions of SC, you can use Node.js `v0.12.x` if you comment out some of the default optional code in server.js and broker.js.

Ideally we recommend Node.js `v4.x.x`.

**Comment by wtgtybhertgeghgtwtg** [comment]
> In the latest versions of SC, you can use Node.js v0.12.x if you comment out some of the default optional code in server.js and broker.js.

Will this be documented?

**Comment by jondubois** [comment]
Hopefully the passing of time has resolved this issue for us.
