### ISSUE TITLE
Is there any experience using ios and android? 

### ISSUE THREAD

**Issue by artooroff** [SocketCluster/socketcluster#238]
We try to implement with this doc: https://github.com/SocketCluster/socketcluster-client-ios
And we get errors. Who can help us with this implementation?

**Comment by jondubois** [comment]
@artooroff If you're having problems with that client, there is another native client: https://github.com/socketcluster/client-drivers#list-of-clients

**Comment by artooroff** [comment]
@jondubois  can You help us to implement?  Here are skypes : djortoor,  gevorg19965

**Comment by jondubois** [comment]
@sacOO7 Is in charge of all the native client stuff. See https://github.com/sacOO7/socketcluster-client-java and https://github.com/sacOO7/socketcluster-client-swift
