### ISSUE TITLE
Spin off CLI.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [SocketCluster/socketcluster#243]
`socketcluster` provides a CLI with one command, `create-app`.  As the name suggests, it creates a `socketcluster` app.  Could this be made into its own package, call it something like [create-socketcluster-app](https://github.com/facebookincubator/create-react-app)?  Dropping the `inquirer` dependency from the `socketcluster` package would nearly halve the dependency tree.

**Comment by jondubois** [comment]
@wtgtybhertgeghgtwtg It looks like a lot of those dependencies are pretty lightweight, so `inquirer` downloads pretty quickly but I don't like the way they've specified their dependencies with `^` in front of the version numbers https://github.com/SBoudrias/Inquirer.js/blob/master/package.json#L22-L56

I also think they've used way too many dependencies for such a simple tool.
I've raised an issue on their repo about this https://github.com/SBoudrias/Inquirer.js/issues/460

I think we can consider creating a new `create-socketcluster` or similar npm module... The other possibility is to just find something more lightweight than inquirer.

**Comment by happilymarrieddad** [comment]
I was also thinking it might be nice to add broker and state manager to the cli as well so you can easily spin up a clustered system. What do you think about that @jondubois ?

**Comment by jondubois** [comment]
I think that this project already has a lot of different repos/packages to manage so I'm happy to keep it as it for now.
