### ISSUE TITLE
WebRTC support

### ISSUE THREAD

**Issue by ivopc** [SocketCluster/socketcluster#244]
Planning to write a native webrtc support with socketcluster front-end and authentication for back-end. Why? To do a real-time p2p module. 
Webcam, Vo-IP and REALLY real-time games support (all of "them" are not viable for TPC sockets).
Any suggestion?

**Comment by ivopc** [comment]
Planning to write a native webrtc client2server too, maybe with c++ libs implemetations. This will be a necessity of my project and I want to share with devs.

**Comment by jondubois** [comment]
@ivopc That sounds great. Yes, I think this would be perfect as a module (or wrapper?) for SC client.

I guess you could pass a client SCSocket object to it as an argument when creating a new peer-to-peer connection and you could save the username/user id inside an SC token somehow.

**Comment by ivopc** [comment]
@jondubois Thanks for advice, I'll start the project maybe in the next year.

**Comment by zalmoxisus** [comment]
@ivopc you could also take a look at [`janus-gateway`](https://github.com/meetecho/janus-gateway), which allows to write custom plugins. Specifically [its websockets plugin](https://github.com/meetecho/janus-gateway/blob/master/transports/janus_websockets.c) and [text chat pluggin](https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_textroom.c) could be rewritten to play nice with socketcluster.
