### ISSUE TITLE
[Q] Trying to build a mental model of SocketCluster and where/how to use my domain logic

### ISSUE THREAD

**Issue by jsynowiec** [SocketCluster/socketcluster#245]
Maybe this is silly but I'm reading through the SocketCluster documentation and source code of the `sc-*` dependancies trying to build a mental model of SocketCluster. So far I think that I understand how and why each of those packages is used.

Right now I have a running SC and some domain logic in separate modules. Now I want to use those modules with SC to authenticate clients, keep track of their permissions (allow to pub/sub a channel), etc. Also, one of the primary functions is to use the SC server to rebroadcast (forward) some messages from internal MQ to appropriate channels.

The problem is that I'm not sure where I should "put my code". The most obvious place is the Worker, but:

 1. If I'll add a middleware using `worker.wsServer.addMiddleware` and start 2 or more workers, how many middlewares are registered and run when event is triggered?
 2. If I'll subscribe to my MQ in the Worker and start 2 or more workers, I'm dealing with duplicated messages (MQ fanout). *Maybe Worker is not the right place for such code?*
 3. If I'll subscribe to socket events using `worker.wsServer.on` and start 2 or more workers, does the Broker bind each client with one specific worker so the callback is called only once?

I'm also looking for a way to spawn specialised sub-workers from a Worker - don't like the sphagetti code of a single worker-file. Is there any *official* way to support this or do I have to use my own spawning-managing-signalling?

**Comment by jondubois** [comment]
1. If you have 2 workers, it will register 2 middleware functions in total; 1 middleware function in each worker. Each worker is a separate process and doesn't share anything with each other (not even variables) - So think of them as being completely isolated ([embarassingly parallel](https://en.wikipedia.org/wiki/Embarrassingly_parallel)). I think the best way to understand how it works is to play with it (I.e. use `console.log()` and watch how messages pass through the middleware).
2. The worker is a good place to put your MQ consumers; it's not the absolute most optimal solution but it's simple and it scales well (linearly) - You consume messages from your workers and when you get a new message, from your external MQ, you just do `worker.exchange.publish('myChannelName', ...)` (that's it; the brokers will figure out how to deliver them to the correct workers and users). To avoid duplication of messages from your MQ, you can use a hash function to hash topic names into a numeric index and use this to decide which worker should handle which topics (or which subset of messages) - You can get the total number of workers from SC using `worker.options.workers`. Also each worker has an `id` which you can get using `worker.id`. Note that the hash function can work however you like - It doesn't matter which worker ends up consuming which topics so long as it's approximately even between all workers - The  `worker.exchange.publish('myChannelName', ...)` will figure out how to get it to the right clients.
3. In this case, each client will be bound to one of the workers; SC uses the Node.js cluster module which will do the round-robin load balancing which will pass the connection socket to one of the workers. Once a client is connected, it will stay connected to that worker for the life of the connection. If the connection is lost and re-established, it's possible that the user will end up on a different worker than the first time. Storing session data inside a JWT token using `socket.setAuthToken(data)` is a good way to keep track of workers across multiple workers in the event of lost connections. Storing the username in the token is the most common pattern but you can store other stuff as well (don't store passwords though).

You can require custom Node.js modules using `var myModule = require('./someModule.js')` inside `worker.js` so you can spread out your logic over multiple files. You can look at the worker controller for this sample app for ideas: https://github.com/SocketCluster/sc-sample-inventory/blob/master/worker.js
^ I could probably have moved even more code to a separate file...

Spawning other processes from worker.js is fine but it can make some things tedious (I guess it depends on your use case).

**Comment by jondubois** [comment]
Note that in the latest version of SC, you can use SC's default hashing function by requiring it with `hash = require('sc-hasher').hash`.

The `hash` function is in the form `hash(key, modulo)` where key is a string (e.g. a channel name or MQ topic name) and modulo is the number of available targets.

If it cannot find the 'sc-hasher' module automatically, you may need to `npm cache clean` and reinstall socketcluster - It should be bundled with SC.

**Comment by jsynowiec** [comment]
Thank you for the explanation. Those were the missing peaces that I needed. One more thing - if, for some reason, a worker crashes and is restarted, does it get the same id or a new one? Currently I'm using only the leader worker as a MQ forwarder and I'm wondering if I can somehow loose the leader? I know that this is not an optimal solution due to lack of scaling but there is currently only one queue (topic) to rebroadcast.

> Storing session data inside a JWT token using 

Yes, this is a common pattern but I'm dealing with a lot more state information. After reading documentation, issues and source code I can see that I have to implement some sort of state-syncing between workers myself, right?

> You can require custom Node.js modules using var myModule = require('./someModule.js') inside worker.js so you can spread out your logic over multiple files.

Thanks, I know this. My case is a bit different than just splitting the code.

**Comment by jscheel** [comment]
You can sync state between your workers by using the exchange, I believe.

**Comment by jondubois** [comment]
@jsynowiec Well technically if a worker dies, a new worker will take its place and that worker will take the dead worker's ID... So I guess the answer to your question is yes - The IDs are reused - They are in fact indexes; the first worker is always id 0, second worker is id 1, etc...
The worker object has an `isLeader` property (boolean) which tells you if the current worker is the leader (worker with ID 0 will always be the leader).
If you have just one queue and throughput is reasonable, then it's fine to make the leader always handle it.

You don't have to sync state between workers; in fact I would recommend that you don't unless you absolutely have to. Whenever you try to sync data between all workers, you automatically reduce scalability because there is only so much data that you can share around before workers get overloaded - The more workers you add, the more CPU and memory will be spent on synchronizing them; it's just not worth it.

To make an effective distributed system, you have to accept that not all workers need to have all the information at any given time (it's just not possible at scale). Data that needs to be accessed globally should be put in an external database and each worker should load what it needs and only when it needs it.
