### ISSUE TITLE
Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system

### ISSUE THREAD

**Issue by iMoses** [SocketCluster/socketcluster#246]
```
[Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
```
I can't seem to get SocketCluster to work, I always get the above error message, even after I changed `wsEngine` to `ws`.
I tried it on Node 6 and 7, Ubuntu 16.04.
I couldn't find anymore information about this issue online, can you please direct me on how to figure out what is causing this issue?

Thanks

**Comment by jondubois** [comment]
@iMoses Is this happening when you do `npm install`?
It works fine on my Ubuntu 15.10 machine with Node 6.4.0. It sounds like it doesn't like your compiler for some reason... @alexhultman do you know what the issue could be?

Worst case, you can try running SC inside Docker (if you have Docker installed)... See https://blog.baasil.io/framework-in-a-container-6105d3275d61#.nrqmc559j

**Comment by iMoses** [comment]
No, `npm install` goes smoothly.
I get this message on a loop when trying to run a worker, it keeps crashing.

What information can I provide that will assist?
I need to get it working as part of an electron application, so docker is not really an option.

**Comment by jondubois** [comment]
Alex said that it can happen if you have an unusual setup like maybe 32-bit machine instead of 64-bit or maybe you have an old compiler - Or something happened to it... I'm trying to find a workaround now.

**Comment by jondubois** [comment]
It's weird that you can't just use `ws`.

**Comment by jondubois** [comment]
@iMoses When I delete the `uws` module and set the `wsEngine` to `ws` (http://socketcluster.io/#!/docs/api-socketcluster), it still works for me - Maybe try deleting `uws` from node_modules directory.

**Comment by iMoses** [comment]
64-bit, on two different PCs with Ubuntu 16.04
Both were bought in the last 18 months, both are strong PCs

It seems that the worker crashes just by trying to import uws
```
1479419902894 - Origin: Worker (PID 5931)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at e (/home/imoses/repos/tools_client/app/node_modules/uws/uws.js:25:19)
    at Object.<anonymous> (/home/imoses/repos/tools_client/app/node_modules/uws/uws.js:29:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at EventEmitter.SCServer (/home/imoses/repos/tools_client/app/node_modules/socketcluster-server/scserver.js:83:18)
1479419902896 - Worker 0 exited - Exit code: 1
1479419903031 - Origin: Worker (PID 5936)
   [Error] Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at e (/home/imoses/repos/tools_client/app/node_modules/uws/uws.js:25:19)
    at Object.<anonymous> (/home/imoses/repos/tools_client/app/node_modules/uws/uws.js:29:3)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at EventEmitter.SCServer (/home/imoses/repos/tools_client/app/node_modules/socketcluster-server/scserver.js:83:18)
1479419903033 - Worker 0 exited - Exit code: 1
```
This goes on and on and on...

**Comment by iMoses** [comment]
I tried deleting node_modules several times already.. no luck

**Comment by jondubois** [comment]
Did you try doing `npm cache clean` before reinstalling?

**Comment by jondubois** [comment]
@iMoses What is your `uname -a`?

**Comment by iMoses** [comment]
`Linux imoses-pc 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

I haven't tried `npm cache clean` until now, it does seem to have changed something.
I think I have a bigger bug here that may not belong to you.
For some reason, SocketCluster still ignores my `wsEngine: 'ws'` but it does seem to work:
```
   [Busy] Launching SocketCluster
   >> Worker PID: 8426
   [Active] SocketCluster started
            Version: 5.0.24
            Environment: dev
            WebSocket engine: uws
            Port: 8000
            Master PID: 8407
            Worker count: 1
            Broker count: 1
```
But when I try to run it as part of an electron application I still get the same error messages.

**Comment by jondubois** [comment]
Did you use `npm link` to link SC into your project?

**Comment by iMoses** [comment]
No, it was installed as a regular dependency.

**Comment by iMoses** [comment]
The part about `wsEngine` was my bad, I was indeed loading configuration from the wrong place.

Thanks a lot for you help

**Comment by CoolHandLuke88** [comment]
I ran into this exact issue.
I wanted to leave this here for anyone else that may run into this issue with docker and `uws` installation.

Hope you guys don't mind I drop this here.

In Dockerfile
*********************************
FROM node:8.9-alpine

RUN apk add --update \
    libc6-compat

*********************************
Needed `libc6-compact`

This should resolve the issue seen below.

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

**Comment by seclace** [comment]
As a workaround I run `cd node_modules/uws` and `node-gyp rebuild` commands.
(This module is used by socket cluster server in my react-native project). 
Consider that your `python` binary has version is `> 2.5` and `< 3.0.0`, `node-gyp` uses `python` for it.

Command | Value
------------ | -------------
uname -a | Darwin `here's my name` 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
node -v | v8.9.4
npm -v | 5.6.0
python --version | Python 2.7.10

**Comment by cjmling** [comment]
Had this same problem. And I got it solved by

Delete `node_modules` folder then `npm install` which download everything again **didn't solve**
Delete `node_modules\uws` folder then `npm install` which only re download `uws` **solved**

**Comment by brunolemos** [comment]
I was able to fix this on a mac by doing:

```shell
cd node_modules/uws
npm install
```

**Comment by ghoshabhi** [comment]
@cjmling's solution works!

**Comment by dotbloup** [comment]
Using node 10, npm 5.6 and python 2.7.14, I have tried from cjmling but there is a built error. "make" failed during built of uws. in node_modules/uws/build_log.txt
Does it mean the issue is related to the uws package?

```
make: *** [Release/obj.target/uws/src/addon.o] Error 1
make: Leaving directory `/root/seoserverdev2/node_modules/uws/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Linux 3.10.0-514.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/seoserverdev2/node_modules/uws
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
```

The file is really long so it is attached
[build_log.txt](https://github.com/SocketCluster/socketcluster/files/1982439/build_log.txt)

**Comment by boogerlad** [comment]
had the same problem

**Comment by klren0312** [comment]
I don't use the alpine ,fix it

**Comment by hiepxanh** [comment]
still cannot fix

**Comment by dotbloup** [comment]
Here is what I did as a workaround to fix the issue, I added SOCKETCLUSTER_WS_ENGINE='ws' to the .env file in the main root path.
So, rather than using uws, i use ws. I also discovered that ws was maintained by many more people than uws.

**Comment by cryptoking117** [comment]
tried all of the above no luck

**Comment by dotbloup** [comment]
@cryptoking117 i have updated my answer.

**Comment by sp-suresh** [comment]
In my case installing latest `nodejs` and `npm` on Ubuntu with PPA, solved this problem.

**Earlier version**

    node - v6.14.3
    npm - 3.10.10


**Latest version** which solved the problem-

    node - v10.6.0
    npm - 6.1.0

Refer - [How to Install Latest Node.js and NPM on Ubuntu with PPA][1]


  [1]: https://tecadmin.net/install-latest-nodejs-npm-on-ubuntu/

**Comment by pbassut** [comment]
For me the program was node 10.
When downgrading to node 9 it worked.
`nvm use 9`
`rm -rf node_modules/`
`npm install`

**Comment by vickylance** [comment]
> For me the program was node 10.
> When downgrading to node 9 it worked.
> `nvm use 9`
> `rm -rf node_modules/`
> `npm install`

I downgraded to node 8 and it worked thanks 👍

**Comment by nicubarbaros** [comment]
@pbassut thank you

**Comment by paxperscientiam** [comment]
Thanks @vickylance , I downgraded to 9 and that worked for me too.

**Comment by stephben** [comment]
uws will never ever work with nodejs10.  That is because uws does not support openssl 1.1.1.
That is the reason uws works when downgrading to node 8 (openssl 1.0.2).
Since the author has pulled his source out of nodejs repository I doubt there will ever be any support.
