### ISSUE TITLE
length limit for channel names?

### ISSUE THREAD

**Issue by naelt** [SocketCluster/socketcluster#248]
"socketcluster": "5.1.0"

When the length of my channel name is bigger than 7, `broker.publish(channel, message)` not work, resp `sCSocket.exchange.subscribe(ch).watch(function (data) {})`. Is there a length limit for channel names? Not found about this in the docs. There are some other restrictions for channel names?

Many thanks.

**Comment by jondubois** [comment]
@naelt No, there is no limit. How many brokers do you have? Note that you should avoid putting any code insider `broker.js` generally and publish using `scSocket.exchange.publish(channel, message)`.

If you have two brokers (for example), then each broker will only know about half of all channels which exist in your system. So if you call `broker.publish('somechannel', data)` on a broker but the `somechannel` channel is handled by a different broker (not the current one), then it will do nothing.

The code inside `broker.js` will be run for each of your brokers. You can use `broker.id` to check which broker your code is running on.

If you really want to run code inside `broker.js`, you might want to get sc-hasher https://www.npmjs.com/package/sc-hasher - This is the hashing algorithm which SC uses to distribute channel names between different brokers. So, inside broker.js can add logic such as (example):

```
var scHasher = require('sc-hasher');
var targetBrokerId = scHasher.hash(channelName, broker.options.brokers);
if (targetBrokerId == broker.id) {
  // Here we know that this channel belongs to this broker, so we can publish from here.
}
```

**Comment by naelt** [comment]
Thank you so much, now i understand my problem and solve it :)

SC is just awesome 👍

**Comment by happilymarrieddad** [comment]
What is the recommended number of brokers... for example if I have 2 16 core machines running together in a cluster how many brokers should each one have? How many brokers in the scc-broker and how many in scc-state?

**Comment by jondubois** [comment]
@happilymarrieddad It depends on how many pub/sub messages you send - If it represents a large part of your workload (like each user is sending one message every second at least), then a 50/50 ratio of workers to brokers is safest. So on a 16 core machine, you could have 8 workers and 8 brokers. But often, I found that you can have fewer brokers than workers. You'd have to try it out to see - If your broker processes are maxed out on CPU, then it means you need more.

You can have 16 workers and 16 brokers (that way you don't have to think about the ratio) but you tend to lose efficiency when you have brokers and workers sharing the same CPU cores.

**Comment by happilymarrieddad** [comment]
What about if you switch from redis to SCC?

**Comment by jondubois** [comment]
@happilymarrieddad In new versions of SCC, there is now an option to customise the connection pool size so it shouldn't matter as much how many workers/brokers there are. Increasing the `clusterClientPoolSize` (https://github.com/SocketCluster/socketcluster/blob/master/sample/server.js#L38) to be greater than the number processes per node should help even out distribution across all processes in the scc-broker instances.
