### ISSUE TITLE
No decent Android client library

### ISSUE THREAD

**Issue by heiba** [SocketCluster/socketcluster#249]
Hello @jondubois ,

First of all, well done and a big bravo on developing the amazing SocketCluster websocket server.

I switched from Socket.io to SocketCluster and managed to get SCC working using Rancher and Kubernetes. I now have a fully functional websocket server and tested web client works correctly.

Now I need to develop an Android client, but your list [https://github.com/SocketCluster/client-drivers](https://github.com/SocketCluster/client-drivers) doesn't have any decent Android client.

I tried both android libraries in your list. Can't even get it to connect, let alone very difficult and undocumented libraries.

The one you developed [https://github.com/SocketCluster/socketcluster-client-android](https://github.com/SocketCluster/socketcluster-client-android) is not native and uses WebViews so that's not recommended at all. Also, you have discontinued it, so I had to avoid it.

This is making me rethink my decision to move to SocketCluster. A well-developed Android client is critical for me.

Any plans to develop an official SocketCluster native Android client ?

What can I do in the mean time ?

**Comment by jondubois** [comment]
@heiba Did you try https://github.com/sacOO7/socketcluster-client-java? It's the latest one from the list. Maybe you can have a chat with @sacOO7 ([https://gitter.im/sacOO7](https://gitter.im/sacOO7)) - I believe he is currently refining it.

**Comment by heiba** [comment]
Yes I have tried it and didn't find it that easy to use. Will give it another shot. But seriously, consider developing an official android client for socketcluster.

**Comment by jondubois** [comment]
@heiba - @sacOO7 has built (and is building) a number of clients for SC, so I'll probably be working with him more closely soon. It's possible that it might become the official client down the track. Feedback is welcome - Feel free to raise an issue on the client's repo.

**Comment by jondubois** [comment]
@heiba Also, a lot of people use the official JavaScript client with React Native - So that may be an option worth considering as well.

**Comment by heiba** [comment]
I am currently trying hard yet again with [https://github.com/sacOO7/socketcluster-client-java](https://github.com/sacOO7/socketcluster-client-java)

I keep getting ERROR 400 "Reason Phrase = URL not supported"

I've raised the issue in the client repo, here's the link: https://github.com/sacOO7/socketcluster-client-java/issues/2

Thanks for the attention and support

**Comment by jondubois** [comment]
@heiba It takes a while to perfect things. It's been a while so hopefully it's better now :)
