### ISSUE TITLE
Save history of messages

### ISSUE THREAD

**Issue by ranhsd** [SocketCluster/socketcluster#252]
Hi, 
i am developing a mobile app which require some real time capabilities. 
One of the features of the app is to allow users to chat with each other in realtime and since my server side is 100% NodeJS i really want that also my chat server will be NodeJS based. 

In my app all the messages which are sent by users should be stored in the database in order to provide a "chat history" so all the messages that were sent/received from/to will be stored in the DB.
Im my current solution is store all the messages in MongoDB and i really want to keep them there because it's easy to scale it and also it provide a very powerful query mechanism (find, paging, sorting, etc.) 

My question is: what is the best practice for integrating it with my current NodeJS + MongoDB stack? 
I know that i can create this integration on the client side by first POST the message to the server and then publish it to socketcluster server but i think that it's not the best solution...

thanks in advanced for any help !

**Comment by ranhsd** [comment]
Hi @jondubois , thanks a lot for your quick response.. 
I forgot to mention that my stack is k8s stack and currently i deployed both NodeJS servers there (my application server and socketcluster server) so both are located in the same cluster which means that i can access from my application-server and vice versa in a very simple way (k8s really make life easy for me with that) so based on that what do you think?

**Comment by sacOO7** [comment]
Hi @ranhsd , There is a mongo driver for integration with node.js https://github.com/mongodb/node-mongodb-native. I think you should try out some of examples based on socketcluster APIs , as there is no need to send POST request by client in order to store messages. You can just emit message via socketcluster-client and corresponding server side API will handle everything for you.

**Comment by ranhsd** [comment]
hi @sacOO7 yes but the socketcluster and my NodeJS app server are decoupled and i don't want to use the MongoDB driver on my socketcluster  server i want to use it only in my application server what do you think about the following: 

1. the Mobile client will send POST request to the application server to create a new message
2. the application server will store the message in MongoDB 
3. After the message will be stored the application server will use socketcluster client (NodeJS) to emit the message to the socketcluster server
4. The socketcluster server will receive the message and will publish it to the specific channel
5. All subscribes (on the mobile device) will receive the message

This way we can create something similar to "real time database" so events will be emitted only after the data has being saved to the database. 

what do you think ?

**Comment by sacOO7** [comment]
I think sending POST request is not a good approach. As you are developing real-time application , POST request will introduce some delay while travelling from client to server. I just want to know , why you don't want socketcluster server to have functionality to connect to mongoDB and store the messages ? If both servers are located in same cluster, you can create global mongodb-client driver instance and export it to both servers.

**Comment by ranhsd** [comment]
Hi @sacOO7 yes I can .. but I don't 100% sure that I understand your suggestion ..
What will be the flow starting from the client through saving it into the DB until it sent to other clients in your suggestion?

Thank.

**Comment by sacOO7** [comment]
Well , as I explained earlier, client will send emit message to server. Message will consist of data that you want to save on your database. Your socketcluster server file will consist of import for mongo client instance. There will be code block to handle incoming message where you will get message data and then you can save it in mongoDB. Then call publish method to publish data to intended users.

I think this is most detailed explanation I can give without code :p . I think you should try out some examples .

**Comment by webeindustry** [comment]
Is there any reason this issue remains open? The original question was well answered.

**Comment by jondubois** [comment]
@webeindustry It takes too much effort to click on the 'close' button ;p
