### ISSUE TITLE
Passport-Steam with SC?

### ISSUE THREAD

**Issue by FantomHD** [SocketCluster/socketcluster#259]
Hi there. So my web app used to run solely on socket.io and it worked great until it couldn't support that many concurrent users at once with my inefficient code. I'm now working on transitioning to SC but i hit a large road block. I had previously used Passport-Steam to authenticate players and it was a great system. I passed the session middleware into socket.io so when an authenticated user issued a message to the server, I could refrence the socket and see which steam id sent it, knowing that it was for sure from that person since the ID was a cookie essentially. Now authentication is not my strong point and I barely have my head wrapped around it. I sorta understand JWT's and how to use them with SC but I need the steam userid's and need to make sure they are secured. This was super easy with socket.io but I cant seem to get it with SC. Any help is super appreciated. The goal is to essentially have a player log in with steam and anytime they make a connection to the server, I can get a secure token from them that I can refrence back to a steam Id. 

Edit: Been doing a lot more research and anything I find is honestly mind boggling to me. Socket.io worked so well for this but i really do need to switch over to a better system like socket clusters. This is really holding me back and it would be really nice for some sturdy compatibility of passport and socket clusters as it seems to be a fairly common issue for people. To my knowledge #53 is the closest ticket to a solution but it isnt complete enough for me and I cant build off of it. Similarly, in some other thread you talk about the methodology of doing this correctly. Where the client gets authenticated, passes its info to the server, server checks if its legit, if so it passes back a JWT, however I dont see how I can apply that the passport-steam strategy. Really, anything is helpful because I would really like to continue using steam as my authentication service.

**Comment by jondubois** [comment]
@FantomHD You should be able to do authentication however you like over HTTP on the server - From there you can create a token, send it back to the client (E.g. in the HTTP response) and on the client, you add it to localStorage. The full instructions are here: https://github.com/SocketCluster/socketcluster/issues/233#issuecomment-254871963

If you're using passport-steam, all you have to do is create the token inside the callback here https://github.com/liamcurry/passport-steam#authenticate-requests (once the steam authentication has succeeded) and pass that token back to the client in the HTTP response.

Then to do authorization (which is different from authentication) on WebSockets, you should look into http://socketcluster.io/#!/docs/middleware-and-authorization

The JWT token is basically a just special certificate which the server gives clients (upon successful login/authentication on the server-side) and which allows clients to prove their identities in the future without having to show a password.

So for example,  if a client loses the connection and then reconnects to a new server/process which has never seen that client/user before, the server can still verify their identity by looking at their token - That's why this approach is scalable.

In SC, whenever the `socket.authToken` property exists on the server, it means that the client has a valid auth token.

**Comment by FantomHD** [comment]
So been working on it for a while now, and now hititng this error:

`WebSocket connection to 'ws://xxx.xxx.xxx/socketcluster/' failed: WebSocket is closed before the connection is established.
(index):12 Uncaught Socket error - SocketProtocolError: Client connection establishment timed out`

Im still confused, but less confused lol. here is my index, 

`<!DOCTYPE html>
<html>
  <head>
    <title>SocketCluster</title>
    <script type="text/javascript" src="/public/public/socketcluster.js"></script>
  </head>
  <body>

    <script type="text/javascript">
var socket = socketCluster.connect();
      socket.on('error', function (err) {
        throw 'Socket error - ' + err;
      });
      socket.on('connect', function () {
        console.log('CONNECTED');
      });
      socket.on('rand', function (data) {
        console.log('RANDOM STREAM: ' + data.rand);
      });
      var sampleChannel = socket.subscribe('sample');
      sampleChannel.on('subscribeFail', function (err) {
        console.log('Failed to subscribe to the sample channel due to error: ' + err);
      });
      sampleChannel.watch(function (num) {
        console.log('Sample channel message:', num);
  });
    </script>
  </body>
</html>`

and my worker.js

`var express = require('express'),
    session = require('express-session'),
    cookieParser = require('cookie-parser'),
    passport = require('passport'),
    passportSocketCluster = require('passport.socketcluster'),
    RedisStore = require('connect-redis')(session),
    SteamStrategy = require('passport-steam').Strategy;
		var healthChecker = require('sc-framework-health-check');

module.exports.run = function (worker) {

	var app = express(),
		cookieKey = 'session',
		cookieSecret = 'melons',
		store = new RedisStore();

	var httpServer = worker.httpServer;
	var scServer = worker.scServer;

  	healthChecker.attach(worker, app);

  	httpServer.on('request', app);

app.use('/public', express.static('public'));

passport.serializeUser(function(user, done) {
  //stores user in session.passport.user
  done(null, user);
});

passport.deserializeUser(function(user, done) { 
  done(null, user); 
});

passport.use(new SteamStrategy({
  returnURL: 'http://104.236.115.98/auth/steam/return',
  realm: 'http://104.236.115.98/',
  apiKey: 'DF3BAAE0ED45123D96B777EC50C7C8C3'},
  function(identifier, profile, done) {
    process.nextTick(function () {
      return done(null, profile);
    });
  }
));

var sessionMiddleware = session({
  secret: 'melons',
  name: 'User',
  resave: true,
  saveUninitialized: true
});

app.use(sessionMiddleware);

app.use(passport.initialize());
app.use(passport.session());

app.get('/auth/steam', passport.authenticate('steam'), function(req, res) {});

    app.get('/auth/steam/return',
      passport.authenticate('steam', { failureRedirect: '/auth/steam' }),
      function(req, res) {
        res.redirect('/');
    });
  
    app.get('/', ensureAuthenticated, function (req, res) {

      res.sendFile(__dirname + '/public/index.html');

    });

  scServer.addMiddleware(scServer.MIDDLEWARE_HANDSHAKE, passportSocketCluster.handshake({
    cookieParser: cookieParser,
    key: cookieKey,
    secret: cookieSecret,
    store: store,
    passport: passport,
    callback: function(err, req, user, next){
        if(!err){
            req.socket.setAuthToken({ //authenticates socket only if user information was loaded
                profile: {
                    name: user._json.personaname,
                    avatar: user._json.avatar
                }
            });
        }
        next();
    }
}));


  function ensureAuthenticated(req, res, next) {
    if (req.isAuthenticated()) { return next(); }
    res.redirect('/auth/steam');
  }

 scServer.on('connection', function (socket) {

    // Some sample logic to show how to handle client events,
    // replace this with your own logic

    socket.on('sampleClientEvent', function (data) {
      count++;
      console.log('Handled sampleClientEvent', data);
      scServer.exchange.publish('sample', count);
    });

    var interval = setInterval(function () {
      socket.emit('rand', {
        rand: Math.floor(Math.random() * 5)
      });
    }, 1000);

    socket.on('disconnect', function () {
      clearInterval(interval);
    });
  });

};`

**Comment by FantomHD** [comment]
Update: So after following a lot of what you said, I've gotten to the point where I sign my passport token with worker.auth.signToken and currently and sending it to my client as a cookie. However, I'm stuck here. The cookie shows up on the client but I don't know how to save it to local storage to set it as the "socketclsuter.authToken". I tried to get the cookie but that didn't really work. You also said somewhere I should just send it as part of the response body but I couldn't figure that out. Could you elaborate here please? Sorry for being a nuisance since i'm so inexperienced!

**Comment by jondubois** [comment]
@FantomHD Ah, you should remove the `{ httpOnly: true /* TODO: Set secure: true */ }` option when setting the cookie from the server - Setting it as httpOnly prevents you from accessing it and editing it in your JS client-side code.

If you remove the httpOnly stuff from the server, on the client side, you should be able to copy the token from the cookie and put it inside the localStorage (at key `socketCluster.authToken`), then, when that's done, you can call `socketCluster.connect(...)` and the socket will be authenticated.

Maybe steam also offers other ways to send the JWT token to your front end... I'm not familiar with it. In any case, it doesn't matter how you provide the JWT token to the front end; so long as you manage to create the token on the server and pass it to the client (and store it in the appropriate localStorage key) before it connects, the SC authentication will be automatic.

**Comment by FantomHD** [comment]
Great! I got it to work! Without using the JWT module and just using worker.auth.signToken, how secure is this? Do I need to secure the cookie? If so could you point me to how, this is sorta leaving your domains so i dont want to continue being a burden. Thanks so much for getting me here though!

**Comment by jondubois** [comment]
@FantomHD It's safe. You don't need to secure the cookie. The token which is in the cookie is signed and therefore cannot be tempered with by the user.

The reason for using httpOnly when setting a cookie is to prevent it being stolen as part of XSS attacks (if an attacker manages to sneak an unauthorized script into your site/app).

I wouldn't worry about this. If your website/app has been compromised by an XSS attack, the attacker could already do some serious damage without having access to the token - Having access to the token doesn't have much additional value to an attacker who already has his code running on all your users' browsers.

In case of an XSS attack, remove the offending script tags/iframe (or whatever the offending component is) from your site/app and then make sure you change the `authKey` option provided to SocketCluster on the server side (and reboot) to invalidate all previously granted tokens.

**Comment by FantomHD** [comment]
Ok great, thanks for the top notch support, honestly! This solidifies my decision to stick with socketclusters over socket.io!
