### ISSUE TITLE
Can a worker listen to a channel?

### ISSUE THREAD

**Issue by FantomHD** [SocketCluster/socketcluster#262]
Im back! Quick question that I couldnt find on my own. Can a worker subscribe to a channel too? I planned to use a feature like this to communicate between worker instances but cant find the syntax anywhere... Only client syntax for subscribing to a channel. 

Edit: While reading further, I found that worker.global is a thing. Does this mean i set values into it and they will update live on other workers? Because this would solve a lot of my problems!

Edit 2: Ill just ask for the most clear response: What is the best way to share information between worker instances? A database is not the way to go here because some of the data i need fast, I mean locally fast, which is why I want to be able to have a server listen to a channel, so once the worker the client's connected to has processed the data from the client it can post this data to the channel and all the other workers can pick it up too. Its not a lot of data, its just a position value that i store into an array, so its not very redundant, but I need the position value live so has to be lightning quick to update for other people.

**Comment by jondubois** [comment]
@FantomHD Yes you can communicate between workers using channels. You should use the `worker.exchange` property (not worker.global - That's deprecated).

The Exchange object is here: http://socketcluster.io/#!/docs/api-exchange

Sharing data between workers via channels is the cleanest way. Just make sure that you don't end up sharing TOO much between too many workers or it will affect scalability. Also, try to group data together (e.g. in an array) when publishing it - It's more efficient to publish one long message with lots of data than many small ones.

**Comment by FantomHD** [comment]
Great this is everything I needed! Thank you once again!
