### ISSUE TITLE
[QUESTION] Any references to clients? 

### ISSUE THREAD

**Issue by githubfreedcamp** [SocketCluster/socketcluster#264]
Can you provide any references to clients who use it under high load in cluster environment in production to contact and ask them to share how SocketCluster works for them?

Thanks
Igor

**Comment by happilymarrieddad** [comment]
@githubfreedcamp Hey man, we are using it in production and have been for over a year. We started on SC2 and are now on SC5 so I think we've had quite a bit of experience with it. It's stable, fast, and efficient. In my opinion, it's the best web framework out there and @jondubois is an awesome guy as well who always answers any questions I have quickly. I can't say enough good things about it. We have quite a few customers. For example, our main database is a 16 core AWS server that's always around 8%-10% load. I'm not sure if that's the kind of load you are referring to. If it matters, here is our stack.

1) Nginx
2) REDIS - sub pub (moving to SCC soon. It wasn't around when we first set up our project.)
3) Socketcluster for servers (we use socketcluster instances at each customer's site and they communicate data back and with the main instance) (basically we grab data from customers' data warehouses and share the data among customers)
4) MySQL, MSSQL, Oracle 11.2g and 12.1g, DynamicsGP ... and a ton of other databases..
5) VueJS for the font-end
6) Express for the API (it's part of SC)

**Comment by githubfreedcamp** [comment]
Hey!

Thanks for sharing.

Can you share more on point 3 - how many nodes, what horse power, how reliable it is when node fails both on client side and your side?

Anything like open connections, messages per day, messages per minute to show how loaded these systems are?

Cheers,
Igor

**Comment by slidenerd** [comment]
@happilymarrieddad if you dont mind answering, are you using the native js client with vue or are you using some sort of library

**Comment by happilymarrieddad** [comment]
@slidenerd We are using socketcluster-client. 

@githubfreedcamp I've migrated our project to Golang and Vue2. We are no longer using Socketcluster except for sub-pub which will eventually be replaced by Hyperledger's Event System. Thanks!
