### ISSUE TITLE
SCSocket._onSCClose [error]

### ISSUE THREAD

**Issue by zmikolaj** [SocketCluster/socketcluster#267]
Hi, i get this error:
```javascript
data:    main.js:5462 - 1485546264816 - Origin: Worker (PID 5513)
data:    main.js:5462 -    [Warning] Error
data:    main.js:5462 -     at SCSocket._onSCClose (/home/node_modules/socketcluster-server/scsocket.js:202:17)
data:    main.js:5462 -     at Timeout.<anonymous> (/home/node_modules/socketcluster-server/scsocket.js:167:10)
data:    main.js:5462 -     at ontimeout (timers.js:365:14)
data:    main.js:5462 -     at tryOnTimeout (timers.js:237:5)
data:    main.js:5462 -     at Timer.listOnTimeout (timers.js:207:5)
```

What its mean?

**Comment by jondubois** [comment]
Which version of SC are you using? How are you logging this?

**Comment by jondubois** [comment]
You may need to `npm update socketcluster-server` or `socketcluster` itself.

**Comment by trzyrazyzero** [comment]
```SocketProtocolError```
Its mean that client-side is outdated or server side?

**Comment by trzyrazyzero** [comment]
Socketcluster on clientside 5.2.4 version.
socketcluster@5.2.1 socketcluster-server@5.4.1 on serverside.

**Comment by jondubois** [comment]
There should be a message that tells you what went wrong.
Check `err.code` and `err.message`.
You can see what all the codes mean here:

https://github.com/SocketCluster/sc-errors/blob/master/index.js#L206-L225
