### ISSUE TITLE
use fixed version dependencies

### ISSUE THREAD

**Issue by mattkrick** [SocketCluster/socketcluster#268]
the latest sc-auth breaks my entire app. since the dep required is not fixed to a specific version, it grabbed the newest version without my knowing (which made for a debugging nightmare). would be great to nail down all dependencies to static version numbers so this doesn't happen in prod.

also, we should fix sc-auth... 
`socket.setAuthToken(authToken);` never sends a token to the client, i'm still trying to figure out why not...

**Comment by jondubois** [comment]
@mattkrick Thanks for looking into this. Having flexible versions for all sc-related dependencies was convenient for a while but I agree that the time has come to lock all of them down.

I  propose using the recommended npm format `'~1.2.3'` and to get more strict with semantic versioning when bumping up dependency version numbers.

**Comment by jondubois** [comment]
Did you find which version of `sc-auth` introduced the problem? https://github.com/SocketCluster/sc-auth/commits/master

**Comment by jondubois** [comment]
@mattkrick I think the issue might be with this commit: https://github.com/SocketCluster/sc-auth/commit/24afe2e227f4a96c99674360db67a2d7be45e26b - I upgraded jsonwebtoken and started using the async version of the `sign` function/

You can either downgrade all `sc-auth` dependencies to `v3.0.0` (it should be referenced twice; in socketcluster and in socketcluster-server) or upgrade `socketcluster` to `v5.2.2` (make sure that `socketcluster-server` is `v5.4.4`). There haven't been any breaking API changes to SC in a long time so upgrading should be straight forward. Let me know if not.

The `socket.setAuthToken(authToken);` is working for me when I use the latest version of SC with latest dependencies.

**Comment by mattkrick** [comment]
With the latest versions of everything, it still fails for me. I made a PR on sc-auth that fixes it (it was throwing a warning about `exp` being included, so i removed it from the token). Perhaps that was causing an error to be thrown?

**Comment by mattkrick** [comment]
proposal:

- release socketcluster/-server at v.5.2.3 and v5.4.5 that revert back to sc-auth 3.0.0 and hardcodes all deps.
- release socketcluster/-server at v5.2.4 and v5.4.6 that bump sc-auth to 3.1.0

that way, i can just install the former versions and still be OK while we discuss what to do with sc-auth.

**Comment by jondubois** [comment]
@mattkrick Ok, I published the updated socketcluster & socketcluster-server v5.2.3 & v5.4.5 as you proposed (pointing to the old sc-auth 3.0.0).

**Comment by jondubois** [comment]
I published v5.2.5 and v5.4.6 with the newest sc-auth and with the fix in `socketcluster-server`.

**Comment by jondubois** [comment]
Hopefully this is all better now with the package-lock.json file.
