### ISSUE TITLE
How to reject connection if user already logged in another device?

### ISSUE THREAD

**Issue by nguyenhaian** [SocketCluster/socketcluster#271]
@jondubois Hi, my game requires user only login in one device at a time. If he login in device A, then he cannot login in device B. I use MIDDLEWARE_AUTHENTICATE to reject if know that user has already logged in.

I try to implement this, but have not success.

```
var scServer = worker.scServer;

scServer.addMiddleware(scServer.MIDDLEWARE_AUTHENTICATE, function(req, next) {
    // my req.authToken like this
    // {
    // 	uid: '123456789',
    // }
    var uid = req.authToken.userid;
    var udata = req.authToken;
    // add worker id in which user currently connected
    udata.w = worker.id;

    // look into public store to check if user is currently logged in.
    broker.get(uid, function(err, userinfo) {
        if (userinfo) {
            // user may be is logged in by another device
            // or may be disconnected but some how broker did not remove him
            tryContactClient(worker userinfo, function(err) {
                if (err) {
                    // can not contact user, allow new connection
                    next();
                } else {
                    // can contact user normally, don't allow new connection
                    next({ name: 'UserAlreadyLoggedIn' });
                }
            })
        } else {
            // user not logged in, allow him to log in.
            // set to store to later determine if user is online.
            broker.set(uid, udata, function(err) {});
            next();
        }
    });
});


scServer.on('connection', function(socket) {
    if (socket.authState != 'authenticated') {
        socket.disconnect(4100, 'unauthenticated'); // mã code err này mình tự quy định
    }

    socket.on('disconnect', function() {
        var uid = socket.authToken.userid;

        // delete key from broker
        broker.remove(uid, function(err) {});
    });
});
```

I cant find good solution to implement tryContactClient() function.
If user currently logged in this worker, it quite easy using emit with callback function to confirm connection is good.
But if user does not easy in other cases.

```
function tryContactClient(worker, userinfo, callback) {
    var scServer = worker.scServer;

    if (userinfo.w == worker.id) {
        // cùng Worker, gửi luôn bằng emit
        scServer.clients[userinfo.sid].emit(EVENT_PING, null, function(err) {
            callback(err)
        })
    } else {
        // TODO: how to contact woker with id {userinfo.w} with callback
        // worker.sendToMaster has no callback

        // worker.sendToMaster({ action: ACTION_PING, wid: userinfo.w, sid: userinfo.sid });
        callback(null); // tạm gửi là không lỗi
    }

}
```

Or can I using publish function with callback function to confirm connection status, with channel is userid?
```

// Server code
socket.exchange.publish(userid, null, function (err) {
  if (err) {
    // Failed to publish event, retry or log?
  } else {
    // Event was published successfully
  }
});
```

Any one can help me solve this problem? Much thanks.

**Comment by jondubois** [comment]
@nguyenhaian Publish actions don't have callbacks but you can subscribe to a new channel on the server to handle acknowledgements from users.

So for example, for a user 'bob123', you could do:
```
// Capture acknowledgements (ack) sent from client when they have received the message, the ack
// should contain the mid from the message.
scServer.exchange.subscribe('bob123-messages-ack').watch(function (data) {
  // You can use data.mid
});
scServer.exchange.publish('bob123-messages', {mid: 'someuniquemessageid', message: 'some data'});
```

In SC, you can create as many channels as you like - They're very inexpensive so feel free to create lots of them.

Also note that in your code, it should be `scServer.exchange.publish` not `socket.exchange.publish`.

**Comment by nguyenhaian** [comment]
@jondubois Thank you. I understand your solution, but in my case, I want to decide right in MIDDLEWARE_AUTHENTICATE function whether or not user can log in.

If I check connection state like in your solution, I have to reject the new connection later. 
May be I have to do that.

**Comment by jondubois** [comment]
@nguyenhaian Oh I misunderstood the question. You can check the auth token inside the `MIDDLEWARE_AUTHENTICATE` middleware using `req.socket.authToken` - See http://socketcluster.io/#!/docs/authentication - The auth middleware runs after the token has been verified/attached and before the connection is triggered - Note that it only runs if the token exists and is valid.
