### ISSUE TITLE
Assign variable to the socket object

### ISSUE THREAD

**Issue by JCMais** [SocketCluster/socketcluster#273]
Am I safe to assign a variable to a socket object and expect it to be available during the middleware calls?

I want to assign some valid values that the server allows given socket to subscribe to during the socket.connection event.

And so check for them when the middleware responsible for the authorization is called.

**Comment by frank-dspeed** [comment]
@JCMais yes your save if you use something that is free :)

**Comment by jondubois** [comment]
@JCMais Yes that's fine of course; just make sure you don't overwrite any existing properties of the socket object.
