### ISSUE TITLE
Also cluster regular sockets?

### ISSUE THREAD

**Issue by wmertens** [SocketCluster/socketcluster#275]
I was wondering if it would be easy to add support for clustering regular TCP connections. I have a project where I need to accept connections with a plain TCP protocol, and having the SC infrastructure is nice. Right now I have only the one process accepting connections.

Alternatively, is it possible to somehow accept plain TCP with the websocket server?

I can only ask 😄

**Comment by jondubois** [comment]
It would be a lot of work since WebSocket connections start with a HTTP request and a lot of properties that exist with WebSockets would not be present with TCP.
