### ISSUE TITLE
Publish from loopback model system

### ISSUE THREAD

**Issue by KCypher13** [SocketCluster/socketcluster#278]
Hi everyone,

I'm using SocketCluster with Loopback.js, and I need to publish to a SC channel from the loopback model system.

Here is an exemple (because it's not very obvious): 
I make a POST request to an endpoint handle by Loopback,
the Loopback handler do it jobs (persisting datas, etc...)
then I want to publish the modified datas (by the handler) on a SocketCluster channel (with scServer.global.publish() ).

I've tried to create a custom event between a broker and loopback, but it didn't work.
I know I can handle this with sc-redis, but it's not really what I'm looking for.

Is the solution to create a HTTP server directly on my broker and interact with from my loopback model ?

Or there is another solution directly inside nodeJS (with custom event, or other stuff) ?
I read some other issues with a almost a similar problem, but didn't find a solution.
I'm sorry if the solution is already somewhere.

Thanks !

**Comment by gantir** [comment]
@KCypher13 is the issue solved?
