### ISSUE TITLE
Unsubscribe on disconnect?

### ISSUE THREAD

**Issue by Charuru** [SocketCluster/socketcluster#283]
Does the unsubscribe event fire when a user is disconnected? I thought it was yes.

I'm trying to do presence like this:

    socket.on('unsubscribe', function (channel) {
      removeUsersFromChannel(socket.id, channel)
    });

    // not needed right now. When disconnecting the unsubscribe is automatically fired.
    // socket.on('disconnect', function () {
    //   removeUsersFromPresence(socket.id)
    // });

Is this correct? For some reason users aren't always removed from the database when they leave. Currently using 5.9.0.

**Comment by jondubois** [comment]
@Charuru The unsubscribe event should fire when a socket disconnects.
The problem which this approach is that if your SC worker crashes suddenly, you may lose track of your presence sessions so you have to figure out a way to clean them up later.

**Comment by Charuru** [comment]
Thanks. I'm fixing up some errors. Do you have any advice for how to handle the clean up in general in case there are crashes for other reasons?

**Comment by Haocen** [comment]
I usually clean it up next time I run into that session, which usually happens next time user try to connect.

I also have scheduled cleanup run on disaster recovery/hot redundant, but not my immediate failover.

**Comment by jondubois** [comment]
@Charuru You can just destroy the socket if you're certain that you don't want to reuse it again. Also you can pass the `multiplex: false` option when creating the client socket to make sure that sockets are never reused.
