### ISSUE TITLE
How to unsubscribe before socket reconnect by server？

### ISSUE THREAD

**Issue by luozan** [SocketCluster/socketcluster#284]
I have a socket was subscribed to channel "A" and watched it.
If this socket reconnect,then new socket also can get message from channel "A".
I don't want new socket subscribed.How can I do it?

**Comment by happilymarrieddad** [comment]
You can use

socket.on('disconnect',function() {
     socket.destroy()
    // Then call whatever function you want to reconnect and setup subscription
})

@jondubois  hey man what you do think about this solution.. if it can be called that?

**Comment by jondubois** [comment]
@luozan There are many ways to do this, for example you can unsubscribe the channel with `socket.unsubscribe('channelName')` when the socket 'close' event triggers... Or you can destroy the whole socket as @happilymarrieddad suggested (and this will also delete any attached channels).
