### ISSUE TITLE
How scoket cluster really works ??

### ISSUE THREAD

**Issue by Himansh-Tiwari** [SocketCluster/socketcluster#285]
I just want to understand few things that i am confused.
1. How many sockets does it create, when we publish to a channel, assuming 100 users.
2. Can we have a way to create dynamic channels?
3. what if i have 100k users open, how it can manage the load or sockets, i just want to know how it works and manipulates sockets.

Thanks

**Comment by MegaGM** [comment]
1. One socket per connected client. Two opened tabs in a browser == 2 clients. The sockets quantity doesn't correlate with publishing at all.
2. All channels are being created dynamically, when a first client subscribes to a channel. When the last, subscribed to the channel, client unsubscribes - the channel is being destroyed by SocketCluster automagically.
3. All clients(sockets) are distributed ~equally between workers. The same goes for channels, they're distributed between brokers. In theory, you can work with 100kk clients simultaneously, if you have enough SocketCluster's clusters in your setup.


Anyway, @Himansh-Tiwari, this is a bug tracker. So, please, close the issue.
If you want to understand SC workflow better, feel free to ask any questions in the SocketCluster's chat room. There are many people who could help you there. https://gitter.im/SocketCluster/socketcluster
