### ISSUE TITLE
Server xxxxxx at address undefined on port 8888 left the cluster

### ISSUE THREAD

**Issue by ArmorHerO** [SocketCluster/socketcluster#288]
i wang to install a scc  but when i start broker they said "Server xxxxxx at address undefined on port 8888 left the cluster"  i do it use the scc-guide ,i want to made a sc cluster

**Comment by alexus85** [comment]
Was facing the same issue last time when I wanted to test something on my laptop with Windows 10. I was unable to figure out as why the messages are not being distributed between all the active SC nodes. But it all started working when I switched to my Ubuntu. So I'd suggest you to do the same.

**Comment by ArmorHerO** [comment]
@alexus85 I solved the problem, I changed the command to start broker "SCC_INSTANCE_IP = '127.0.0.1' SCC_STATE_SERVER_HOST = '127.0.0.1' SOCKETCLUSTER_SERVER_PORT = '8888' node server" I still set up a loadblancer in front of the cluster, and then loadblancer As an entrance, but I still do not particularly understand the role of scc-broker, you can tell me how you understand

**Comment by happilymarrieddad** [comment]
@ArmorHerO Hey man, so the scc-broker is essentially what used to be sc-redis for communication between the servers. It's a 1 to many relationship in reference to scc-state. The scc-state server holds state between the servers and scc-broker handles the communication between the servers. I hope that makes sense.

**Comment by jondubois** [comment]
@ArmorHerO Pretty much what @happilymarrieddad said: the relationship between scc-state and scc-broker is 1 to many.

The relationship between scc-state and socketcluster instances is also 1 to many.

The relationship between socketcluster instances and scc-broker is many to many - This means that you can keep adding as many socketcluster and scc-broker instances as you like and everything will scale linearly/automatically.

scc-broker instances allow socketcluster instances to automatically share pub/sub channels with each other across multiple machines/hosts. So if you have the same channel name on two different socketcluster instances/hosts, scc-brokers will combine them into a single channel that spans multiple machines.

scc-state just coordinates how the socketcluster instances connect to the back end scc-brokers (like checking when new scc-brokers or socketcluster instances come online or go offline and resharding channels across them accordingly).

**Comment by happilymarrieddad** [comment]
@ArmorHerO Hey man, thanks so much for participating in the socketcluster community. If your issue is solved can you please close this issue. If not, what can I do to help you fix your issues? Thanks so much!
