### ISSUE TITLE
Not able to get public ip after deploying on minikube

### ISSUE THREAD

**Issue by rachlies** [SocketCluster/socketcluster#289]
Deployment of the services is working properly on the vm (minikube).
Status is set to running on the Kubernetes dashboard for
* pods
* deployment

There is no public endpoints exposed from scc-state, scc-broker, socketcluster server.
So currently I am not able to understand how do I access the services externally i.e. outside the virtual machine (that is running on minikube). 

The images were built from the kubernetes yml files directly, with the ingress TLS security disabled.
Am i missing out on any aspect as to how to access the socketcluster on the host machine?

**Comment by joyson-17** [comment]
Hi,
Did you get through the issue you were facing? Can you post your solution?

**Comment by rachlies** [comment]
Hey joyson, 

I just change the service type for socketcluster to NodePort and then I am able to access over public internet through the minikube ip and the port which is assigned to socketcluster service. But I am still facing issue for load balancing purpose.
