### ISSUE TITLE
Dispatching events between clusters

### ISSUE THREAD

**Issue by shengis** [SocketCluster/socketcluster#291]
As stated in the _SCC Guide_, only one scc-state must be run by cluster.
Is there a way to dispatch events between clusters ? As my clients on cluster 1 receive events on cluster 2 ?

Thanks !

**Comment by happilymarrieddad** [comment]
@shengis 
```
// Cluster 1
worker.subscribe('SOME_CHANNEL').watch(data => console.log(data))

// Cluster 2
worker.exchange.publish('SOME_CHANNEL',{ id:1 })
```
Hope that makes sense.

**Comment by shengis** [comment]
Thanks @happilymarrieddad !
I expected a solution at the broker level, but ok, I think your solution could work.

**Comment by happilymarrieddad** [comment]
@shengis you can publish from the broker as well. In SC5 the broker really shouldn't be doing anything other than backend sc stuff. Communication requests should be handled by the worker. @jondubois what do you think?

**Comment by happilymarrieddad** [comment]
@shengis hey man if this solves your problem can you please close this issue? If not let me know what else I can do to help. Good luck!

**Comment by shengis** [comment]
I was waiting for the thoughts of @jondubois, but actually it's solving my problem, so thanks 👍
