### ISSUE TITLE
Did the receiver receive the message or not.

### ISSUE THREAD

**Issue by joyson-17** [SocketCluster/socketcluster#292]
Hi,

I was wondering if there is a way that the socketcluster server would know if a receiver is actually subscribed to that channel or not. I am developing a chat server and I would like to know if the receiver is online or not. If offline then save the message in a message data store and send it to the user once he connects back on. 

I did go through the design patterns blog which says that the user can request a snapshot of the last messages received but then it still does not tell me how many messages were not sent to the receiver, there may be duplicate messages which may go.

I have a private channel for every user. The sender emits the message to the server and the server publishes the message to the receiver. I just want to know if the receiver received the message or not so that I can send him a notification if he hasn't.

Regards,
Joyson.

**Comment by happilymarrieddad** [comment]
@joyson-17 Hey man, that sounds like something you should use the db for. You could store messages in a "queue" table or something and then if a user logs in and there are messages in that table pop them off and broadcast them to that user. @jondubois What do you think?

**Comment by joyson-17** [comment]
@happilymarrieddad : Yes, I will be following the below method:
1. Sender sends the message. Store it in a DB with ack value 0.
2. Send it to the receiver and wait for ack.
3. Receiver sends the ack, change ack value to 1.
4. In case receiver reconnects, receiver sends all pending acks and asks the server to send all pending messages with ack 0.

Regards,
Joyson.
