### ISSUE TITLE
Do I have to put socketcluster.js on client side in order to use it?

### ISSUE THREAD

**Issue by crazyyi** [SocketCluster/socketcluster#294]
I am using yarn/npm to build my project. `<script type="text/javascript" src="/socketcluster.js"></script>` is added in the html file. But the browser tells me it can't find the file. I found in this example:
[sc-chat](https://github.com/nelsonzheng/sc-chat/tree/master/public) that a socketcluster.js file is in the public directory. But I don't want to put it there because it is too big. Is there any other way I can use socketcluster on client side?

**Comment by happilymarrieddad** [comment]
@crazyyi How are you serving static files?

**Comment by crazyyi** [comment]
@happilymarrieddad  I use expressjs to serve the static files. I try to use `socketcluster` as [socket.io](https://socket.io) maybe that's the problem. I think `socket.io` will serve the `socket.io.js` file on the server when I link its websocket server to the http server. In `socketcluster` I don't know how to do that properly.

**Comment by happilymarrieddad** [comment]
you should be serving the socketcluster.js file in the example. You can just point to it in your html file. As you can see here it's in the public folder. You then reference it in your html file or however you are serving your app. I hope that makes sense.


![selection_193](https://cloud.githubusercontent.com/assets/6416323/26222888/e64c39d2-3bd8-11e7-8c90-3abc0c450736.png)

**Comment by frank-dspeed** [comment]
i think that can be closed as its related to javascript + http basics
