### ISSUE TITLE
scc-guide not correct?

### ISSUE THREAD

**Issue by dotob** [SocketCluster/socketcluster#295]
hi,

trying to test with the local version of the scc guide. i managed to clone and npm i the three repos. scc-state and scc-broker are running fine, but unfortuantely i cannot start sockecluster as either the named repo is wrong or the description of what to execute for a start. the document states i should execute `node server`, but in the https://github.com/SocketCluster/socketcluster repo is no server.js file and the index.js does not start a server. what am i doing wrong?

thanks for your help?
sebastian

**Comment by jondubois** [comment]
@dotob Yes actually the part about launching the socketcluster instance was misleading. I've updated the guide. Let me know if it makes more sense now: https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md

**Comment by dotob** [comment]
awesome, thanks this is much better now. i tried it and it worked. thank you very much.
