### ISSUE TITLE
Upgrade SC Docker image to use Node.js v8

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#299]
Do it.

**Comment by jondubois** [comment]
@heiba I pushed a new Docker image v5.15.0 - But this is Node.js v7.10.0.

Unfortunately, the base image for Node.js v8.x.x-xxx fails to compile uWS so I raised an issue here: #630

It seems more like an issue on the Node.js side than uWS though. The upgrade to Docker image for Node.js v8 will have to wait until this issue is resolved.

**Comment by heiba** [comment]
That's superb. It's fine, 7.10 supports async and await which is exactly what I want. Sure happy to wait for the v8 updates when the issue is resolved and a need arises.

Sincerely, thank you man.

**Comment by jondubois** [comment]
Ok the latest docker image runs Node.js v8.
