### ISSUE TITLE
from socket.io to socketcluster

### ISSUE THREAD

**Issue by MatthieuHPP** [SocketCluster/socketcluster#301]
Hi,
socketcluster seems very insteresting for clustering. 
I would like to upgrade my application written with socket.io, with socketcluster. 
What have I to consider to do so ?
Many thanks
Matthieu

**Comment by WwoeSsi** [comment]
Follow. I'd like to do the same.

**Comment by WwoeSsi** [comment]
Nobody knows?

**Comment by jondubois** [comment]
@MatthieuHPP @WwoeSsi Although there are a few similarities, it depends on how deeply you're using the Socket.io API. Usually it will require some code changes as well. No step-by-step guide exists at this stage though it might be worthwhile for me to write one.

In the meantime you have to familiarise yourself with the docs: http://socketcluster.io/#!/docs

**Comment by WwoeSsi** [comment]
Yeah @jondubois , very worthwhile because I think most people are using socketio though it's not as scalable it seems....

**Comment by MatthieuHPP** [comment]
Many thanks. I will look at it.

**Comment by slidenerd** [comment]
Thank god I searched issues :) before posting this, one thing that would be super appreciated is if you can elaborate what socketcluster can do over the cluster module or socketio, you dont have to do it here, a medium post will be helpful too but a comparison would be super appreciated
