### ISSUE TITLE
Can we setup standalone socketcluster server?

### ISSUE THREAD

**Issue by navjotdhanawat** [SocketCluster/socketcluster#302]
**Is it possible by using SocketCluster?**

Suppose SocketCluster(Standalone) server is 'S'(https://s.com:4000).
And I had deployed my nodejs application on 'A-Server'(https://A-Server.com:4000).

How do I use socketCluster in this scenario? My web app URL is https://A-Server.com:4000

**Communication Should be like below:**

client ------- SocketCluster ------  My Server(https://A-Server.com:4000)  ------  SocketCluster ---- Client.

Similar to (pusher or pubnub) functionality. I want to implement it for my 3 web apps.

**Comment by frank-dspeed** [comment]
it is possible you only need to learn javascript + http you can close this as this is not a support forum and you posted no bug thanks
