### ISSUE TITLE
Want to recover data after restart socketCluster

### ISSUE THREAD

**Issue by libressence** [SocketCluster/socketcluster#307]
Hello,
i try to recover object data after a restart. Someone know how to do that ?
May be a script exemple ?

Many thank !

**Comment by libressence** [comment]
documentation of socketCluster is good but very poorly done

**Comment by jondubois** [comment]
@libressence Thanks for the feedback. Do you mean; the documentation exists but it's hard to find?

You need to be more specific with your questions. What do you mean by "recover your data"? Is it in your database? Inside Redis? Inside your workers? Inside your brokers?

**Comment by libressence** [comment]
Thank for your response ! I use a object inside worker (appManager), i use this for play with user, context and the logic of server-side. It's just un object for playing with multiple class make by myself.

The problem is when socketcluster restart after file change i loose my object (a new object is created in worker.js, new appManager()).

My strategy is i want to save some data who are inside my appManager before socketCluster restart for finding them afer restart.

Is it possible or not ? Thank jondubois (french?) :)

Sorry for my english...

**Comment by libressence** [comment]
i mean is complicated to use this documentation because there are not a lot of example. Like scripts. I try some methods in worker but they don't work. I know it's because i am wrong but impossible to know why...

**Comment by jondubois** [comment]
@libressence Data in your workers are in memory and only temporary. If you need to persist your data to disk, you will need to store it in a database instead.

SC is just for sending messages in real-time, not for storing stuff.

**Comment by libressence** [comment]
ok, thanks
