### ISSUE TITLE
Accessing socket.setAuthToken through module

### ISSUE THREAD

**Issue by LukeXF** [SocketCluster/socketcluster#308]
I'm trying to move my code out of the worker file, into multiple files to make working on a project with a team easier, and to making the code more maintainable. How can I access socket through a module?

My worker file:

```
var account = require('./classes/account');
// some more code

scServer.on('connection', function (socket) {
    socket.on('account/loginTest', account.login);
});
```

my clases/account.js file:

```
module.exports = {
    login(credentials, respond) {
        // some db code here
        respond(null, userRow);
        // how can I use setAuthToken correctly using this way?
        this.setAuthToken({email: credentials.email, channels: userRow.channels});
        // originally it was
        socket.setAuthToken({email: credentials.email, channels: userRow.channels});
    }
};
```

**Comment by LukeXF** [comment]
As a work around I'm currently doing:
```
socket.on('account/loginTest2', function (credentials, respond) {
    account.login(credentials, respond, socket);
});
``

But this is messy and I'm sure it can be done more efficiently. Any suggestions?

**Comment by frank-dspeed** [comment]
@LukeXF Your doing it 100% right

**Comment by frank-dspeed** [comment]
One Alternate method that is also use able but makes no sense in your case would be coding ES6 class account with a constructor that takes socket and then you do new Account(socket).login(credentials,response)

**Comment by LukeXF** [comment]
Thanks Frank, going to close this issue now since my problem is solved
