### ISSUE TITLE
Ratelimiting

### ISSUE THREAD

**Issue by zmikolaj** [SocketCluster/socketcluster#309]
Hello,
how i can make limit request rate to express.js to make it works on all cpus?

**Comment by jondubois** [comment]
@trzyrazyzero You should do the rate-limitting per-worker/CPU.
If a specific IP address exceeds the maximum number of messages or connections to a specific worker, you can block the IP on that worker and log it in a database/datastore somewhere... Then if you notice that the same IP is being blocked on multiple workers, then you can assume that they are malicious and you can ban them (you can keep a blacklist in the datastore somewhere) then in the future you can block them straight away if they try to connect from any worker... There are a lot of strategies though.

**Comment by trzyrazyzero** [comment]
@jondubois its good idea to use express midleware to use redis to rate limite user? so it will work on all workers?

**Comment by trzyrazyzero** [comment]
Im using express-throttle with redis support. And if someone spam request like this https://scr.hu/6JMnnm 10+ request in one seconds, like two or three request went through, but it should rate limitting 1 request per 3 seconds.

**Comment by jondubois** [comment]
@zmikolaj It depends on what kind of rate limiting you want to do. You can use SocketCluster middleware to do this for different kinds of operations (e.g. MIDDLEWARE_SUBSCRIBE, MIDDLEWARE_PUBLISH, MIDDLEWARE_EMIT...) or you can apply a rate limit based on the number of connections coming from a specific IP address.

I don't know about any general purpose modules/plugins that are available for SocketCluster at the moment but it should be relatively easy to implement. If you do implement a general-purpose module to do this and want to share with the rest of the community, please feel free to share it.
