### ISSUE TITLE
Can't get error code (Gets hydrate error instead)

### ISSUE THREAD

**Issue by LukeXF** [SocketCluster/socketcluster#310]
When I return an error on the server, the client throws a hydrateError rather then the error code?

- Server respond with:
`respond(151, 'example error.');`

- Client receives:
```
app.js:119 Error
    at Object.module.exports.hydrateError (socketcluster.js:389)
    at SCTransport._onMessage (socketcluster.js:1877)
    at WebSocket.wsSocket.onmessage (socketcluster.js:1743) "example error."
```
How can I get the error code rather then an error stack?

**Comment by jondubois** [comment]
@LukeXF You should send back a proper Error object instead of a string. Strings don't have error codes.

So:

```
socket.on('ping', function (data, res) {
  // ...
  var err = new Error('Example error');
  err.name = 'CustomError';
  // Preferably, use error codes in the range 4100 to 4500 - The WebSocket
  // protocol and SC leave this range open for custom errors.
  // You don't necessarily need to use error codes though, you can use err.name too.
  // You can add custom properties to your error object and they will be available on the front end.
  // Note that the err.stack property will not get passed to the front end for security reasons.

  err.code = 4123;
  respond(err);
});
```

The documentation on the website is confusing because it encourages sending strings (which is possible but not ideal) - Feel free to leave this issue open for now; that way I will fix the documentation.

**Comment by jondubois** [comment]
Ok, I updated the docs: http://socketcluster.io/#!/docs/handling-failure

**Comment by LukeXF** [comment]
Thanks once again, documentation is less confusing now!
