### ISSUE TITLE
[ERROR] console - (node:37) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 S5c:f8:de:21:39:12_100032 listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by xuejipeng** [SocketCluster/socketcluster#313]
I get some error  like this
[ERROR] console - (node:37) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 S5c:f8:de:21:39:12_100032 listeners added. Use emitter.setMaxListeners() to increase limit
what can i do

**Comment by jondubois** [comment]
@ArmorHerO Are you adding event listeners somewhere in your own code? This can happen if you attach event handlers multiple times with `socket.on(...)` or similar...
