### ISSUE TITLE
Lots of processes

### ISSUE THREAD

**Issue by happilymarrieddad** [SocketCluster/socketcluster#317]
Is this normal? That seems like a lot of workercluster pid's. @jondubois 
Thanks!

![selection_338](https://user-images.githubusercontent.com/6416323/29087304-b647dd50-7c32-11e7-8ce0-4f987fdd2f6b.png)
![selection_339](https://user-images.githubusercontent.com/6416323/29087325-d17c248c-7c32-11e7-992e-78386c95c37d.png)
![selection_340](https://user-images.githubusercontent.com/6416323/29087350-df2a2a3e-7c32-11e7-8eda-2680866c700f.png)

**Comment by jondubois** [comment]
@happilymarrieddad I can't reproduce this. Could it be related to your specific setup; something is preventing your workerCluster process from shutting down properly?

Child processes in Node.js are terminated when the parent is terminated. workerCluster process should automatically be terminated when your master process stops unless something else is happening in the background. I haven't had any issues with PM2. What's your version of Node.js and SocketCluster?

**Comment by happilymarrieddad** [comment]
PM2 - 2.4.3
SC - 6.7.1
SCClient - 6.3.0

I use ```pm2 start gulp --name=fusion``` (I know... this app specifically is REALLY old...) and then I use ```pm2 restart fusion``` occasionally but other than that I don't really touch the app.

**Comment by happilymarrieddad** [comment]
I don't write apps like this anymore... it was my first attempt at a large SC app.

**Comment by happilymarrieddad** [comment]
I know this has nothing to do with this issue but is there a way to not output the initial startup logs from SC? I want to write my own logging engine and use SC events and process emits to manage what's going on.

**Comment by jondubois** [comment]
@happilymarrieddad What's your Node.js version?

**Comment by happilymarrieddad** [comment]
8.2.1

**Comment by happilymarrieddad** [comment]
I wonder if this has something to do with my startup script. I'm running pm2 startup which will start SC if/when the server crashes or gets restarted.

**Comment by jondubois** [comment]
@happilymarrieddad Let me know if you can find the cause because I can't reproduce it. I'm also on Ubuntu, Node.js `v8.0.0`, PM2 `v2.6.1` and SC `6.7.1` and I haven't seen this issue before and cannot reproduce.

**Comment by happilymarrieddad** [comment]
Ok, I don't know what was causing this... I just restarted the server and it's not happening again... really weird. I'm going to close this.
