### ISSUE TITLE
authToken via HTTPS not getting picked up by client.

### ISSUE THREAD

**Issue by Panoplos** [SocketCluster/socketcluster#318]
I am having an issue with getting auth to work with server generated tokens. I have setup passport on the server that is interfaced via https. At the end of the OAuth2 process, a JWT token is generated and sent back to the client, which stores it in `localStorage.socketCluster.authToken` and changes a state in a Redux store that kicks off a GraphQL query over SC. (Note that before auth, there are GraphQL queries happening that do not require authentication.) Other comments and the documenation mention that setting the `authToken` into `localStorage` is all that is required for SC to use it for authenticating via the default engine, but even after setting this my requests to the server do not include the `authToken` server side and the socket is not "authenticated".

Client snippet for `socketCluster.connect()`.

```es6
/* @flow */
import socketCluster from 'socketcluster-client'

export default (options) => {
  return {
    query: (request) => {
      const socket = socketCluster.connect(options)
      return new Promise((resolve, reject) => {
        socket.emit('graphql', request, (error, data) => {
          if (error) reject(error)
          resolve(data)
        })
      })
    }
  }
}
```
And the server side:

```es6
import { execute } from 'graphql';
import rootSchema from 'server/graphql/rootSchema'

export default async (exchange, socket, debug) => {
  const schema = await rootSchema()
  return async (data, callback) => {
    debug.log(`Handling a graphql query or mutation from socket [${socket.id}]`)
    const { query, variables } = data;
    const authToken = socket.authToken
    const context = {
      authToken,
      exchange,
      socket
    }
    // response = {errors, data}
    const result = await execute(schema, query, {}, context, variables)
    if (result.errors) {
      debug.error('DEBUG GraphQL Error:', result.errors)
    }
    callback(null, result)
  }
}
```

Again, server side, `socket.authToken` is always `null`.

Note also that I am indeed using the same secret in `SocketCluster(options)` as is used when creating the `authToken`.

**Comment by jondubois** [comment]
@Panoplos That is for HTTP-based authentication. It sounds like your socket object is already connected and making GraphQL requests for public data; in this case, because your socket is already connected, simply setting the `localStorage.socketCluster.authToken` is not enough; the SC client doesn't watch for changes in localStorage so if the socket is already connected, you need to use socket-based authentication; the means you have to explicitly pass the signed/encoded JWT token to `socket.authenticate(myEncodedJWT)` on the existing socket.

**Comment by jondubois** [comment]
You could also just watch the localStorage yourself by doing something like this (for example):

```
        window.addEventListener('storage', function (e) {
          // In case the user logged in from a different tab
          // socket.options.authTokenName is 'socketCluster.authToken' by default
          if (e.key == socket.options.authTokenName) {
            if (self.isAuthenticated) {
              if (!e.newValue) {
                self.isAuthenticated = false;
              }
            } else if (e.newValue) {
              socket.authenticate(e.newValue, function (err, authStatus) {
                // ...
              });
            }
          }
        });
```

**Comment by jondubois** [comment]
Thanks for pointing out this difficulty. I will see if we can bring that logic into the next version of socketcluster-client so that it watches the localStorage and authenticates automatically (maybe with an option to enable/disable it) - But for now you have to do it yourself.

**Comment by Panoplos** [comment]
Yes, I got this working a little after posting with the following code:

```es6
/* @flow */
import socketCluster from 'socketcluster-client'

export default (options) => {
  return {
    query: (request) => {
      const socket = socketCluster.connect(options)
      return new Promise((resolve, reject) => {
        if (!!localStorage.getItem('socketCluster.authToken') && socket.authState === socket.UNAUTHENTICATED) {
          console.log(`>>> sockerCluster.connect() => authenticating socket...`)
          socket.authenticate(localStorage.getItem('socketCluster.authToken'), (error, status) => {
            if (error) reject(error)
          })
        }
        while (!!localStorage.getItem('socketCluster.authToken') && socket.authState === socket.UNAUTHENTICATED) {
          setTimeout(() => {}, 100)
        }
        socket.emit('graphql', request, (error, data) => {
          if (error) reject(error)
          resolve(data)
        })
      })
    }
  }
}
```
Can you see if there are any corner cases this would hang on?
