### ISSUE TITLE
Inform client of invalid events

### ISSUE THREAD

**Issue by FallingSnow** [SocketCluster/socketcluster#319]
Is there a way to respond to the client when the socket emits an event that isn't picked up by an event listener? That way you can inform the client rather than them just having a timeout. For example:

Server:
```javascript
socket.on('test', (data, respond) => {
    respond(null, 'success');
});
socket.on('unansweredMessage', (respond) => {
    respond(new Error('Unknown event request.'));
});
```
Client:
```javascript
socket.emit('test2', {}, (err) => {
    console.log(err); // ERROR: Unknown event request.
});
```

**Comment by sacOO7** [comment]
No there is not a way to inform a client if it is not received by server. Timeout is the only thing you can do to check if request is received and acknowledged corresponding ack is received or not.

**Comment by FallingSnow** [comment]
That's unfortunate. Thanks for the response anyway.

**Comment by jondubois** [comment]
@FallingSnow do you mean a default catch-all event (so the server receives an event which has no matching listeners attached)?
If so, it's not supported at the moment but feel free to share more details about your use case and why you think it might be useful and we can consider it.

**Comment by FallingSnow** [comment]
I intend to write a websocket api for a service I'm developing. The ability to notify clients when they have made an unknown request would not only help with my development but also developers that will use that api in the future.

My primary use case is for requests for events that require authentication. For security reasons I don't attach certain event listeners to a socket until it has been authenticated. If there was an api to catch unhandled events I could compare the event against my list of handlers for authorized events and notify clients that they need to authenticate before calling this event or that this event doesn't exist at all.

Lastly I think it would add a better user experience. A timeout error suggests that any number of errors could have occurred between the client and the server (when I think timeout I think connection loss personally). With a catch-all you can provide the client with a more specific error.

Rant over. Thanks.
