### ISSUE TITLE
How to use with Koa?

### ISSUE THREAD

**Issue by nardeas** [SocketCluster/socketcluster#320]
I'm trying to use SocketCluster with KoaJS. I got the impression from [this thread](https://github.com/SocketCluster/socketcluster/issues/10) that it should be supported. However when I pass the Koa app instance in `worker.js` to the httpServer instance like this:

```javascript
module.exports.run = (worker) => {
  const app = new koa();

  // The following are defined by socket cluster
  const httpServer = worker.httpServer;
  const scServer = worker.scServer;

  httpServer.on('request', app);
...
```

I get the following error:

```
1503047601567 - Origin: Worker (PID 18944)
   [Error] TypeError: "listener" argument must be a function
    at _addListener (events.js:238:11)
    at Server.addListener (events.js:298:10)
    at Object.module.exports.run (/path/to/project/src/worker.js:32:14)
    at SCWorker.start (/path/to/project/node_modules/socketcluster/lib/scworker.js:270:26)
    at SCWorker.<anonymous> (/path/to/project/node_modules/socketcluster/lib/workercluster.js:213:16)
    at emitNone (events.js:105:13)
    at SCWorker.emit (events.js:207:7)
    at SCServer.<anonymous> (/path/to/project/node_modules/socketcluster/lib/scworker.js:184:10)
    at emitNone (events.js:105:13)
    at SCServer.emit (events.js:207:7)
```

I couldn't find any documentation on how to use SC with Koa. Help would be much appreciated!

**Comment by jondubois** [comment]
@nardeas Yes, that is what is recommended by Koa here: https://github.com/koajs/koa/blob/master/docs/api/index.md#applisten

The `app.callback()` argument passed to `http.createServer(app.callback())` is the handler for the internal 'request' event so doing what you did above is equivalent.

I think that your approach is the best way for Koa.

Note that SC now also lets you create the HTTP server yourself but you need to put it in a separate file/module which exports a `createServer(protocolOptions)` function (which returns a Node.js-compatible HTTP server). You would need to tell SC about this custom module using the `httpServerModule` option here https://socketcluster.io/#!/docs/api-socketcluster - Then SC will use that function to create its servers internally; note that this is a much more advanced use case and probably not the best for Koa.

**Comment by nardeas** [comment]
Thanks! I think since Koa is also so popular these days it would be beneficial to include & document a Koa example somewhere where it would be easily accessible for SC users.

I could do a writeup but where do you think would be best to put it?

**Comment by jondubois** [comment]
@nardeas A writeup would be great! If you write it on medium and send me the link, I could put it on the website somewhere.

**Comment by nardeas** [comment]
I did a writeup here https://medium.com/@nardeas/socketcluster-with-koa-ff760c402588

**Comment by nardeas** [comment]
Feel free to comment and improve, a link from the website would be great :-)

**Comment by jondubois** [comment]
@nardeas Nice stuff :)
