### ISSUE TITLE
log4js cluster logging

### ISSUE THREAD

**Issue by Nicholi** [SocketCluster/socketcluster#321]
The module [log4js-node](https://github.com/nomiddlename/log4js-node) has a feature for handling all logging within a `cluster`, however it requires that the master cluster process (and the child) both run `log4js.configure()`.

However `workercluster.js` is not forked via cluster, it uses child_process. All we would really need is a a mechanism similar to initController, except runs on the workercluster itself. So maybe a new initWorkerClusterController? I could provide the pull request.

**Comment by jondubois** [comment]
@Nicholi Your solution sounds fine, feel free to make a PR.
