### ISSUE TITLE
Upgrade version numbers for scc-broker and scc-state

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#323]
Use the latest from DockerHub. See scc-broker-deployment.yaml and scc-state-deployment.yaml

**Comment by happilymarrieddad** [comment]
+1

**Comment by toredash** [comment]
Hi Jonathan,

I made three PRs to upgrade scc-broker and scc-state:
https://github.com/SocketCluster/scc-state/pull/2
https://github.com/SocketCluster/scc-broker/pull/1
https://github.com/SocketCluster/socketcluster/pull/325

Also bumbed npm versions of socketcluster* and upgraded node from v6 to v8 as the base image for the Dockerfiles

**Comment by toredash** [comment]
Added two PRs to update node to use LTS in Dockerfile:
https://github.com/SocketCluster/scc-state/pull/4
https://github.com/SocketCluster/scc-broker/pull/3

**Comment by jondubois** [comment]
Done.
