### ISSUE TITLE
Batch subscribe

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#326]
Consider adding batch subscribe so that clients can subscribe to multiple channels with a single WebSocket message. This will also need to be supported in the JavaScript client.

**Comment by happilymarrieddad** [comment]
Are you going to return the channels as an array? How would you attach watchers to them? Thanks!

**Comment by jondubois** [comment]
@happilymarrieddad It won't affect the API, only the protocol.

**Comment by jondubois** [comment]
*EDIT* It might not affect the API necessarily. May be only protocol. Something to think about.

**Comment by jondubois** [comment]
Done since v8.0.0.

**Comment by ansubur** [comment]
any reference for "how to do batch subscribe"?
Is it like scClient.subscribe('channel1,channel2,channel3');
