### ISSUE TITLE
Issues when connecting between server with SSL

### ISSUE THREAD

**Issue by KCypher13** [SocketCluster/socketcluster#327]
Hello everyone,

I'm trying to connect a nodejs server to another nodejs server with socketcluster.
It work perfectly when I'm using regular WS but when I try with SSL I got the error "Socket hung up" at connexion.
But I don't have any issues to connect to the server from a browser.
I've tried with self signed and certified certificate and the result is the same.

I'm using socketcluster 5.14 and socketcluster-client 5.5.2

Any idea ?

Thanks.

**Comment by jondubois** [comment]
@KCypher13 I'm closing this, please reopen this if you're still having the issue.
