### ISSUE TITLE
Worker.js : socket.on 'message' event is not triggered

### ISSUE THREAD

**Issue by PawanWagh** [SocketCluster/socketcluster#328]
Below is some default snippets from worker.js on server. Whenever i publish data on a channel i need to do some application specific processing on received data but nothing is received in `socket.on('message')` event. But, all clients subscribed to that channel are receiving the published data.

```
        socket.exchange.publish('welcome',"hi there!!",err => {
          if (err) {
                console.log("cant welcome" + err);
            } else {
                console.log("Greeted!");
            }
        });
        socket.on('sampleClientEvent',data => {
            count++;
            console.log('Handled sampleClientEvent', data);
            scServer.exchange.publish('sample', count);
        });
        socket.on('message', data => {
            console.log("raw message: " + data);
            /* some application specific processing */
        });
```

Client side code
```
const options = { 
	hostname: appConfig.host,
	port: appConfig.port 
};
const socket = socketCluster.connect(options);

socket.on('connect', () => {
	console.log('socket connected to the server');
});

socket.on('error', err => {
	console.log('socket connection error:' + err );
});

const generalChannel = socket.subscribe('general');
socket.watch('general' , data => { 
        msgReceived(data);
});
generalChannel.publish('hello from general');
```

**Comment by jondubois** [comment]
@PawanWagh It works for me. Note that only inbound messages (client socket -> server socket) will trigger the 'message' event - Not outbound.

**Comment by PawanWagh** [comment]
@jondubois First of all thanks for such a great library.
This same configuration works on all different deployments like test server,alpha server but don't why not working on dev deployment server. Is it something environment specific ?

**Comment by jondubois** [comment]
@PawanWagh No, the environment should make no difference. Maybe there is something in your code which is different? Lots of people use this functionality.

**Comment by PawanWagh** [comment]
@jondubois Which one should you prefer to use, 
1. SCChannel Object
2. SCSocket Object

**Comment by PawanWagh** [comment]
@jondubois I have re-checked the code in all deployments & nothing is different. As a note this code was functional uptill yesterday but don't know something went off & it suddenly stopped working.

**Comment by jondubois** [comment]
@PawanWagh This should make no difference. Note that calling `socket.exchange.publish(...)` will NOT trigger the 'message' event on the socket becuause that publish is internal (not inbound). Only publish from external clients will trigger the 'message' event.
