### ISSUE TITLE
Upgrade scc-state and scc-broker to SC v9

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#330]
SC v8 introduces client subscription batching which should improve the efficiency of scc-state and scc-broker.

**Comment by happilymarrieddad** [comment]
+1 Alright!!!

**Comment by jondubois** [comment]
Upgraded scc-broker to v9.

**Comment by happilymarrieddad** [comment]
@jondubois thanks so much man. Now I can update our broker/state servers.
