### ISSUE TITLE
Add support of ES6 modules and --experimental-modules flag

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#332]
See appDir (require.main.filename) socketcluster/index.js#L72

**Comment by mauritslamers** [comment]
A more detailed description of the issue at hand:

In Node v8.6.1 it is possible to start using ES6 modules in NodeJS. Because of the lack of a dynamic loader that works (the proposed `import()` loader is available in V8 through --harmony_dynamic_import but not yet implemented on the NodeJS side) it causes all kinds of problems with SC versions up to and including 8.0.2.
NodeJS currently requires the entry point to be an .mjs file (or ES6 Module file) in order to switch to ES6 module mode. It is possible to use the ES6 `import` statement to load CommonJS modules, but their environment is a bit different from a non ES6 Module entry point.
One of the key differences is the lack of `require.main` entry which SC uses to determine the root path of the SC project.
Additionally, there are some problems regarding `options.environment` which doesn't seem to get passed on properly.

It is possible to rewrite the boilerplate server.js and worker.js in ES6 module form and rename them to .mjs. However SC uses require to load the worker.js file and this is not allowed for ES6 modules.

This means that currently it is not possible to use code written using ES6 Module form to be used directly in SC (unless transpiled).

**Comment by mauritslamers** [comment]
Set of rudimentary changes to socketcluster to allow workers to run as ES6 modules. 
https://gist.github.com/mauritslamers/1e5e24207e389dd00373b57b1f0ce359

**Comment by jondubois** [comment]
@mauritslamers Nice looks good! I'll test it out.
I did something similar for the broker controller but I used the `extends` keyword and allowed the developer override the `run()` method with their own https://github.com/SocketCluster/sc-broker/blob/class-based-controllers/test/stubs/broker-controller-stub.mjs#L8-L9

I see you've used a `SCWorker.setup(...)` approach https://gist.github.com/mauritslamers/1e5e24207e389dd00373b57b1f0ce359#file-worker-mjs-L19-L20 -
 Can you think of any problems with the `extends` approach? I like it a bit more because it reminds me of the Runnable interface which Java uses for running custom code inside threads (which is essentially what we're doing here except using processes instead of threads). http://www.java2novice.com/java_thread_examples/implementing_runnable/

**Comment by jondubois** [comment]
@mauritslamers I created a new feature branch for this change on this repo called `class-based-controllers` https://github.com/SocketCluster/socketcluster/tree/class-based-controllers. If you want your contribution to show up on the GitHub repo, you can do a pull request against that branch. I'll have to do a bit of tweaking later to finalise this feature before we can merge it into master.

**Comment by mauritslamers** [comment]
There are a few issues with the `extends` approach. 
- it pretends to be class based, which in essence it is not. The `class` and `extends` keywords are syntactical sugar over the prototypal inheritance
- `extends` creates a new constructor + prototype. It doesn't create an instance
- As described in the comments in the gist: To keep the option of creating a new SCWorker instance you need a reference to the class somehow. When you extend SCWorker using `extends` you get back a reference to a new constructor + prototype, which you still need to feed to the incoming worker incoming message handler.

**Comment by jondubois** [comment]
>> it pretends to be class based, which in essence it is not. The class and extends keywords are syntactical sugar over the prototypal inheritance

True, but maybe this syntactic sugar doesn't hurt in this case? I see an increasing number of projects using classes now.

>> extends creates a new constructor + prototype. It doesn't create an instance

In that case we can leave the responsibility of instantiating the SCWorker (or SCBroker) to the developer; then the developer can even delay the instantiation if that is what they want and the rest of SC would just wait for it (example for the broker):

https://github.com/SocketCluster/sc-broker/blob/class-based-controllers/test/stubs/broker-controller-stub.mjs#L77

It does mean that the developer will need to add one line of extra boilerplate logic (which is a negative) but on the plus side I'm thinking that maybe the extra flexibility is worth it.

We can make the underlying SCWorker class a singleton if necessary and throw an error if the developer tries to instantiate it twice (or something like that).

I understand your point though that maybe instantiation doesn't feel right at a conceptual level. I'll think about this more.

>> As described in the comments in the gist: To keep the option of creating a new SCWorker instance you need a reference to the class somehow...

Ok. I'll look through your code and see if there are some small adjustments that can be made to solve this problem (to see if it's even possible). I was able to get it to work with the broker controller but it might be different in this case.

**Comment by mauritslamers** [comment]
In a way I don't see the point of adding the extra boilerplate code of instantiation when you can achieve the same by having the developer call a function which does both extending and instantiation by means of an object literal. So, in a way you could even merge these two approaches and just have something like:
```
new SCWorker({ 
  run() { 
    // attach handlers here.
    this.on('masterMessage', (data, respond) => {
    // etc
    })
  }
```

**Comment by jondubois** [comment]
@mauritslamers I think that functionally it's perfect.

But it's a big change and it should affect all SC-based logic in the future for the rest of eternity. It's not just about functionality and correctness; there is also a convention (aesthetic) aspect to it.

Developers are attached to conventions; I think that's why they introduced classes to JavaScript (ECMAScript people had to give up eventually); developers just couldn't adopt to the prototype approach fully. It's ridiculous but it's reality.

So in terms of functionality, your current approach is a huge improvement (it does everything we need) - but in terms of following existing programming conventions I think we should evaluate it further. Are there any other frameworks using a similar pattern?

I will consult with some existing SC users to see what they think.

**Comment by jondubois** [comment]
I've raised a proposal for people to vote on https://github.com/SocketCluster/socketcluster/issues/333
