### ISSUE TITLE
RFC major release 9.0 - New entry point for controller logic

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#333]
See this issue for some background: https://github.com/SocketCluster/socketcluster/issues/332

Proposal for new entry point for controllers (e.g. Workers and Brokers).

Node.js is currently rolling out ES6 modules (though it's currently still behind an `--experimental-modules` flag in Node.js v8.6.1+); this allows developers to import ES6 modules from inside Node.js using the `import` statement (as an alternative to `require`). See https://medium.com/dailyjs/es6-modules-node-js-and-the-michael-jackson-solution-828dc244b8b

Currently, ES6 modules are not supported by SC.

In theory, we could wait for Node.js to implement 'dynamic import' (https://github.com/tc39/proposal-dynamic-import); then SC could support ES6 modules without requiring any code changes to the backend developer API; but because Node.js is in
the middle of this transition, this gives us the opportunity to revise the current entry point for SC controllers (workers and brokers).

Although this would be a breaking change, migration to the new format should be straightforward and low risk.

The current entry point for worker processes (worker.js) looks like this:

```
// SocketCluster decides when the run() function is invoked.

module.exports.run = function (worker) {
    // Custom worker logic goes here.

    worker.scServer.on('connection', (socket) => {
        // Handle the new connection.
    })
};
```

Disadvantages of the current approach:
- Doesn't work with the upcoming Node.js ES6 module import feature (at least until we have dynamic import).
- Developer can't decide when or how the worker is instantiated; SC decides this.
- This approach is quite unique to SC and doesn't follow any major known conventions (though it was loosely inspired by Java threads which have a `run` function as entry point).

The proposed alternatives will affect some of the boilerplate logic in worker.js. The approaches which are currently being considered are:

**1. Function-based approach to instantiate the controller.**
```
let SCWorker = require('socketcluster').SCWorker;

// The worker instance is created here.
SCWorker.create({
  run () {
    // Custom worker logic goes here.
    // You can reference to the worker in here with 'this'.

    this.scServer.on('connection', (socket) => {
        // Handle the new connection.
    });
  }
});
```

OR

**2. This is a variation of the approach above using the 'new' keyword instead of 'create'.**
```
let SCWorker = require('socketcluster').SCWorker;

new SCWorker({
  run() {
    // Custom worker logic goes here.
    // You can reference to the worker in here with 'this'.

    this.scServer.on('connection', (socket) => {
        // Handle the new connection.
    });
  }
})
```

OR

**3. This class-based approach is closer to front-end frameworks like React.  It's also similar to how threads are used in Java (via the Runnable interface).**
```
let SCWorker = require('socketcluster').SCWorker;

class WorkerController extends SCWorker {
  run() {
    // Custom worker logic goes here.
    // You can reference to the worker in here with 'this'.

    this.scServer.on('connection', (socket) => {
        // Handle the new connection.
    });
  }
}

new WorkerController();
```

All the approaches above work similarly; the question is mostly about syntax and convention - Which one makes the most sense to developers?
Which one is more future-proof?

Once this change is made, we should assume this is how it's going to stay for the foreseeable future.

The benefits of any of the three proposed approaches above are that developers will be able to:
- `import` ES6 modules from inside the worker controller file (worker.js) as an alternative to the current `require()` approach.
- Delay when and how the worker becomes instantiated (since it is now the developer's responsibility as part of the boilerplate).
- Provide/override functions in the worker to modify default behaviour. For example, we could allow the developer to provide or override a getHTTPServer() method which will allow developers to create their own HTTP server finstead of the basic Node.js one. This might help with integrating some backend frameworks with SC.

Please vote for your favorite approach in the comments below.

**Comment by gustojs** [comment]
Thanks for letting us know about that and asking for opinions!

I fully support this change, it would be a very welcomed feature and the breaking changes seem pretty trivial.

**Comment by jondubois** [comment]
@gustojs Yes you can vote for all of them if you don't have a preference; it's good to know. I also think it's close. You can also suggest alternatives if you have other ideas.

**Comment by happilymarrieddad** [comment]
I would love this!!! Currently, I have a worker class that's a wrapper and this would make things so much easier. +1!!!!

**Comment by happilymarrieddad** [comment]
Oh, I use the static create(options = {}) { return new Worker(options) } so I would rather use create instead of new.

**Comment by jondubois** [comment]
This has now been released to npm as `socketcluster` version `9.0.3` - It's also been pushed to DockerHub.

@mauritslamers The entry point supports all the formats that were put forward since they all ended up being compatible with almost no added complexity. I did not use any classes behind the scenes except for in the controller scripts themselves as defaults (the user is free to change to whatever approach they prefer).

**Comment by wmertens** [comment]
I was using this code to run a single-process `socketcluster` in development:

```js
import socketClusterServer from 'socketcluster-server'
import http from 'http'
import {run} from './worker'

const httpServer = http.createServer()
const scServer = socketClusterServer.attach(httpServer)

run({httpServer, scServer})
httpServer.listen(80)
```

(transpiled of course)

How should I adjust this so it works again?

**Comment by happilymarrieddad** [comment]
@jondubois Hey man, I moved everything over and it makes everything so much easier. Thanks man!! Awesome change!!!
