### ISSUE TITLE
 NoMatchingTargetError: Could not find a matching target server

### ISSUE THREAD

**Issue by ArmorHerO** [SocketCluster/socketcluster#336]
i use the scc on the real server ,no docker i get a error like this:
 NoMatchingTargetError: Could not find a matching target server for the S5c:f8:21:de:55:66_100032_5c:f8:21:de:55:66 channel - The server may have gone down recently.
What will cause this problem?

**Comment by jondubois** [comment]
@ArmorHerO It usually means that a backend scc-broker went down and is no longer reachable by the regular socketcluster instance. If you have multiple scc-broker instances, then the cluster will switch to other available instances.

**Comment by ArmorHerO** [comment]
Oh oh so thank you
