### ISSUE TITLE
Missing process.env on workers

### ISSUE THREAD

**Issue by thomasvargiu** [SocketCluster/socketcluster#339]
With ^8.0 version I was able to retrieve environment variables with `process.env`, with version 9.0.3 the only setted env variable is `workerInitOptions`.

I think the probles is in `index.js` and `scworkercluster.js` where two parts should be something like this:

`index.js`:
```js
execOptions.env = {
    workerInitOptions: JSON.stringify(workerOpts),
    ...process.env
  };
```

`scworkercluster.js`:
```js
var worker = cluster.fork({
      workerInitOptions: JSON.stringify(workerInitOptions),
      ...process.env
    });
```

**Comment by jondubois** [comment]
@thomasvargiu Thanks for raising this issue. It has now been fixed in `socketcluster` `v9.0.8`.
