### ISSUE TITLE
ES6 imports not working in broker.js or worker.js.

### ISSUE THREAD

**Issue by Panoplos** [SocketCluster/socketcluster#340]
After upgrading to the latest version of SC, the server now barfs on `import` statements in worker.js (and broker.js since I have to import `SCBroker`), even though I am using `babel-register`. As I am using Koa for user auth logic, I have quite a few imports in the worker.js module. Any way to fix this without changing everything to `require`?

**Comment by Panoplos** [comment]
In fact, this is a big problem as many of my local imports have dependencies as well... Also, I am using `module-resolver` babel plugin to keep imports clean, i.e. `import something from 'server/something'` as opposed to `var something = require('../../path/to/server/something')`.

**Comment by jondubois** [comment]
@Panoplos It looks like babel-register ignores `node_modules` by default but you can set `ignore` to `false`. https://www.npmjs.com/package/babel-register#ignores-node_modules-by-default

If you use a transpiler like babel or coffeescript, you may need to rename `worker.jsx` (or whatever the extension is) to just `worker.js` and move the actual logic into an different `.jsx` file (so worker.js would just be babel-related bootstrap logic)- Then you require it from `worker.js`. Then you should be able to use import in your `.jsx` file.

If you use Node.js v8+, you can use es6 module `import` natively if you pass the `--experimental-modules` flag.

**Comment by jondubois** [comment]
With the new architecture, your worker.js file is executed directly by Node.js with nothing in-between (via `cluster.fork()`). So you should treat worker.js as if it was executed with the command `node worker.js`

**Comment by Panoplos** [comment]
Note that I approached this slightly differently in that I included `-r babel-register` on the initial command line, as it appears you guys are copying over all args to the forked process.
