### ISSUE TITLE
The term 'SCC_STATE_SERVER_HOST=127.0.0.1' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by filipwa** [SocketCluster/socketcluster#342]
Im getting the following message when running the command to start the broker, I have followed the guide but I can't figure it out. Any tips?

SCC_STATE_SERVER_HOST=127.0.0.1 : The term 'SCC_STATE_SERVER_HOST=127.0.0.1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path w
as included, verify that the path is correct and try again.
At line:1 char:1
+ SCC_STATE_SERVER_HOST='127.0.0.1' SOCKETCLUSTER_SERVER_PORT='8888' no ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SCC_STATE_SERVER_HOST=127.0.0.1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jondubois** [comment]
@filipwa Maybe specifying environment variables like this is not supported by your shell on your operating system (Windows Powershell?). You should find a different way to set environment variables.
