### ISSUE TITLE
Running into "JsonWebTokenError: invalid signature" intermittently while validating token

### ISSUE THREAD

**Issue by debadaz** [SocketCluster/socketcluster#343]
I am a newbie.
I am running into "JsonWebTokenError: invalid signature" intermittently. The token validation passes 90% of the time though, not sure why does it fails intermittently.
Please help in understand what can be the reasons of failure intermittently.

Error-

Validating token  eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTA3NTg2MTE0LCJleHAiOjE1MDc1ODk0Mjh9.MrMVPvXLFkzkZwhnjH0J2DMggwRQmJ80VurXxuUEAa4
2017-10-09 22:44:40.458 +0000 DEBUG [] [userManager] Token validation requested for: userManager:validateToken
2017-10-09 22:44:40.458 +0000 DEBUG [] [userManager] JsonWebTokenError: invalid signature - eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTA3NTg2MTE0LCJleHAiOjE1MDc1ODk0Mjh9.MrMVPvXLFkzkZwhnjH0J2DMggwRQmJ80VurXxuUEAa4

Part of the code that gets invoked -

validateToken: function validateToken(msg) {
    var logMessage;
    return new rsvp.Promise(function(resolve, reject) {
        logger.debug('Validating token ', msg.payload.token);
        deps.jwt.verify(msg.payload.token, secret, function(error, decoded) {
            if (!error) {
                var expirationTimeSeconds = attrs.expirationTimeSeconds ? attrs.expirationTimeSeconds : 360;
                if (msg.payload.expirationTimeSeconds !== undefined) {
                    logMessage = 'Token expiry time specified (seconds) : ' + msg.expirationTimeSeconds;
                    logger.debug(logMessage);
                    if (msg.payload.expirationTimeSeconds > attrs.maxTokenExpirationTimeSeconds) {
                        // You can't have a expiration time greater than the max allowed
                        logMessage = 'Token expiry time specified is more than max allowed. Capping it at ' +
                                attrs.maxTokenExpirationTimeSeconds + ' (seconds)';
                        logger.debug(logMessage);
                        expirationTimeSeconds = attrs.maxTokenExpirationTimeSeconds;
                    } else {
                        expirationTimeSeconds = msg.payload.expirationTimeSeconds;
                    }
                }
                var newToken = createToken(decoded, expirationTimeSeconds);
                logger.debug('Distributing new token with expiration time of ', expirationTimeSeconds, newToken);
                // For future requests
                attrs.expirationTimeSeconds = expirationTimeSeconds;

                var decodedValue, secToExpire = 360;
                try {
                    decodedValue = deps.jwt.decode(newToken);
                    secToExpire = Math.abs(Math.floor((new Date() - new Date(decodedValue.exp * 1000)) / 1000));
                } catch (err) {
                    var errorMessage = 'Error in decoding token ' + newToken + ' . Error message: ' + err.message;
                    logger.error(errorMessage);
                }
                resolve({
                    message: 'Successfully validated access token',
                    payload: {
                        token: newToken,
                        username: decoded.username,
                        secToExpire: secToExpire
                    }
                });
            } else if (error instanceof JWT.JsonWebTokenError || error instanceof JWT.TokenExpiredError) {
                var jwtErrorMessage = util.format('%s: %s - %s', error.name, error.message, msg.payload.token);
                logger.debug('Token validation requested for: ' + msg.originalRequest);
                logger.debug(jwtErrorMessage);
                reject(jwtErrorMessage);
            } else {
                reject(error);
            }
        });
    });
},

**Comment by jondubois** [comment]
@debadaz It could either mean that a malicious user is trying to pass fake token data which was signed with an invalid `authKey` or (more likely) it could be that your SC instance's `authKey` has changed since the token was issued and so it's no longer valid (and so the user should log in again to get a fresh JWT signed with the new `authKey`). Note that by default, if you do not provide an `authKey` option to SocketCluster (in server.js), then it will generate a random one for you; a side-effect of this is that every time you restart your SC instance; the `authKey` will be different.

Search for the `authKey` property on this page https://socketcluster.io/#!/docs/api-socketcluster for more info.

**Comment by debadaz** [comment]
@jondubois Thank you, will look into the pointers u shared !!
