### ISSUE TITLE
Not sharing session across all nodes

### ISSUE THREAD

**Issue by happilymarrieddad** [SocketCluster/socketcluster#349]
Hey @jondubois,

I can't seem to get the sessions to share across nodes. I'm using Nginx with two "applications servers" running socketcluster with 8 workers each. I also have a state and a broker server connecting them. In the emit middleware, I'm storing an object to the authToken and when a user gets routed to the other server the authToken is empty so their "session" variables are reset and they have to update their filters again. Is there a way to share authToken's between application server?

```
scServerEmit({ data,event,socket },next) {
        if (event == 'logout') return next()
        let authToken = socket.authToken || {}

       // Set some data to the authToken
       ....

       if (authToken && Object.keys(authToken).length) socket.setAuthToken(authToken)
        return next()
})

```

I'm not sure if it matters but I'm using express-session-middleware for logins and API requests. Would this interfere? If user happens to be routed to the same server they were on before by nginx then their session works just fine.

**Comment by happilymarrieddad** [comment]
I dirty fixed this by adding ip_hash; to my nginx config but all that does is force users to stay on the same server. I would like to have the ability to move them to whatever server I want without having to deal with any issues. @jondubois Is there a way to save to express sessions from inside the emit middleware instead of using SC session? That would also solve it for at least me. Thanks!

**Comment by jondubois** [comment]
@happilymarrieddad The express session plugin doesn't seem to scale out of the box because it stores the data on the server's memory by default. Maybe there is an option to make it store the session data in an external database instead?

Unless you need to store sensitive session data, then JWT is usually a much better, simpler and more scalable solution.

**Comment by happilymarrieddad** [comment]
@jondubois  
Ok, I stored the data in the DB using the express-session-middleware. Using JWT is great and I would love to do so but I wrote this app a long time ago and switching our login page would be quite complicated... Is there a way to access the express session from the middleware?

**Comment by happilymarrieddad** [comment]
... I just answered my own question... I can store and update the authtoken inside the db store... wow... I'll just do that.

**Comment by happilymarrieddad** [comment]
In case anyone else encounters this, all you have to do is update the data object in the db and it works across all systems. They can even login multiple browsers at different IP's and it works. I've been keying off the user_id that I store in the req.session object. Probably not the most performant thing to do but I need accuracy more than performance at this point. I'll do it a better way if I find a better way soon. Thanks!
