### ISSUE TITLE
update the socketcluster from ~9.2.2 to ~9.3.1

### ISSUE THREAD

**Issue by Coldzer0** [SocketCluster/socketcluster#355]
i try to use "npm update" on my server dir , but nothing happen !
and i search the documentation for any hint about updating without overwrite the code in server.js
but nothing

how could i upgrade to the newest version ?

thanks

**Comment by amin-mir** [comment]
Try `npm update socketcluster` in the directory where your `package.json` lives.

**Comment by Coldzer0** [comment]
i already did that and nothing happen but anyway i think i should build new project with the newest version and copy my code to it

cuz there's some changes in the files

and next time i'll write my code in separated files then import it inside the server & worker

**Comment by fkhateeb** [comment]
Hi Man, 
As I think  updating only the dependency modules only, you couldn't request update and to find all  of your code in worker or any other file have been editing , so  only you need to change the version  on the package.json  and npm update or remove the module dependency folder and npm install.
