### ISSUE TITLE
Events are getting published multiple times

### ISSUE THREAD

**Issue by beingshashi** [SocketCluster/socketcluster#361]
Hi,

I have implemented SocketCluster in my angular app. When It was working great and as expected.
After a few days, I just tested a case where I have logged in with the same user in multiple tabs in the same browser.
Then I have noticed that, when someone sending me messages, I am receiving it multiple times. Sometimes 3 times, sometimes 4 times etc. based on how many places I am logged in.

Same happens, If I am logged into multiple browsers within a single system or multiple systems.

Need a resolution for above kind of unusual behavior.

Thank you,

**Comment by beingshashi** [comment]
I don't know why you saying "That's expected", Maybe I am not able to convey the problem properly.
Consider the example of Facebook, it has one chat box, if I open the same FB page in multiple tabs and someone sends me a custom, Its shown only one time.

We want to have the same concept, but whats happening is in my case, I am receiving messages 4 times in each tab ( I have opened 4 tabs ).
Is there any way to convey socket cluster that it should create sessions or socket connections based on user Id and not based on tabs session?

**Comment by toredash** [comment]
Ah that explains it, I didn't understand the question then. Thats not expected AFAIK. Not sure what it can be.

**Comment by MegaGM** [comment]
@beingshashi We could continue the conversation in [Gitter](https://gitter.im/SocketCluster/socketcluster)
Then, if it's a bug, we'll post here some reports.

**Comment by amin-mir** [comment]
@beingshashi The `multiplex` option in ScClient library is true by default, which means that the browser will use the same socket for several tabs. Maybe you have written some logic which caused your client app to subscribe to a channel multiple times. Remember to unsubscribe or unwatch channels if you don't need them.

**Comment by lokielse** [comment]
It has no connection with `multiplex` option if you open multiple tabs in a browser. 

I think your problem is caused by your worker logic. 

```js
/*
 In here we handle our incoming realtime connections and listen for events.
*/
scServer.on('connection', function (socket) {

  setInterval(function () {
    scServer.exchange.publish('sample', 'sample')
  }, 1000)

})
```

As the code say, To create a timer for each connection, publish a message every 1s, That's say four browser tabs will start four timers. Each client will receive 4 times of `sample` message for there 4 timers publish it for a while.
