### ISSUE TITLE
Can't access worker.scServer during init because of async support for createHTTPServer()

### ISSUE THREAD

**Issue by specialkk** [SocketCluster/socketcluster#364]
9.3 broke my setup since I depend on being able to have access to `worker.scServer` during my run method. Because the result of calling `createHTTPServer` is wrapped in a `Promise.resolve`, the constructor for the Worker is now asynchronous which is kind of uncomfortable to work with. It introduces a race condition where `scServer` is missing during the only time when many people will touch it, which is pretty confusing.

I realize now that the Worker supports start middleware that I can use to work around this, but it would be nice if `Promise.resolve` could be avoided so that the constructor stays synchronous. At the very least (for me), `scServer` should be present before `run()` is called.

**Comment by jondubois** [comment]
@specialkk `worker.scServer` should always be available inside the `run()` method. Can you post simple code snippets to reproduce the issue?

**Comment by specialkk** [comment]
Whoops, I'm sorry, I actually can read `scServer` in during my `run()` method. However this definitely did initially break my setup since I was previously relying on the constructor being synchronous in a couple spots, but I guess I might be alone since it's been a few weeks without anyone else complaining.

It still wouldn't hurt to keep `_init()` sync if `createHTTPServer()` doesn't return a Promise though.
