### ISSUE TITLE
Clustering - 2 hosts, 4 workers on each. Need sticky session

### ISSUE THREAD

**Issue by sravia** [SocketCluster/socketcluster#365]
Can someone link me to explanation how to put multiple socketcluster servers into a cluster and scale them across multiple hosts?

I need ability to split traffic using loadbalancer ( nginx ) between 2 hosts with sticky session. Each host has 4 sc servers.

**Comment by jondubois** [comment]
@sravia You may want to read the SCC Guide https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md

**Comment by sravia** [comment]
THANK YOU! Could not find it before :)
