### ISSUE TITLE
Instance_1 was not allowed to run insecure contenet from instance_2

### ISSUE THREAD

**Issue by sravia** [SocketCluster/socketcluster#366]
I have the follow architecture:

* EC2_1_INSTANCE which has socketcluster client functionality. It is a web application with nginx listening on port :443.
* EC2_2_INSTANCE which has socketcluster server functionality ( 2 workers ). Nginx listens on port :80 and splits all traffic between :3000 and :3001.

EC2_1_INSTANCE instance is connecting to EC2_2_INSTANCE instance using the following settings:
options = {
        path: '/',
        port: 80,
        hostname: 'EC2_2_INSTANCE',
        autoConnect: true,
        secure: false,
    };

I am getting this error in browser console:
[blocked] The page at https://EC2_1_INSTANCE was not allowed to run insecure content from ws://EC2_2_INSTANCE:80/

How something like this gets fixed? Do I have to also get a second certificate for EC2_2_INSTANCE? Another domain/subdomain?

**Comment by jondubois** [comment]
If the page is served over HTTPS then the WebSocket connection from it must also be secure (wss:// instead of ws://).

The domain doesn't have to match - Often a subdomain is suitable and yes you may want to get a separate TLS/SSL certificate for the subdomain.
