### ISSUE TITLE
receive raw data from external device

### ISSUE THREAD

**Issue by yalint** [SocketCluster/socketcluster#369]
Hi guys,

I have a GPS device and I set it to send GPS data to my socketcluster server app, but I don't know how to receive that data. 

If I create a complete new nodejs project running a simple net.CreateServer I receive the GPS data,
Does scServer have an event  like scServer.on('data',function(data){})?

Thanks

**Comment by jondubois** [comment]
@yalint Are you connecting to the SocketCluster instance using a raw `WebSocket` client?
It's not too difficult to make it work but you'll need to implement the SocketCluster handshake immediately after connecting your device. You may want to read through the SocketCluster protocol guide here: https://github.com/SocketCluster/socketcluster/blob/master/socketcluster-protocol.md
