### ISSUE TITLE
How to get the count of subscribers to  a channel

### ISSUE THREAD

**Issue by fkhateeb** [SocketCluster/socketcluster#370]
Hi there,
I searched in the API and found a way to get the connected client count; but I need to get subscribers count of specific channel. 
how I can do that?!

**Comment by toredash** [comment]
On each worker you should loop through the subscribers and count, and store that in e.g. redis so you can count the total number.

**Comment by fkhateeb** [comment]
thank you,
how I can get the subscribers count in the worker, I can get the socket connected count but the subscribers I couldn't!?

**Comment by toredash** [comment]
That would be the same. You can look at each socket and see what channels it's subscribe to

**Comment by fkhateeb** [comment]
do  you mean to get the sockets `scServer.clients` then loop on them `socket.subscriptions()` so  I can know how many subscribers to the channel in this worker and store in redis to sum them up ?!

**Comment by jondubois** [comment]
@fkhateeb Sure that would be one way to do it.

**Comment by rigalpatel001** [comment]
@fkhateeb
I spent so much time finding a way to count subscribe channel users but I didn't found any. solution. Would you please provide a solution or share code with me to count subscribe channel users?

Thanks
