### ISSUE TITLE
Connecting from normal WebSocket

### ISSUE THREAD

**Issue by Hirbod** [SocketCluster/socketcluster#371]
Hi everybody,

I have socket cluster up and everything is working perfectly. I can also connect my app and the website to the socketcluster using socketcluster.js client.

But I also do have a node server which has to be connected to socketcluster. How can I achieve this? There is no nodejs client for socketcluster. I tried using WS and Socket.io-client but I can’t establish a connection.

I need to send data from the node ja Server to my socketserver but there is no way I could connect it. Any advice?

**Comment by MegaGM** [comment]
The easy way is to send the data from the external app directly to a MQTT or Redis cluster or whatever else brokers of your socketcluster app are listening to. So, you don't have to connect as a client to your SocketCluster server at all.
If the easy way doesn't work for you, feel free to join [Gitter](https://gitter.im/SocketCluster/socketcluster)

**Comment by Hirbod** [comment]
I have a redis server running, but how can socketcluster get triggered doing something if any action happened on redis? Is there kinda redis watch? I worked with MQTT long time ago using raspberry and home automation (lmao), but not sure how to listen for mqtt events inside my worker or broker js. Is there any documentation ?

**Comment by Hirbod** [comment]
Ok, if I get this right, I just need to install a Mosquitto Server inside my worker.js listening for MQTT messages. Should be easy.

**Comment by MegaGM** [comment]
Since you have redis already, you could subscribe sc-app to a channel in redis, then from external app publish to that channel the data.
But there is a better solution: https://github.com/SocketCluster/sc-redis

**Comment by Hirbod** [comment]
Sounds good, thanks @MegaGM

**Comment by amin-mir** [comment]
@Hirbod @MegaGM I don't think MQTT is needed here really. ScServers can act as message brokers. Also sc-redis is not scalable. The best approach, I think, is to use the ScClient in your node.js servers as well. So you have a message broker through which your nodes can communication with each other (pub/sub). You might want to include special secret tokens as well, so only trusted clients can do particular stuff.

**Comment by Hirbod** [comment]
@amin-mir merci, but how can I include ScClient inside node? I can’t require anything and I have to include the socketcluster.js file. Scaleabillity isn’t a big deal though at this stage (I’m only sending “signals” to the socket for initiating some stuff inside the app). But I would love to know how to use scClient inside node.

**Comment by amin-mir** [comment]
First, install socket cluster client in your node.js server:
`npm install socketcluster-client`

The rest is as simple as the code snippet below:

```javascript
const socketCluster  = require('socketcluster-client');
const scOptions = {
    hostname: 'localhost',
    port: 3000
};
const scClient = socketCluster.connect(scOptions);
// ...
```

Also, this will become handy when testing your code. Let me know if it works.

**Comment by sacOO7** [comment]
Hi @Hirbod, I think you have some wrong assumption. You can use socketcluster js client in both node and browser. That way you do not have to worry about platform you are running. It can either be browser or node environment.

**Comment by Hirbod** [comment]
Thanks everbody, I have sc-client fully working inside nodejs and I can communicate as I wish. It works flawlessly :)

Very happy now! Thanks for your help.

**Comment by happilymarrieddad** [comment]
Hey guys,

If you want, you can look through the SC-Client code and see how it works. WebSocket is used client-side by SC-Client to connect so you can just follow that if you want to connect without using SC-Client I guess. Not sure how much help that is but you can do it.

**Comment by slidenerd** [comment]
@amin-mir this node js client you have specified can only connect with another socket cluster server regardless of whether that server is on the same domain or on a different domain, what if you want to connect to a completely third party API that provides data via a websocket stream such as the GDAX API, I am assuming it wont work then

**Comment by amin-mir** [comment]
@slidenerd Yeah you are right. If you still want to connect to a third party library that uses pure websocket protocol, then you have to use pure websocket client in your SocketCluster application to connect to it. The idea is the same; only do you need to use a different client library.

**Comment by slidenerd** [comment]
So a highly related question, lets say I have 4 workers running and I have a separate file lets call it api.js that connects to an external websocket api and receives stream, I want to forward this stream data to the connected clients

1. If I include the file api.js inside the worker file, obviously it gets called 4 times which is not desirable
2. One way I can fix the issue is to use the worker id and require("api.js") only in a worker with say id 0
Is there any other way of doing this?

**Comment by IngwiePhoenix** [comment]
How about using the broker process and forwarding events through that one? You dont need to spawn too many broker processes, so you could effectively reduce those, while keeping the amount of worker processes higher.
