### ISSUE TITLE
Issue with "secure" option of connection method in socketcluster-client 

### ISSUE THREAD

**Issue by Louies89** [SocketCluster/socketcluster#372]
As per https://socketcluster.io/#!/docs/api-socketcluster-client documentation, the "secure" option of connection method is by default false, but, it seems it is by default true.

So request, either code has to modified or the documentation has to be updated.

If I am not wrong, code modification is a good choice. :)

**Comment by happilymarrieddad** [comment]
@Louies89 what are your connection parameters? Can you post your code?

**Comment by sacOO7** [comment]
I think we need to take a look into this. Which version of socketcluster server are you using right now?

**Comment by MegaGM** [comment]
Let's find where `secure` option is being set ([the line](https://github.com/SocketCluster/socketcluster-client/blob/64db0b086b518838aee4251783d3ba05a182fd13/lib/scsocketcreator.js#L61))
Then track down all the abstractions until we get VanillaJS code ([the line](https://github.com/SocketCluster/socketcluster-client/blob/64db0b086b518838aee4251783d3ba05a182fd13/lib/scsocketcreator.js#L36))
Now we can see that essentially
```js
options = {
  secure: global.location && location.protocol == 'https:'
  // .....
}
```
So, there is **no default option**. It depends. 
Unfortunately, in [the docs](https://socketcluster.io/#!/docs/api-socketcluster-client) we indeed have a simple, not entirely correct, explanation.
> secure: Boolean - Defaults to false

Someone, please, be :1st_place_medal: and correct that <3

@Louies89 what's your site protocol?

**Comment by Louies89** [comment]
Thanks all for wonderful replies...  And sorry for late reply, I didn't check my mails.
@happilymarrieddad : I just used below code:
**Newsocket = socketCluster.connect({
		hostname: 'localhost',
		port: 80})**

And in gitter sacOO7 pointed out to set secure false, after doing that, it get connected.

@sacOO7 : I am using 
**"socketcluster": "~9.1.3",
    "socketcluster-client": "~9.0.0",**

@MegaGM : I am using simple http only

And also the code can be referred from here: https://github.com/SocketCluster/socketcluster-client/issues/102

**Comment by Louies89** [comment]
Sorry to all, by mistake I clicked on `Close and comment`

**Comment by MegaGM** [comment]
@Louies89 
```js
global.location && location.protocol
```
`global` in the context is `window` in a browser. So it's 
```js
window.location.protocol
```

**Comment by Louies89** [comment]
ooh, got it. :)
The code is working fine for me now.
Thank you for the reply @MegaGM
