### ISSUE TITLE
Trigger a channel publish event from server side outside of worker.js

### ISSUE THREAD

**Issue by HoplaGeiss** [SocketCluster/socketcluster#374]
I would like to trigger a channel publish event outside of worker.js 
e.g: `scServer.exchange.publish('tenant.LDN1', {message: 'hello tenant LDN1'});` 

I have a .net backend sending data to (via signalR) to my middletier (node running socketCluster). Once I get this new data at the middletier, I am parsing it and I would like to send it to the front-end. I am not sure how to do that, as I don't know how to get an instance of `scServer` outside of worker.js

**Comment by MegaGM** [comment]
somewhat similar https://github.com/SocketCluster/socketcluster/issues/371

@HoplaGeiss tldr you can connect to your existing sc app using https://github.com/SocketCluster/client-drivers or even via external queues.

**Comment by HoplaGeiss** [comment]
Thanks!
