### ISSUE TITLE
Send message to user by socketID

### ISSUE THREAD

**Issue by Hirbod** [SocketCluster/socketcluster#375]
Hi,

I know it is possible to create a "bob-channel" for achieving what I need, but I have a public channel with ~ 200k users and I can't create 200k private channels for sending data to a specific user only.

Is there any way (I am storing the socket-id inside of redis) to use that ID for sending data from server (it's a welcome message) to that user only? Currently I am using exchange.publish, what other options do I have? Thanks!

**Comment by toredash** [comment]
If it's a welcome message couldn't you trigger an event when the user subscribes to the channel?

**Comment by Hirbod** [comment]
Yeah but the message content is specific (based on several facts). I can see if that user subscribed to the channel, but I tried to do something like this:

scServer.clients[socket.id].emit('foo', mySpecialObject); but there was no way for me to receive that answer. For now, I've ended up "subscribing' (on client) to .subscribe('private_uniqueUserId').watch().

This if working, but I don't know how much overhead this is. Actually, I would love to just listen in my already existing channel "foo".

**Comment by hardikamutech** [comment]
you can use emit method of SCSocket (Client)/SCSocket (Server), check document here for SCSocket client `https://socketcluster.io/#!/docs/api-scsocket-client` same for the SCSocket (Server) `https://socketcluster.io/#!/docs/api-scsocket-server` and find `emit` Method for example find https://socketcluster.io/#!/docs/handling-failure

**Comment by jondubois** [comment]
@Hirbod Why can't you have 200K private channels?

SC doesn't impose any hard limits on the total number of channels that you can have (or even on the rate of creation of new channels). Also the cost of each channel is negligible.

**Comment by Hirbod** [comment]
@jondubois as I don’t know the internals I thought the overhead will be much more. 

We ended up creating a hidden private channel to achieve what we want.

**Comment by Hirbod** [comment]
Thanks everybody!
