### ISSUE TITLE
Socket hung up / Worker respawn when restarting app

### ISSUE THREAD

**Issue by Hirbod** [SocketCluster/socketcluster#376]
Hi,

as soon as I close my connection inside of my app (cordova) I'll receive a socket hung up inside of my server-logs with an warning, after that, a "socket respawned" message apears.

Why does the server crash if a user disconnect from a connection?
Is this a bug? Should it behave like that?

**Comment by jondubois** [comment]
@Hirbod This is normal. It's a warning, not an error. Socket errors show up as warnings on the server.

In this case the problem is probably that the client did not close the socket connection properly and instead killed the connection abruptly. The WebSocket RFC requires that client sockets send a close control frame the server (I.e. `socket.disconnect()`) before they kill the connection.

When using SC, warnings are a normal part of day-to-day operations; they don't usually affect the user experience. it's good to be aware of them but you generally don't need to do anything about them. You can try to reduce how often they happen though.

**Comment by Hirbod** [comment]
Thank you very much for your answer. I found out, that cordova does not fire the unload event, thats the reason why "disconnectOnUnload: true," does not work, while it works inside the browser.

I though it is an error, since the log file say "worker exited 1; worker respawned". Sounds like a crash like more then a warning.

**Comment by jondubois** [comment]
If it says that the worker exited then it is an error. Do you have some other custom code in there that could be causing a fatal error (maybe as a flow-on effect to the first warning)?

**Comment by Hirbod** [comment]
```log
1519397254959 - Origin: Worker (PID 20442)
  [Warning] SocketProtocolError: Socket hung up
   at SCSocket._onSCClose (/srv/trivia/quiz/node_modules/socketcluster-server/scsocket.js:229:17)
   at WebSocket.internalOnClose (/srv/trivia/quiz/node_modules/socketcluster-server/scsocket.js:74:10)
   at process.nextTick (/srv/trivia/quiz/node_modules/uws/uws.js:445:27)
   at _combinedTickCallback (internal/process/next_tick.js:131:7)
   at process._tickCallback (internal/process/next_tick.js:180:9)
1519397254959 - Origin: Worker (PID 20442)
  [Error] UnknownError: Socket error - SocketProtocolError: Socket hung up
   at SocketCluster._convertValueToUnknownError (/srv/trivia/quiz/node_modules/socketcluster/index.js:449:13)
   at SocketCluster.emitFail (/srv/trivia/quiz/node_modules/socketcluster/index.js:460:14)
   at SocketCluster._workerErrorHandler (/srv/trivia/quiz/node_modules/socketcluster/index.js:492:8)
   at ChildProcess.workerHandler (/srv/trivia/quiz/node_modules/socketcluster/index.js:687:14)
   at emitTwo (events.js:126:13)
   at ChildProcess.emit (events.js:214:7)
   at emit (internal/child_process.js:772:12)
   at _combinedTickCallback (internal/process/next_tick.js:141:11)
   at process._tickCallback (internal/process/next_tick.js:180:9)
1519397254962 - Worker 2 exited - Exit code: 1
  >> Worker PID: 20739
1519397255229 - Worker 2 was respawned
```

This only happens when I call "window.location.reload()" inside my app (or if I change a .js file and socketcluster reloads). 

As my app listens to some special events, I need to call that reload function sometimes which will flood or kill the server when 100k users are connected)

**Comment by jondubois** [comment]
@Hirbod I cannot reproduce. Which `socketcluster` version and `socketcluster-client` version are you using?

**Comment by Hirbod** [comment]
"socketcluster": "~9.3.1",
    "socketcluster-client": "~9.0.2"

**Comment by Hirbod** [comment]
Updated to 9.3.3, problem remains the same.

**Comment by jondubois** [comment]
Can you reproduce the issue by connecting a client which is running inside Node.js somehow?

E.g. You can run a client inside Node.js with:
```
var socketCluster = require('socketcluster-client');

var options = {
  port: 8000,
  path: '/socketcluster/',
  hostname: '127.0.0.1',
  multiplex: false
};
var socket = socketCluster.connect(options);
```

For me I only get the warning but no error afterwards.

**Comment by Hirbod** [comment]
we have a node.js running, there are no issues. We also have the client inside a brower, also no issue. It only happens on a hard disconncet from my app.. :/

**Comment by Hirbod** [comment]
To give more informations. I've downloaded a copy of "socketcluster.js" into my cordova app, which is included via js.

**Comment by jondubois** [comment]
`UnknownError` means that an unrecognised error type was thrown in one of the processes.
SC should never throw this error type internally. I can reproduce the same error if I add this line inside worker.js:

```js
scServer.on('warning', (err) => {
  throw err.toString(); // Throwing a string; bad idea.
});
```

Then I open a client in the browser and I hold down the refresh key so that it keeps reloading until I see errors.

SC never throw strings as errors (it always uses Error objects) so it's more likely to be a problem with your custom application logic.

**Comment by Hirbod** [comment]
I will dig into this, but to be honest, the server/worker.js stuff was auto generated with "socketcluster create app". I did not do anything on that part, I will have a look if I can find something.

**Comment by Hirbod** [comment]
Dang... @jondubois here we go

```
...
scServer.on('connection', function (socket) {
		socket.on('error', function (err) {
			throw 'Socket error - ' + err;
		});
```

This is AUTOGENERATED. I did not write this, but thanks for figuring out that very annoying problem. You saved my day!

**Comment by Hirbod** [comment]
Changed throw 'Socket error - ' + err to console.log('Socket error - ' + err); and this fixed the problem. THANK YOU!

**Comment by happilymarrieddad** [comment]
@Hirbod yea it's killing me lol. Has this been pushed? 

|handler  | 1519765951970 - Origin: Worker (PID 13438)
1|handler  |    [Error] SocketProtocolError: Server ping timed out
1|handler  |     at SCSocket._onSCClose (/var/www/handler/node_modules/socketcluster-client/lib/scsocket.js:629:15)
1|handler  |     at SCTransport.<anonymous> (/var/www/handler/node_modules/socketcluster-client/lib/scsocket.js:280:12)
1|handler  |     at SCTransport.Emitter.emit (/var/www/handler/node_modules/component-emitter/index.js:133:20)
1|handler  |     at SCTransport._onClose (/var/www/handler/node_modules/socketcluster-client/lib/sctransport.js:204:28)
1|handler  |     at Timeout._onTimeout (/var/www/handler/node_modules/socketcluster-client/lib/sctransport.js:269:10)
1|handler  |     at ontimeout (timers.js:475:11)
1|handler  |     at tryOnTimeout (timers.js:310:5)
1|handler  |     at Timer.listOnTimeout (timers.js:270:5)
1|handler  | 1519765952071 - Worker 0 exited - Exit code: 1
1|handler  |    >> Worker PID: 13523
