### ISSUE TITLE
'SCC_STATE_SERVER_HOST' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by HassanShulli** [SocketCluster/socketcluster#380]
I have followed the guide: https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md However when I attempt to launch the broker this is what I am getting : 'SCC_STATE_SERVER_HOST' is not recognized as an internal or external command,
operable program or batch file.

**Comment by MegaGM** [comment]
```js
SCC_STATE_SERVER_HOST='127.0.0.1' SOCKETCLUSTER_SERVER_PORT='8888' node server
```
The syntax is for *nix terminals(linux, mac). You have to find out how to setup environment variables in the terminal you use and rewrite the command. I guess you use cmd.exe

**Comment by HassanShulli** [comment]
yes I am using cmd.exe on windows, can you advise on where I can find the equivalent windows commands?

**Comment by MegaGM** [comment]
Fortunately I don't know how to struggle on Windows. So I cannot advice you something Windows-specific.

p.s. After ~1 min of googling, I guess you could use
```cmd
set SCC_STATE_SERVER_HOST='127.0.0.1' && set SOCKETCLUSTER_SERVER_PORT='8888' && node server.js
```
Btw you can see all environment variables via command `set` with no arguments.
