### ISSUE TITLE
Advantages of using Kubernetes

### ISSUE THREAD

**Issue by idibidiart** [SocketCluster/socketcluster#382]
I read the guide of scaling SC.

It talks about two options: with or without Kubernetes.

But it does not mention why I would choose one over the other. There is no guidance or mention of any deciding factors.

Please elaborate and clarify the criteria for each of the two options.

**Comment by jondubois** [comment]
It depends on if you want to automate your infrastructure or not.
If you have a very large production system with hundreds of machines then K8s would be very helpful.

**Comment by happilymarrieddad** [comment]
@idibidiart We have 7 nodes in our production environment and I never got around to using Kubernetes... I wish I had. I've been meaning to go back and fix this mistake but I haven't got the time to take care of it. I would suggest you start with Kubernetes. I wrote a deploy script that works for now but I'm sure I would have been better off learning Kubernetes from the start.
