### ISSUE TITLE
Exchange not working

### ISSUE THREAD

**Issue by happilymarrieddad** [SocketCluster/socketcluster#385]
Hey guys,

For some reason, exchange publishing stopped working with SCC. I didn't change anything except upgrading to SC 10 from 8 and our exchange system stopped working. Here is an example.

```
var SCWorker = require('socketcluster/scworker')
var express = require('express')
let SC = require('socketcluster-client')

class Worker extends SCWorker {
  run() {
    console.log('   >> Worker PID:', process.pid)
    var environment = this.options.environment

    var app = express()

    var httpServer = this.httpServer
    var scServer = this.scServer
    let scExchange = this.exchange

    httpServer.on('request', app)


    let packet = {
      success:1,
      message:'Here is your erp data',
      notify:'orders-edit-set-erp-transaction-data',
      customer_id:1000
    }

    let soc = SC.connect({
      hostname:<url>,
      secure:true
    })

    soc.on('connect',() => {

      soc.publish('1000',packet)

    })

  }
}

new Worker()

```

works but this does not

```
var SCWorker = require('socketcluster/scworker')
var express = require('express')

class Worker extends SCWorker {
  run() {
    console.log('   >> Worker PID:', process.pid)
    var environment = this.options.environment

    var app = express()

    var httpServer = this.httpServer
    var scServer = this.scServer
    let scExchange = this.exchange

    httpServer.on('request', app)


    let packet = {
      success:1,
      message:'Here is your erp data',
      notify:'orders-edit-set-erp-transaction-data',
      customer_id:1000
    }

    this.exchange.publish('1000',packet)

  }
}

new Worker()

```

**Comment by happilymarrieddad** [comment]
Going back to 8 fixes it.

**Comment by happilymarrieddad** [comment]
I just created a SC client connection to the system in the worker, super dirty I know, and it works like it should. I just replaced   ```worker.exchange.publish``` with ```soc.publish``` and it works. I hope that makes sense.

**Comment by jondubois** [comment]
@happilymarrieddad It's not exactly the same. In the first case `soc.publish('1000',packet)` is called from inside the 'connect' handler (which is triggered asynchronously). In the second case the `this.exchange.publish('1000',packet)` is triggered directly inside the `run` method.

When an instance starts it can take a bit of extra time to join the SCC cluster. If I publish inside a `setTimeout` it works fine in both cases for me.

**Comment by happilymarrieddad** [comment]
hmm the publish is driven by event and isn't called immediately... I guess bad test
Basically, when a user presses a button it fires an event and other users can get a notification given they match the conditions. When I listen to all events that are published, I don't see it... it's really weird. If I publish from the client it works but not from the worker.exchange.

**Comment by happilymarrieddad** [comment]
This is the actual function

```
/**
     * GP Channel Handlers
     * @type {[type]}
     */
    scExchange.subscribe('set-erp-transaction-data').watch(function(data) {
				console.log('Setting ERP Transaction Data')

        let chan = data.customer_id ? data.customer_id.toString() : '1000'
        let packet = {
            success:1,
            message:'Here is your erp data',
            notify:'orders-edit-set-erp-transaction-data',
            data:data,
            customer_id:data.customer_id || 1000
        }

        worker.exchange.publish(chan,packet,(err,ack) => {
          console.log(packet)
        })
    })
```
if I console.log the packet, it logs but a client never gets the message... If I replace the worker.exchange.publish with a client.publish it works.. really weird. Even after the server has been live for a long time.

**Comment by jondubois** [comment]
@happilymarrieddad I can't reproduce this issue. I don't think any changes have been made to this area.

Maybe you can try upgrading scc-broker-client https://www.npmjs.com/package/scc-broker-client to v2.2.0

**Comment by jondubois** [comment]
Also I notice that you use `scExchange` to subscribe but `worker.exchange` to publish. Is `worker` pointing to the correct object?

**Comment by happilymarrieddad** [comment]
```let scExchange = worker.exchange```
is above.. sorry about that

**Comment by happilymarrieddad** [comment]
pretty sure this started happening when I upgraded to scc-broker-client 2.2

**Comment by jondubois** [comment]
@happilymarrieddad Ok sure sounds good.

**Comment by MegaGM** [comment]
I've looked at some new code, shouldn't there be `'updatedPubs'` instead of `'active'` or `undefined`? https://github.com/SocketCluster/scc-broker-client/blob/0069ea9ead2e119e3f204d0970718b2a6dc339ff/index.js#L165 I'm not sure though, it might be my imagination.

**Comment by jondubois** [comment]
@happilymarrieddad Also did you remember to update the code inside broker.js to match the new format: 

```
var SCBroker = require('socketcluster/scbroker');
var scClusterBrokerClient = require('scc-broker-client');

class Broker extends SCBroker {
  run() {
    console.log('   >> Broker PID:', process.pid);

    // This is defined in server.js (taken from environment variable SC_CLUSTER_STATE_SERVER_HOST).
    // If this property is defined, the broker will try to attach itself to the SC cluster for
    // automatic horizontal scalability.
    // This is mostly intended for the Kubernetes deployment of SocketCluster - In this case,
    // The clustering/sharding all happens automatically.

    if (this.options.clusterStateServerHost) {
      scClusterBrokerClient.attach(this, {
        stateServerHost: this.options.clusterStateServerHost,
        stateServerPort: this.options.clusterStateServerPort,
        authKey: this.options.clusterAuthKey,
        stateServerConnectTimeout: this.options.clusterStateServerConnectTimeout,
        stateServerAckTimeout: this.options.clusterStateServerAckTimeout,
        stateServerReconnectRandomness: this.options.clusterStateServerReconnectRandomness
      });
    }
  }
}

new Broker();
```

**Comment by jondubois** [comment]
@MegaGM this change was intentional. There was an issue that if a regular SC instance would join the cluster in the middle of a sync round then the state of the cluster would get stuck and not sync properly because the new client was 'active' but all the other instances were stuck on a different phase. The client used to wrongly assume that the cluster was always 'active'.

So the fix was to make it so that the client would use the last known phase of the cluster that way new instances that join are now always in agreement with all other instances.

**Comment by jondubois** [comment]
@happilymarrieddad Also you may want to upgrade to the latest version of `scc-state` https://hub.docker.com/r/socketcluster/scc-state/tags/ `v1.7.1`

**Comment by happilymarrieddad** [comment]
package.json
```
{
  "name": "socketcluster-sample",
  "description": "A sample SocketCluster app",
  "version": "1.0.0",
  "scripts": {
    "prod": "NODE_ENV=production gulp"
  },
  "contributors": [
    {
      "name": "Nick Kotenberg",
      "email": "nkotenberg@fusionware.com"
    },
    {
      "name": "Sam Graham",
      "email": "sgraham@fusionware.com"
    }
  ],
  "dependencies": {
    "aes256": "^1.0.3",
    "async": "^2.6.0",
    "base64-stream": "^0.1.3",
    "connect": "^3.6.6",
    "debug": "^3.1.0",
    "express": "^4.16.2",
    "ftp": "^0.3.10",
    "geocoder": "^0.2.2",
    "google-distance": "^1.0.1",
    "gulp": "^3.9.1",
    "imap": "^0.8.17",
    "jquery": "^3.3.1",
    "jsdom": "9.12.0",
    "minimist": "^1.2.0",
    "moment": "^2.20.1",
    "mysql": "^2.15.0",
    "nightmare": "2.10.0",
    "node-env-file": "^0.1.8",
    "node-mysql-deadlock-retries": "^2.1.0",
    "node-schedule": "^1.3.0",
    "nodemailer": "^4.6.0",
    "object-sizeof": "^1.0.10",
    "promise-mysql": "^3.2.1",
    "request": "^2.83.0",
    "sc-cluster-broker-client": "^1.0.5",
    "sc-redis": "^0.2.0",
    "scc-broker-client": "^2.1.2",
    "serve-static": "^1.13.2",
    "socketcluster": "^10.0.1",
    "socketcluster-client": "^10.1.1",
    "socketcluster-server": "^10.0.1",
    "templatizer": "^1.5.4",
    "vo": "^4.0.2",
    "xml2js": "^0.4.19",
    "xvfb": "^0.2.3"
  },
  "keywords": [
    "websocket",
    "server",
    "realtime",
    "cluster",
    "scalable"
  ],
  "readmeFilename": "README.md"
}

```

**Comment by happilymarrieddad** [comment]
```
var config = require('./config.json')
var SCBroker = require('socketcluster/scbroker');
var scClusterBrokerClient = require('scc-broker-client');

class Broker extends SCBroker {
  run() {
  		let broker = this
		console.log('   >> Broker PID:', process.pid);

		// This is defined in server.js (taken from environment variable SC_CLUSTER_STATE_SERVER_HOST).
		// If this property is defined, the broker will try to attach itself to the SC cluster for
		// automatic horizontal scalability.
		// This is mostly intended for the Kubernetes deployment of SocketCluster - In this case,
		// The clustering/sharding all happens automatically.
		process.env = config
		if (broker.options.clusterStateServerHost) {
			var broker_config = {
				stateServerHost: broker.options.clusterStateServerHost,
				stateServerPort: Number(broker.options.clusterStateServerPort),
				authKey: broker.options.clusterAuthKey,
				stateServerConnectTimeout: broker.options.clusterStateServerConnectTimeout,
				stateServerAckTimeout: broker.options.clusterStateServerAckTimeout,
				stateServerReconnectRandomness: broker.options.clusterStateServerReconnectRandomness
			}
			scClusterBrokerClient.attach(broker,broker_config);
		}
	}
}

new Broker();

```

**Comment by happilymarrieddad** [comment]
@jondubois could it be that the client doesn't have an AUTH_KEY set? If I connect to a cluster from a client and broadcast into that system and the client doesn't have an AUTH_KEY but the state and broker servers do? The weird part is the subscribe channel console.log's but the message from that subscribe event doesn't seem to emit anything if that makes sense.

**Comment by happilymarrieddad** [comment]
@jondubois ok I was able to recreate this. I had to recreate our production env though in order to do it.

1) create a state server on aws
2) create a broker server on aws
3) create 2 app servers on aws.
4) connect it all up
5) Test emit from app server 1 to client on app server 2.. cluster is live
6) create a client on my local machine that connects to one of the app servers on the cluster.
7) have it subscribe to channel '1000' and log any data that comes across that channel.
8) socketcluster create app (locally) and connect to cluster
9) have that local server publish a message to channel '1000' and the client will NOT emit the event but if I do the same thing from a SC-Client connection on locally it works.

![selection_048](https://user-images.githubusercontent.com/6416323/37438078-15800d36-27b6-11e8-868b-aaf7ba887dc3.png)

**Comment by jondubois** [comment]
>> pretty sure this started happening when I upgraded to scc-broker-client 2.2

@happilymarrieddad can you confirm this?
So if you use the latest `scc-state` version and latest SC version `v10.1.2` but you use the previous version of `scc-broker-client` (e.g. `v2.1.2` or earlier) does that alone fix the problem or downgrading SC itself to v8 is necessary?

**Comment by happilymarrieddad** [comment]
Ok, so the client works but the worker does not on "scc-broker-client": "^2.1.2"


![selection_049](https://user-images.githubusercontent.com/6416323/37472914-cc9029ee-2832-11e8-8fea-f5375bac9eee.png)
![selection_050](https://user-images.githubusercontent.com/6416323/37472916-ce4bc374-2832-11e8-83d6-9ad8f6e684c4.png)
![selection_051](https://user-images.githubusercontent.com/6416323/37472920-cfff8dcc-2832-11e8-9153-b1e455431f1e.png)
![selection_052](https://user-images.githubusercontent.com/6416323/37472925-d2f3a676-2832-11e8-8634-403de791cff3.png)
![selection_053](https://user-images.githubusercontent.com/6416323/37472928-d4f1aacc-2832-11e8-8cc2-70640cf6a695.png)

**Comment by happilymarrieddad** [comment]
![selection_052](https://user-images.githubusercontent.com/6416323/37474699-9b2c09d2-2836-11e8-96e0-0e48a8b8d82a.png)
![selection_053](https://user-images.githubusercontent.com/6416323/37474704-9cd6e75c-2836-11e8-9f9b-4137f69a8231.png)

**Comment by happilymarrieddad** [comment]
@jondubois on 1.2.2 of scc-broker-client every time I publish to a channel with the worker.exchange it hangs up. On 2.2 it will hang up maybe 10 secs after I publish and the client will never get the message.

**Comment by happilymarrieddad** [comment]
it's pretty simple to replicate. You create a cluster,   (state,broker,1 app server, 1 client connected to the app server, then another app server and use the second one's exchange to publish to a channel that the client is subscribed to and the client will NOT get the message)

**Comment by happilymarrieddad** [comment]
For my test, I spun up 4 AWS micro servers and I used a local app server to publish. The weird part, is if I use the SC-client package INSIDE the second app server the first client gets the message every time.

**Comment by jondubois** [comment]
@happilymarrieddad Can you reproduce the issue with a very basic SC instance (with very little custom logic on top)? I have not been able to reproduce it still and I know at least one big company (with tens of thousands of concurrent users and thousands of unique channels) which is using the `worker.exchange.publish(...)` feature in production without any issues.

I'll keep trying to reproduce though. Do you get any errors at all?

**Comment by happilymarrieddad** [comment]
@jondubois 
sorry man I'm right in the middle of work. I'll create a very simple network of 1 state server, 1 broker, 2 application servers from ```socketcluster create``` and two clients each one connected to one of the app servers and then try it.

I know it's really weird because we are using worker.exchange.publish quite a bit and it's working just fine except for this instance.. when clients publish it works great which is 99.9% of our services but when a app server publishes there are some clients that are not getting the message.. really weird. 

When I get another chance I'll create the above simple test and let you know how it goes. For now, I just am using SC-client publish and it's working so our customers are happy...

**Comment by jondubois** [comment]
@happilymarrieddad Did you check that all dependencies of the regular socketcluster instances are up to date? You can try to delete your project's `package-lock.json` and and reinstall dependencies from scratch.

**Comment by happilymarrieddad** [comment]
@jondubois hey man, no one else seems to be having this issue and with my terrible fix it's working. I'm too busy at the moment to figure out what I'm doing wrong so I'm going to close this issue. Thanks so much for taking the time to reply back and work with me!
