### ISSUE TITLE
How do  shut down  JWT certification

### ISSUE THREAD

**Issue by wanglong167** [SocketCluster/socketcluster#389]
How do  shut down  JWT certification

**Comment by MegaGM** [comment]
@wanglong167 Do you want to disable builtin JWT authentication engine and use your own? If that's the case then read the entire #233 issue, and especially this https://github.com/SocketCluster/socketcluster/issues/233#issuecomment-254884626

If not, could you join [Gitter chat room](https://gitter.im/SocketCluster/socketcluster) and clarify your question?
