### ISSUE TITLE
MIDDLEWARE PUBLISH doesn't prevent .emit()

### ISSUE THREAD

**Issue by Hirbod** [SocketCluster/socketcluster#390]
Hi,

I am doing some checks to prevent a subscription in the publish-middleware (checking against firebase-admin sdk). Validations works and I did understand how to properly use "next()" and "next('error')" or "next(true)" for silent block. While I can see the logs and authentication works, a "emit" still works. How is this possible? I thought a next(err) should be enough?

Do I really need to add another EMIT Middleware for prevention?

**Comment by Hirbod** [comment]
I also do receive the warnings in console:

![bildschirmfoto 2018-03-20 um 01 07 12](https://user-images.githubusercontent.com/504909/37628729-114ba26a-2bdb-11e8-962e-84d37bfcf26e.png)


When I try to emit inside that browser, I can see that "watch" never gets called but on another device, I can see the messages enter. So I guess the only way to prevent illegal accessing is to add another security layer inside of emit, am I right?

**Comment by jondubois** [comment]
@Hirbod MIDDLEWARE_PUBLISH and MIDDLEWARE_EMIT are completely separate lines (or at least they should be). So if you want to block emit, you should setup a separate MIDDLEWARE_EMIT. Note that you can add the same function to both middlewares.

**Comment by Hirbod** [comment]
Hi @jondubois yeah I will do this then.. But to be honest, IMHO, a blocked user from subscribe should not be emitting anything. Thats just another overhead, cause I have to do so much cryptography (validating JWT) in every single request now

**Comment by Hirbod** [comment]
It worked, feel free to close or leave it open if you like to discuss @jondubois

**Comment by MegaGM** [comment]
@Hirbod Sometimes you don't trust the clients, so you don't want to let them `.publish()` anything. In such setups the only one trusted publisher is your sc-based app. At the same time you still want to communicate with clients via `.emit()`.

**Comment by Hirbod** [comment]
I see your point, its legit.
