### ISSUE TITLE
Mobile native SDK.....

### ISSUE THREAD

**Issue by JoHuang** [SocketCluster/socketcluster#391]
Hi

Is Mobile native SDK being developed recently?
We would like to use SC but seems lack of mobile app supported.

And the api spec seems not up-to-date.... (we may build our own sdk in C++)

Thanks

**Comment by sacOO7** [comment]
We have clients developed in both Java and swift. You can use the same for
mobile app development

**Comment by sacOO7** [comment]
Those clients are native clients. So you don't have to worry about
performance issues. Please check official website for client info.
