### ISSUE TITLE
Problem sending data between clients on different ports

### ISSUE THREAD

**Issue by MadGeometer** [SocketCluster/socketcluster#399]
Hello,

I'm following the "Running using Node.js directly" part of the SCC Guide page (at https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md) and ran into the following problem: I'm unable to send messages between clients on different ports. The guide page implies that you can send messages between clients running on port 8000 and port 8001.

I can send messages between two clients running on the same port, however. 

Is there a mistake in the guide page? All other steps except for that one worked OK.

Thanks,
Mike

**Comment by jondubois** [comment]
@MadGeometer That is definitely supported - It can be different ports on the same host, the same port on different hosts or different ports on different hosts.

What is the log from your `scc-state` server?

**Comment by MadGeometer** [comment]
It does not show messages like "The scc-worker instance 2e40a451-16f3-4ac6-b410-11e4386fa7b9 at address ::ffff:172.18.0.6 joined the cluster"

One of my coworkers got the tutorial to work, using 9.3.3. Another coworker was unable to get it to work until he updated to SC 11, as well as modifying some worker code.

**Comment by jondubois** [comment]
make sure that you're using the latest versions of `scc-state` and `scc-broker` repos/instances and also the latest version of the `scc-broker-client` library.
