### ISSUE TITLE
How to divide connection load in all available cores?

### ISSUE THREAD

**Issue by hardikamutech** [SocketCluster/socketcluster#400]
We are using socketcluster in both mobile apps (Andorid and Ios) as a client end. we have created one backend client using that we are broadcasting message to every online users.
we have around 20000 online concurrent users but it always consume one core while we have 8 core cpu. how can we divide all concurrent users in all cores.

We did stress test with your SC-Stress-test-master and we have connected around 32k concurrent users and publish message every second, this runs smoothly, Here you have used node.js `cluster` and `os` modules, how can we implement that in our scenario? Our all clients are from Ios and Android end.

An example would be great to understand.

Thanks in advanced.

**Comment by jondubois** [comment]
@hardikamutech You need to increase the number of workers; just change the workers option in server.js to the number of worker processes you like. If you haven't added any stateful socket management logic to your worker process then you won't need to change any code.

**Comment by hardikamutech** [comment]
Thanks a lot @jondubois for a quick response, I will try your suggestion and let you know.
