### ISSUE TITLE
Understandable manual for scaling

### ISSUE THREAD

**Issue by Hirbod** [SocketCluster/socketcluster#401]
Hi,

sorry for bothering again, but we're currently investing a lot in our infrastructure and we really need to make some future plans and I need to understand a bit more when it comes to scaling.

Kubernetes are out of scope.

To make our application understandable:

We have a live quiz (trivia) with n Users (n will be 100k quickly)
All this users are connected to our server. From the server side, we exchange() a JSON object (the same for all) to every connected user.

A popup will open on the iOS and Android device with a question (trivia) and 3 answer choises. You might know this from the famous app "HQ".

Users have 10 seconds to answer. They can chose and a emit will be send to our server.
We make internal checks on the serverside (a single node server) and store stuff inside redis.

Then we make an exchange with the answer to all connected users.
Thats it basically. So 1 Server send to 100k users a single JSON. 100k Users answer on that with a JSON (containing chosen answer and some auth stuff).

We have a 16-Core AMD Ryzen Server, for the sucketcluster part and a 16-Core AMD Ryzen for the node api and a 16-Core AMD Ryzen for the Redis server. All Servers have 64GB RAM.

So basically, I am note scared of performance for the redis and api server, but for the socketcluster-server.

Our current setup is:
16 Worker
2 Broker
Running on Port 8000 and proxied by nginx.

My first question:
Do I even need 2 broker? Currently, everything is on a single machine. Is there any difference if I have 1 oder 5 brokers on a single machine?

2 Question:
How to scale without kubenetes? Let's say, there are performance issues and we want to buy another server. How do we need to connect everything? Let's say, we have 3 Servers, do we have to setup a clone of server 1 on every server and use a load balancer for connecting? This wouldn't be any problem, but how to make sure, that an exchange() will reach every single user? The .emit() wouldn't be a problem, as everything is stored inside redis.

I still don't get how to setup our infrastrcture. Your documentation didn't help me on this.

Thank you very much!

More details how we start the server:

```shell
forever -o /srv/trivia/out.log -e /srv/trivia/err.log start --killSignal=SIGTERM --watchIgnore /srv/trivia/quiz/public /srv/trivia/quiz/forever/dev.json -w 16 -b 2 --nouse-idle-notification --expose-gc --max-old-space-size=16192
```

Our limits/sysctl

```bash
 fs.file-max = 1000000
 fs.nr_open = 1000000

fs.inotify.max_user_instances=1048576
fs.inotify.max_user_watches=1048576
fs.nr_open=1048576
net.core.netdev_max_backlog=1048576
net.core.rmem_max=16777216
net.core.somaxconn=65535
net.core.wmem_max=16777216
net.ipv4.ip_local_port_range=1024 65535
net.netfilter.nf_conntrack_max=1048576
net.ipv4.tcp_fin_timeout=5
net.ipv4.tcp_max_orphans=1048576
net.ipv4.tcp_max_syn_backlog=20480
net.ipv4.tcp_max_tw_buckets=400000
net.ipv4.tcp_no_metrics_save=1
net.ipv4.tcp_rmem=4096 87380 16777216
net.ipv4.tcp_synack_retries=2
net.ipv4.tcp_syn_retries=2
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_wmem=4096 65535 16777216
net.nf_conntrack_max=1048576


net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.ipv4.tcp_rmem = 4096 16384 33554432
net.ipv4.tcp_wmem = 4096 16384 33554432
net.ipv4.tcp_mem = 786432 1048576 26777216
net.ipv4.tcp_max_tw_buckets = 360000
net.core.netdev_max_backlog = 2500
vm.min_free_kbytes = 65536
vm.swappiness = 0
net.ipv4.ip_local_port_range = 1024 65535
```

```shell
*               soft    nofile          1048576
*               hard    nofile          1048576
*               soft    nproc          1048576
*               hard    nproc          1048576
*               soft    memlock         unlimited
*               hard    memlock         unlimited
```

**Comment by Hirbod** [comment]
@jondubois @toredash any help here? I don't want a "setupready" code, I just want a guide. 
https://socketcluster.io/#!/docs/scaling-horizontally is totally useless. I doesn't help us to get a real idea how a "broker.js" should look and how to setup all the other servers if we want to scale horizontally.. 

I have a lot of pressure on this so I would really appreciate a quick answer.

**Comment by jondubois** [comment]
@Hirbod yeah we need to fix documentation. Did you look at https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md#running-using-nodejs-directly ?

**Comment by jondubois** [comment]
I've trimmed down the stuff on the website a fair bit; see https://socketcluster.io/#!/docs/scaling-horizontally - Hopefully that helps to put more emphasis on the links (where all the real info is).

Hopefully this makes it clearer but documentation is ongoing work.
