### ISSUE TITLE
 Client pong timed out error on server side, when client suddenly lost it's connection

### ISSUE THREAD

**Issue by miladr0** [SocketCluster/socketcluster#409]
why server show this error when a client for example an android phone lost it's connection,
i mean it's normal a client lost it's connection so why server print this error on output and how can i disable this error.
```
1526064883247 - Origin: Worker (PID 2733)
   [Warning] SocketProtocolError: Client pong timed out
    at SCServerSocket._onSCClose (/home/vps/socket_cluster/node_modules/socketcluster-server/scserversocket.js:248:17)
    at Timeout.<anonymous> (/home/vps/socket_cluster/node_modules/socketcluster-server/scserversocket.js:193:10)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by miladr0** [comment]
no one can help me? :(

**Comment by jondubois** [comment]
@miladr0 It just means that the server sent a ping to a client socket but the client socket did not respond with a pong in time. Either it means that your client was too busy (e.g. maybe stuck in a for loop?) or the internet connection was bad (so the client sent a pong but it did not reach the server in time)... Or maybe you didn't set the `pingInterval` and `pingTimeout` options correctly when you created the main SocketCluster instance; the `pingInterval` should always be smaller than `pingTimeout` (ideally, the interval should be less than half of the timeout; e.g. you need at least two missed pings/pongs before the socket times out) .
