### ISSUE TITLE
Stalled websocket connections

### ISSUE THREAD

**Issue by Hirbod** [SocketCluster/socketcluster#415]
Hi there,

when I am testing, I do have to reboot the workers sometimes. While having 3 apps open, only one reconnects immediately, the two others receiving errors in the log "connection times out", connection was closed before established, and on Chrome Debugger, I can see that the connection got "stalled".

Why is this happening and why only when on WLAN? If I switch to LTE or 3G, this "stalling" never happens. Looks like this might be due to multiple devices using the same IP? I tried everything I could find on the net (changing keepalive on nginx, chaning TIME_WAIT features in sysctl.conf).

How can I prevent stalled connections (they need around 1-2 minutes for reconnecting).

**Comment by Hirbod** [comment]
@jondubois 

having 
```
net.ipv4.tcp_tw_recycle = 1
```

in my /etc/sysctl.conf caused the issue. Setting to 0 or removing fixed my problem. Finally no stalled connections.

**Comment by happilymarrieddad** [comment]
@Hirbod was that on your nginx server?

**Comment by Hirbod** [comment]
Yes

**Comment by Hirbod** [comment]
Nginx is on the same machine as socketcluster
