### ISSUE TITLE
create p2p messaging app

### ISSUE THREAD

**Issue by mahdiyousofun** [SocketCluster/socketcluster#418]
hello
is it possible to make pear to pear messaging app by this framwork( i mean socketCluster)
i want to make an app that i can chat with just one friend no everyone that join to group

**Comment by MegaGM** [comment]
SocketCluster is designed with client-server architecture in mind.

It is possible and easy to
> make an app that i can chat with just one friend no everyone that join to group

However, when it comes to implementing pure P2P architecture, it is not possible with SC. Well, *actually it is possible*, but in some quite wretched way. P2P is quite different from client-server architecture after all.

**Comment by mahdiyousofun** [comment]
i mean that i send a message to specific user not to all user.
so as you said it is possible.
can you help me in this subject?
how can save online users? actually if a user connected to server can i save its connection in one list?

**Comment by MegaGM** [comment]
I suggest you to read this article https://blog.baasil.io/socketcluster-design-patterns-for-chat-69e76a4b1966
Don't forget to read the docs https://socketcluster.io/#!/docs

This is issue tracker for bugs. For simple questions, please use Gitter chat room https://gitter.im/SocketCluster/socketcluster

**Comment by sacOO7** [comment]
Thanks for helping guy out @aza
