### ISSUE TITLE
Javascript error listener in Broker

### ISSUE THREAD

**Issue by dafivius** [SocketCluster/socketcluster#419]
Hi all. It's very hard to debug broker process, because it doesnt produce any javascript errors.
When im trying to get method of null or exception occurs - there is no error in console and broker continues to work but not correct. How can i see javascript errors in broker process? Thanks.

p.s. Loglevel is 3 (but as i can see its for internal server errors, not for Javascript)

**Comment by MegaGM** [comment]
Privet!
> When im trying to get method of null or exception occurs

Could you, please, elaborate how exactly do you do that?
Do you have some custom JS code inside the broker process?
Or do you `require('sc-broker').exec(somethingThatProducesAnException)`?
And which broker, `sc-broker` or `scc-broker`?

**Comment by dafivius** [comment]
Look at this on('publish') handler. No errors at console.
```
let SCBroker              = require('socketcluster/scbroker');
let scClusterBrokerClient = require('scc-broker-client');
let EventHelper           = require('./public/js/helpers/EventHelper.js');
let XMPPClient            = require('./public/js/xmpp/XMPPClient.js');
class Broker extends SCBroker {
    run() {
        console.log('>> Broker PID:', process.pid);

        this.xmppStorage = {};

        if (this.options.clusterStateServerHost) {
            scClusterBrokerClient.attach(this, {
                stateServerHost               : this.options.clusterStateServerHost,
                stateServerPort               : this.options.clusterStateServerPort,
                mappingEngine                 : this.options.clusterMappingEngine,
                clientPoolSize                : this.options.clusterClientPoolSize,
                authKey                       : this.options.clusterAuthKey,
                stateServerConnectTimeout     : this.options.clusterStateServerConnectTimeout,
                stateServerAckTimeout         : this.options.clusterStateServerAckTimeout,
                stateServerReconnectRandomness: this.options.clusterStateServerReconnectRandomness
            });
        }

        this.on('publish', (channel, data) => {
            console.log(process.pid, 'Broker received data from channel', channel, 'data:', data);
            throw new Error(); //nothing
this.notExistedMethod(); //nothing
abcdefgh //nothing;
        });
   
    }
  
}

new Broker();

```

**Comment by jondubois** [comment]
@dafivius It should definitely log errors from broker.
What version of SC are you using?
What Node.js version?
What do your `SocketCluster` config options (in server.js) look like?

**Comment by dafivius** [comment]
@jondubois node 9.7.1, SC is latest.
@MegaGM exactly as you wrote above. I didn't use redis adapter. 

Thanks for your replies. I've reinstalled SC, reinstalled my NPM and began to gather errors in console (no ideas why). Sorry for that situation, you can close an issue. My config is: MacOSX, Node 9.7.1, NPM 6.1.0, PhpStorm 2017.3, SC is latest. If somebody will face similar situation - try my steps first.
