### ISSUE TITLE
How to connect/notify 2 user subcribe channel?

### ISSUE THREAD

**Issue by tangquoctuan** [SocketCluster/socketcluster#429]
Hi,
I',m using the SCC design partern to create my demo chat application. My chat application is alike with another chat platform, signup user, show online users, choose user who you want to communicate with. So, my problem is: when user A choose user B to communicate, i can not find the way to notice user B know to subcribe and watch channel. Any ides to fix it? Sorry abount my English!!!

Thanks

**Comment by happilymarrieddad** [comment]
@tangquoctuan Hey man,

You can have each user subscribe to their own channel, for example subscribe to a channel using their user_id. Then, when a person wants to send another person a message, you can publish to the channel matching their ID. Then, you can send messages to everyone or just a specific person. I hope that makes sense and helps!

**Comment by tangquoctuan** [comment]
Hi @happilymarrieddad, thanks you for your reply,

Yah! Before I make an question about this problem, i solved it nearly as your solutions, but i used socket id per each user as an private channel to communicate between server and client. 

At the begnning, i choose socket.io as an framework for my project, but as you know that, it make my feel difficult to manage session between those node server. So, that is the reason why i have choosen socketcluster. 

If compare socket.io vs socketcluter, I feel each type has different strengths and weaknesses. The weaknesses of socketcluster is about pub/sub between client/server. In my opinion, i recommend author improve, separate emit/broadcast/v.v... as socket.io as done.

Thanks you!

**Comment by MegaGM** [comment]
@tangquoctuan  what do you mean by
> improve, separate emit/broadcast/v.v... as socket.io as done.

It's always great to improve SocketCluster! However, I didn't get what exactly did you mean by "emit/broadcast/v.v". Could you, please, explain a bit more in depth?

> difficult to manage session between those node server

You could read those comments, I hope they will help you gain more knowledge and make better architecture decisions.
https://github.com/SocketCluster/socketcluster/issues/425#issuecomment-395368250
https://github.com/SocketCluster/socketcluster/issues/165#issue-142854829

+Feel free to join the chat https://gitter.im/SocketCluster/socketcluster if you have any other questions :slightly_smiling_face:

**Comment by tangquoctuan** [comment]
Hi @MegaGM , thanks you for your reply.

> difficult to manage session between those node server

In this situation, i mention the weakness about the socket.io. When i hosted real-time server (socket.io) with cluster mode. I got an problem when those socket servers share socket id. After all an research, i have to use `socket.io-redis` acting as a management place to share session between nodes. But socketcluster do it very well.

> improve, separate emit/broadcast/v.v... as socket.io as done.

FYI, socket.io a lots of method comunicate between server/client (https://stackoverflow.com/a/10099325/3205195). So, return to my issue when apply `socketcluster` in this post, A want to connect with B, A emit event to server, server make an private event between A - B -> alert B that A want to communicate. But how can server alert to B because `socketcluster` does not support emit  to specified channel through their socket_id. So we have use th tricks as an recommed of @happilymarrieddad said.

Thanks you!

**Comment by tangquoctuan** [comment]
Hi @happilymarrieddad,

Base on your suggestion that each channel subcribe their individual *id* and...  the error has occurred:

```
[Warning] BrokerError: Failed to subscribe socket to the tuan: 1,tuan: 2,tuan: 3,tuan: 4,tuan: 4,tuan: 5 channel - Socket imsWT8xa5sFCmNx0AAAB provided an invalid channel name
    at /home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/socketcluster-server/scserver.js:444:23
    at EventEmitter.SCServer._subscribeSocket (/home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/socketcluster-server/scserver.js:239:17)
    at Emitter.<anonymous> (/home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/socketcluster-server/scserver.js:442:12)
    at Emitter.emit (/home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/component-emitter/index.js:133:20)
    at /home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/socketcluster-server/scserversocket.js:165:38
    at /home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/socketcluster-server/scserver.js:748:15
    at /home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/async/dist/async.js:1110:9
    at /home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/async/dist/async.js:460:16
    at replenish (/home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/async/dist/async.js:977:25)
    at /home/tangquoctuan/sc-demo-chat/socketcluster/dm/node_modules/async/dist/async.js:986:9

```

**Comment by jondubois** [comment]
@tangquoctuan It looks like you may be passing an array as the channel name. The channel name needs to be a string.

**Comment by tangquoctuan** [comment]
Hi @jondubois ,

The *tuan: 1,tuan: 2,tuan: 3,tuan: 4,tuan: 4,tuan: 5* is a string message that i want to publish to individual channel (socket `imsWT8xa5sFCmNx0AAAB`)

**Comment by tangquoctuan** [comment]
I saw the problem and solved it, thanks for reply @jondubois! I'm appriciate it.

**Comment by JojoStacy** [comment]
I really love socketcluster but there is an issue I have been trying to solve for more than a week.
How can I ensure a user receives a message even when they were offline like and hour and then came back ?Is there also a way to find out if a user has consumed a message so that maybe I can persist it?

**Comment by jondubois** [comment]
@JojoStacy If you need offline capability, you need to keep a message log for each user in a database on the back end. So every time a message is sent to that user, an entry is added in the appropriate table/collection. Then when the user logs back in, you can just fetch the latest list of messages from the database. If you need offline capability then it's easier to always persist messages.

You can add UUIDs to messages and make the user to publish or send message receipts (acknowledgements) containing the UUID of each received message that way it's possible to check which messages have been received.

With SC, if you need to target specific users, you can subscribe to unique channels dedicated to each user (e.g. based on their usernames).

**Comment by JojoStacy** [comment]
Thank you very much ! Works like magic!
