### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by Charuru** [SocketCluster/socketcluster#436]
Last I checked it was on v5 or so, what are the changelogs so I know whether or not to upgrade?

**Comment by rasmuserik** [comment]
+1

I also need a changelog, - as we are upgrading from version 8 here, and want to know about possible incompatibilities/changes in protocol or API. Especially: are old clients compatible with newer versions of the server.

**Comment by happilymarrieddad** [comment]
I had real problems from 8 to 12. Sorry, I don't remember what I did to fix it but I just wanted to let you know that you might experience some issues.

**Comment by jondubois** [comment]
@rasmuserik The changelog is here: https://github.com/SocketCluster/socketcluster/releases - The hardest upgrade is usually from `v8` to `v9.0.3` so read that one very carefully.

**Comment by rasmuserik** [comment]
@jondubois Thanks a lot :)

Don't know how I missed it, as I now realise that it is clearly mentioned in the README. I'll add a pull request which adds the link you gave, and closes this issue.
