### ISSUE TITLE
[Question - Request] How can I limit number messages with time per socket?

### ISSUE THREAD

**Issue by tangquoctuan** [SocketCluster/socketcluster#437]
Hi guys,

I wanna apply mechanism about limit messages per socket with time. I have searched for this issue but found no one has suggested or asked about this issue. Though, i also resolve this problem with count the message sent from socket and store limit parameters in cache. But the problem here is message still have to transmit to server. If the system suffers so many time, to a certain threshold, server maybe crash. So, I need request the mechanism temporary disconnect with setup limit message in times per socket.

Thanks!

**Comment by jondubois** [comment]
@tangquoctuan There is no default option to do rate limiting in SC but it should be easy to implement it on your own using middleware. See https://socketcluster.io/#!/docs/middleware-and-authorization

**Comment by happilymarrieddad** [comment]
@tangquoctuan You can use the sc-publish-out package and modify it to add a timeout or something to message pushing. I will accept pull requests.
