### ISSUE TITLE
Inconsistency between wsEngines path configuration

### ISSUE THREAD

**Issue by Aareksio** [SocketCluster/socketcluster#439]
Check out reproduction repo: [Aareksio/socketcluster-test](https://github.com/Aareksio/socketcluster-test)
This should **at least** be documented somewhere.

**Comment by jondubois** [comment]
@Aareksio Thanks for pointing out this issue. It's now been fixed in `socketcluster-server@13.2.0` so that it  behaves consistently in both cases.
