### ISSUE TITLE
Is SC a P2P comm?

### ISSUE THREAD

**Issue by andreishosta** [SocketCluster/socketcluster#446]
Hi everyone. I just have a simple question. SC is for Realtime communication as I understand. Now I wonder when I publish a message to a channel and another user is subscribed to that channel, are we two connected directly or always everything passes from server?
Are we using P2P comm in SC? If not, how we call it realtime? maybe I'm wrong in defining realtime, but I though in realtime there should be no middle thing.

**Comment by jondubois** [comment]
Real-time just means that the message is pushed to the user with very little delay. You can build P2P servers using SocketCluster but it's not a WebRTC framework..
