### ISSUE TITLE
Retrieve Disconnection Message from Server.

### ISSUE THREAD

**Issue by ansubur** [SocketCluster/socketcluster#461]
I'm disconnecting a client from server using the below code

      var clients= scServer.clients;
      var specific_client=clients[socket.id];
      console.log('ScServer Client Socket ID : ' + specific_client.id);
      console.log('Subscriptions of this client : ' + specific_client.subscriptions);
      specific_client.disconnect(4001, 'Your are disconnect by the server.');

The client also gets disconnect, but I'm unable to retrieve the disconnection message sent by the server. How do I achieve it?

**Comment by ansubur** [comment]
Any suggestions?

**Comment by OzySky** [comment]
What have you tried doing on the client?

**Comment by ansubur** [comment]
I use .net client with following BasicClientListener events.
When I disconnect the client server side, I'm unable to capture message & the code. However the client gets disconnected successfully and OnDisconnected event is triggered.

    Public Sub OnDisconnected(socket As Socket) Implements IBasicListener.OnDisconnected
        TotalConnectedClient -= 1
        Debug.WriteLine("Disconnected ")
    End Sub

    Public Sub OnConnectError(socket As Socket, e As ErrorEventArgs) Implements IBasicListener.OnConnectError
        Debug.WriteLine("Connection Error " & vbNewLine & "Error : " & e.Exception.ToString)
    End Sub

**Comment by OzySky** [comment]
It seems to be related to the .net driver. 
You probably should open an issue there.

**Comment by ansubur** [comment]
Will do it. Thanks for your time.
