### ISSUE TITLE
Remove opinionated sample logic from worker.js

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#487]
Because the sample logic is the default which runs inside the SocketCluster docker container, we should just remove it because a lot of people want to run the container as-is so we shouldn't force it to be customized.

For example, these lines should be removed:
https://github.com/SocketCluster/socketcluster/blob/6ef8c3a97e3f205f5bdf23f935405653165ae9de/sample/worker.js#L40-L54

**Comment by firrae** [comment]
Would it make more sense to just comment this out so it stands as an example instead of fully removing it?

**Comment by jondubois** [comment]
@firrae Sure sounds good.

**Comment by firrae** [comment]
#488 should solve this. I need to change the title of that PR though :/

**Comment by happilymarrieddad** [comment]
maybe there should be a `socketcluster create-sample` or something that includes all that code?

**Comment by jondubois** [comment]
@happilymarrieddad the code is there but commented out so it shouldn't be too difficult for someone to uncomment it if they want to try it out.

**Comment by happilymarrieddad** [comment]
@jondubois good to go!
