### ISSUE TITLE
Client pong timed out

### ISSUE THREAD

**Issue by Ido112** [SocketCluster/socketcluster#529]
Hey,
please someone can help me,
After any connection with my client-side, I have an error on my server console Client pong timed out

How I send a pong back to the server?
someone can send me example for this, please?

Thanks

**Comment by jondubois** [comment]
@Ido112 It should do it automatically. It just means your client was not responsive.
Possible causes:

- Client and server versions are incompatible (you can try running client in compatibility mode).
- Browser froze for a long time and caused the pong to timeout.
- Internet connection was lost for a while.

**Comment by Ido112** [comment]
Thanks
