### ISSUE TITLE
[Question]: Can the server be used without the client library?

### ISSUE THREAD

**Issue by SeedyROM** [SocketCluster/socketcluster#535]
Looking to have a platform and language agnostic way to talk to the server. I assume it's just some simple protocol for basic `AGExchange` stuff?

**Sorry if this is a dumb question!**

**Comment by jondubois** [comment]
@SeedyROM The SC protocol is a relatively simple JSON protocol on top of WebSockets so you can implement it with just WebSockets; especially if you don't need advanced features like pub/sub subscriptions. I know several companies and individuals who have built their own clients for it in different languages so yes it's possible.

You can see the different clients and implementation levels here: https://github.com/SocketCluster/client-drivers#curated-list-of-clients-for-socketcluster

Making an `L1` client using just WebSockets should be pretty easy while `L3` would require a lot more work to do well (though you can have a simplified implementation).

**Comment by SeedyROM** [comment]
Thanks for the quick reply, I ended up writing my own simple pub/sub with `ws` since I don't need too much functionality. Definitely going to look into L1 and L3 clients! :+1:
