### ISSUE TITLE
Re-align Git versions with NPM

### ISSUE THREAD

**Issue by loxy** [SocketCluster/socketcluster#536]
Can you please re-align the version tags of Git with the published NPM versions, like it was until version 14.3?

Best regards,
Kersten

**Comment by jondubois** [comment]
@loxy Thanks for pointing this out. I've added a new tag with the latest release version 16.0.1: https://github.com/SocketCluster/socketcluster/releases

**Comment by jondubois** [comment]
I also added a release tag for the `socketcluster-server` module: https://github.com/SocketCluster/socketcluster-server/releases

**Comment by loxy** [comment]
Great! Thank you!
