### ISSUE TITLE
Clients are disconnected automatically

### ISSUE THREAD

**Issue by valvenetbabu** [SocketCluster/socketcluster#541]
Hi,

I'm using socketcluster where I subscribe to redis and republish all the messages that are received. Frequently the server stops publishing the messages. When I check the console there were no updates on the console, when press enter key, all of a sudden, the server disconnects all connected clients & start accepting the connection again.

The occurrence is very random, sometimes it works for weeks without any issue. Some other days, it happens so frequently ie., within a few hours.
I'm not sure what is going wrong. Help me how to track this issue & fix this.

**Comment by jondubois** [comment]
What version are you using? SC doesn't not listen to any keyboard events so I don't see why pressing enter key would have any effect. Could it be something in your code or something related to your hosting provider?

**Comment by jondubois** [comment]
How are you launching the SC server? Are you running it in the background using `nohup` or a tool like `pm2`?

**Comment by valvenetbabu** [comment]
I'm using the older version of SC, I've downloaded it 8-10 months ago from github. Then I just modified the worker.js file.
I press enter key on the console window.
I run it from dos command prompt, using a batch file.
"node server.js"
My machine runs WindowsOS.

**Comment by valvenetbabu** [comment]
I've added console.log in the code so usually the I see some SCClient connection & disconnection status every few seconds. But when this issue occurs, the console update would have been stopped. So I press enter key on the screen to get it start updating.

**Comment by valvenetbabu** [comment]
To be more precise, all of a sudden
```
socket.on('disconnect', function () {
          printf(`\n===================\n${jsonssi.LoginID} Client Disconnected. Total connected :  ${clientsocketslist.length}`, true);
}
```
this event triggers for all connected clients.

**Comment by maarteNNNN** [comment]
@valvenetbabu Can you share the repo for me to take a look?
Check the package.json file and list the version of SocketCluster that you are using.

**Comment by valvenetbabu** [comment]
> 
> 
> @valvenetbabu Can you share the repo for me to take a look?
> Check the package.json file and list the version of SocketCluster that you are using.

    "socketcluster": "^14.3.2",

  "name": "socketcluster-sample",
  "description": "A sample SocketCluster app",
  "version": "1.0.0",

[worker.js.txt](https://github.com/SocketCluster/socketcluster/files/6237461/worker.js.txt)

**Comment by valvenetbabu** [comment]
@maarteNNNN I can post the code after removing the code which is not related to SC. But I think doing so will make the source similar to the sample that I downloaded and would make the problem disappear.

Can you find anything wrong in the code below? This code tries to get a value from REDIS server with a key.
`
    function RedMEMGet(getkey) {
      return new Promise((resolve, reject) => {
        RedMEM.get(getkey, function (err, rvalue) {
          var isError = 0;
          var errName;
          if (err) {
            isError = 1;
            errName = 'RedMEM Get Error';
          }
          if (rvalue == null) {
            isError = 1;
            errName = 'Null Value Error';
          }
          if (isError) {
            var catchArg
            try {
              printf('Error Getting value : ' + errName + '\nKEY : ' + getkey, isimportant);
              catchArg = {
                key: getkey,
                name: errName
              }
            } catch (error) {
              printf("error while RedMEMGet.Reject : " + error.message, 1);
            }
            reject(catchArg);
          } else
            resolve(rvalue);
        });
      })
    }
`

I've written every block of code inside try..catch.. and no exceptions were caught.
Could it be possible worker.js to break if there is some problem in REDIS server to which it is connected to?

**Comment by maarteNNNN** [comment]
Try catching the error this way, maybe it works:
```js
process.on('uncaughtException', (err) => console.log(err))
```

**Comment by valvenetbabu** [comment]
It looks the problem lies with redis library. Fixing the way the redis server connected across horizontal servers solved the issue.
