### ISSUE TITLE
`channelSubscriptionsCount` is not getting updated in AGServerSocket(scc-broker), when we add more brokers

### ISSUE THREAD

**Issue by Shankar-khati** [SocketCluster/socketcluster#556]
SCC configuration: 
 - 1 worker
 - 2 broker
 - 1 state
 
 Steps to reproduce.
 - Create 5 channels from client(as we have 2 brokers, assuming Broker1 will get 2 channels and  Broker2 will get 3 channels ).
 - Just to check how many Channels subscribed by this broker you can use `this.agServer.clients['clientId'].channelSubscriptionsCount` (You will get like 2 for Broker1 and 3 for Broker2)
 -  Disconnect Broker1 (Now this channels will be again distributed among rest of brokers, So Broker2 will get 5 Channels ).
 - Again check on Broker2 `this.agServer.clients['clientId'].channelSubscriptionsCount` => 5
 - Start another broker Broker3 (Now this channels will be again distributed among rest of brokers, So assuming Broker2 will get 3 channels and  Broker3 will get 2 channels ).
 - Again check `this.agServer.clients['clientId'].channelSubscriptionsCount` on both channels output will be like.
  
 Actual: 
 Broker2 => 5
 Broker3 => 2
   
 Expected: 
 Broker2 => 3
 Broker3 => 2
 
 Cause of this issue: 
 https://github.com/SocketCluster/scc-broker-client/blob/51054380aaf47a034cc3bc39bed5a8eafbb22821/cluster-broker-client.js#L129
 Here you can see we are gracefully closing the channel. But this doesn't send any message to server like unsubscribe does.
 So Broker channelSubscriptionsCount doesn't gets updated.

**Comment by Shankar-khati** [comment]
hey @jondubois can you please look into this issue?? I just want to get count for the channel subscribed by a broker.

**Comment by jondubois** [comment]
@Shankar-khati Thanks for this detailed bug report. It was missing an `unsubscribe` call. I've fixed this and integration tests are still passing.

I didn't yet get the time to check if it solves your issue specifically so please let me know (and close this issue) if it did.

The fix was implemented in:

- scc-broker-client@8.1.0
- socketcluster@16.0.3

The latest socketcluster/socketcluster:v16.0.3 container image was pushed to DockerHub.

**Comment by jondubois** [comment]
Closed by accident. Please close this issue if it has been fixed.

**Comment by Shankar-khati** [comment]
Thanks @jondubois, I really appreciate it.

**Comment by Shankar-khati** [comment]
@jondubois I just tested with `scc-broker-client@8.1.0` working amazing!!!
