### ISSUE TITLE
`socketcluster create` screws up app name

### ISSUE THREAD

**Issue by MegaGM** [SocketCluster/socketcluster#572]
Today I've created an app and got something unexpected as a directory name

```sh
npm i -g socketcluster@17.2.0
socketcluster create Pyaterochka-013152-SKU-auditor
```

Expected result
```sh
Pyaterochka-013152-SKU-auditor/
```

Actual result
```sh
-pyaterochka013152-s-k-u-auditor/
```

I've tried something like `git bisect` but, instead of commits, with `socketcluster` npm versions.
And have found out that `v16.1.3` `socketcluster create` doesn't screw up app name, and all versions starting from `v16.2.0` do.

**Comment by MegaGM** [comment]
So far I've narrowed the possible culprits to  
`@maartennnn/cli-builder/src/index.js`
```js
camelCaseToKebab()
kebabCaseToCamel()
```

**Comment by jondubois** [comment]
Thanks for raising this issue @MegaGM. Nice to see you again.
