### ISSUE TITLE
socket.on is not a function

### ISSUE THREAD

**Issue by sahul360** [SocketCluster/socketcluster#588]
I am getting this error while I was doing the below steps in my reactJS application

  const socketClusterConfig = {
      port: 8000,
      hostname: 'localhost'
    };

    const socket = socketCluster.create(socketClusterConfig); 

    socket.on('connect', () => {
      console.log('Connected to SocketCluster server');
    });

**Comment by maarteNNNN** [comment]
What's your client version?

**Comment by sahul360** [comment]
> 

 "socketcluster-client": "^17.1.0"

**Comment by maarteNNNN** [comment]
You can track connection events on the client via:

```js
(async () => {
  for await (const event of socket.listener('connect')) {
    console.log('Connected to server', event);
  }
})();
```
