### ISSUE TITLE
Make SC work with passport authentication

### ISSUE THREAD

**Issue by jondubois** [SocketCluster/socketcluster#71]
See https://github.com/TopCloud/socketcluster/issues/53

**Comment by MegaGM** [comment]
Any news? ^_^

**Comment by vnistor** [comment]
Interested in this as well.

**Comment by jondubois** [comment]
It's next on my TODO list.

**Comment by jondubois** [comment]
I'm currently making some changes to authentication (making it localStorage-based instead of cookie-based, also it will be fully customizable on both the client and server) so I need to finish that before moving on to passport... Sometime this week hopefully :(

**Comment by rrNuvoPoint** [comment]
Look perhaps at https://github.com/sahat/satellizer and the nodeJS module. It works for me :+1:

**Comment by jondubois** [comment]
@vnistor thanks for pointing this out. By default, the token will be stored in sessionStorage (it will have session lifespan). If you want it to persist beyond a single session (localStorage), you will need to set the persistent option to true when calling setAuthToken(token, options) on the server. See http://socketcluster.io/#!/docs/api-scsocket-server

**Comment by jondubois** [comment]
@rrNuvoPoint Thanks for mentioning this!
Satellizer looks like a very good solution to this problem.

@MegaGM @vnistor 
Note that you can do Authentication either over HTTP or over WebSockets.

Assuming I understood satellizer correcrly, a typical HTTP auth flow could be:

1. Use satellizer to open a new Facebook OAuth window and let them sign in
2. Let satellizer send the resulting authorization code to the SC server at a specific URL (HTTP request)
3. The SC server can then check that auth code with Facebook
4. If the auth code is valid, then you can generate a new JWT auth token on the server and send it as a cookie to the client by setting the 'Set-Cookie' HTTP response header.
5. Do ```socketCluster.connect(...)```
6. After the socket connects, you will be able to access the JWT token from ```socket.request.headers.cookie``` (WebSockets)


A typical WebSocket flow could be:

1. Call ```socketCluster.connect(...)```
2. Use satellizer to open a new Facebook OAuth window and let them sign in
3. Get the auth code back directly on the client-side (don't send directly to server via HTTP)
4. You can then send the code to the server over WebSockets using something like ```socket.emit('auth', authCode)```
5. Then on the server you can do ```socket.on('auth', handlerFunction)```
6. Inside handlerFunction, you can check the auth code with Facebook and if it's valid, you can provide the client with a new JWT token - SC provides a method to make this easy (example) ```socket.setAuthToken({username: 'bob123'})``` 
7. Any time after this (usually inside middleware functions), you can check if the client has a token by calling socket.getAuthToken()

The second way (WebSocket based) is currently the easiest way to do OAuth since SC manages the JWT tokens for you. If you go with the HTTP approach, you have to generate/validate the JWT token yourself which is more work.
I will try to make it easier to generate the JWT token as part of the HTTP flow too.

Then once that's done I will think about how to integrate with PassportJS.

**Comment by jondubois** [comment]
Since SC v2.2.35, you can access the default AuthEngine, from ```worker.auth``` inside your workerController. This allows you to sign (create) tokens and also verify tokens provided by clients: https://github.com/SocketCluster/socketcluster/blob/master/lib/auth.js - This may be useful if you want to do custom authentication over HTTP but don't want to write your own token signing/verification engine.

**Comment by jondubois** [comment]
I think satellizer seems like the best solution since SC is designed to work with JWT tokens.
