### ISSUE TITLE
Writting to store and fetching information from them.

### ISSUE THREAD

**Issue by madwill** [SocketCluster/socketcluster#75]
Thanks so much for creating such a powerful server for sockets. 

Hope its ok to post this as a issue, i could not find a forum or irc channel. 
I could not find an explicit example on how to store information on the Stores. 

Like a user list of a chat logs. The kind of information a user would get initially when entering a room. 
Can be larger then stream message but only sent once. 

I usually do this through RPC. I was thinking this information should be on the stores since the worker should not share the state and would not know about each others. 

Do you have any example where you write and retrieve data from the stores ?

One solution i believe could work would be
- Have all user connect to a channel of their name concatenated with the room. 
- Send the worker connect event and new user which then send it to the store. 
- Store listen to event, add user to a map
- Send new user event to room's channel
- Send whole user list to user/room concatenated own channel. 

Is that retarded ? did i miss the API to do such a thing in a more streamlined way ?

i'm fairly new to sockets and node. But it looks like very exiting technology. 

Cordially 

William

**Comment by jondubois** [comment]
@madwill There are many ways to do this.
If you want users to listen to shared channels then you shouldn't have the username be part of the channel name.

For example, if you had a chat room about 'cats', then on the client side, you would have your users subscribe to the 'cats' channel using ```var catsChannel = socket.subscribe('cats')``` then you can watch from new messages using ```catsChannel.watch(listenerFunction)```.

If you want to keep track of logs, you should do it from the server side there are several ways to do this. Here is some server code to give you ideas (note that I haven't tested this code):

```js
// Server code

wsServer.on('connection', function (socket) {
  // ...
  socket.on('POST cats', function (message, res) {
    // Append the message to a rooms.cats array inside the store
    // The array will be created automatically if it doesn't already exist
    wsServer.global.add(['rooms', 'cats'], message, res);
    wsServer.global.publish('cats', message);
  });

  socket.on('GET cats', function (message, res) {
    wsServer.global.get(['rooms', 'cats'], res);
  });
  // ...
});
```

So then on the client side you can have:

```js
// Client code

var catsChannel = socket.subscribe('cats');
catsChannel.watch(function (message) {
  // Display the new message
});

// To send a new message to cats channel
socket.emit('POST cats', 'I like cats!', function(err) {
  if (err) {
    alert('Failed to post message about cats because of this error: ' + err);
  }
});

// The 'status' event gets triggered directly after the socket 
// connects (including reconnects due to failed connections)
// so it's a good place to request entire lists from scratch.
socket.on('status', function () {
  socket.emit('GET cats', function (err, messageList) {
    // ... render the list of all messages
  });
});
```

Also, you will probably need a way to clean-up the casts list in the store so that it doesn't get too long.

**Comment by madwill** [comment]
It does illustrate the point!

Thank you. 

What i was looking for was:

wsServer.global.add(['rooms', 'cats'], message, res);
wsServer.global.get(['rooms', 'cats'], res);

So i can share information between workers. The rest should be easy. The "username channel" was only to be able to find the way back to the initial connecting user. But its absolutely non necessary if i can access the store _synchronously_ with globals.

Any draw back to this ? Does it slow down requests and potential overall performances ?

Perhaps this works like cluster hub ? https://github.com/fent/clusterhub ? With in memory key/value pairs synced through the all workers ? So under the hood it its non blocking. 

Thanks again!

Ps: It would be nice to add a _get_ and _set_ in the socketCluster example app that comes with creating a new app for newcomers in this technology. 

Since your service appeal to the "user friendly" crowd.

**Comment by madwill** [comment]
I guess it could possibly work with https://github.com/jondubois/socket.io-ndata now that i look at your profile :)

**Comment by jondubois** [comment]
@madwill socket.io-ndata is an old project. fent/clusterhub is also kind of old - Both of these are meant to work with the old version of Socket.io and none of them are scalable.

**Comment by madwill** [comment]
Ok. 

My previous experience is with Java, which if we were to put a synchronized data storage in threads you would defeat the thread purpose. 

I'll have a look at how global object works. Try and understand how data in globals can be shared between multiple workers.

Merci pour tous.
