### ISSUE TITLE
In SC2 is possible access client cookies?

### ISSUE THREAD

**Issue by gabrielbiga** [SocketCluster/socketcluster#79]
In SC1 I can use the .cookie object...
```
socket.cookie.myCookie
```

But I can't access in SC2 using:
```
socket.request.headers.cookie
```

The cookie object is not present.
I have not found in the documentation or the Internet.
How I can do that?

**Comment by MegaGM** [comment]
I thought in SC2 it also should be the ` socket.cookie ` as [it was in SC1](https://github.com/SocketCluster/socketcluster/blob/sc1/lib/server/scserver.js#L346)

However, if you're trying to access the ` socket ` object inside ` MIDDLEWARE_HANDSHAKE `, there is no ` socket ` object yet. So it may contains in ` req ` as described here [at the section Handshake](http://socketcluster.io/#!/docs/middleware-and-authorization)  ( @jondubois, why wouldn't you make those sections' headers as clickable links? It's small but sometimes really useful feature )
Though, I'm not sure about where exactly they are ` req.requrest.headers.cookie ` or ` req.cookie `

**Comment by jondubois** [comment]
@gabrielbiga ```socket.request.headers.cookie``` works for me.
You need to make sure that the cookie is set before the client socket starts connecting. In SC2, there is just one HTTP request at the start so you need to make all your cookies are set on the client by the time that request is made. Note that cookies are no longer used as part of authentication so it wouldn't show up there. Let me know if you find a solution or a way to reproduce.

@MegaGM The socket.cookie shortcut was removed in SC2 - I think it's better if the user gets it from the socket.request.headers.cookie and does their own parsing if they need to - This keeps SC lightweight.
