### ISSUE TITLE
User to user communication example

### ISSUE THREAD

**Issue by bguiz** [SocketCluster/socketcluster#80]
- Say I have user A, connected to a server, and he emits an event with a payload.
- This payload is transformed on the server, and then 
- The payload is pushed to users B and C, who are both also connected to this server.

From [this guide](http://socketcluster.io/#!/docs/full-stack), it looks like this can be accomplished by having every user subscribing to a channel whose name is derived from their user name (or some other unique ID), and simply publishing/ emitting the payload to them. Is this the correct/ recommended approach to implement the above sceanrio?

Also, the docs seem to indicate that this is the case for "New API as of SocketCluster v1.0.0." - so I am wary that much of it is outdated as this project is currently in major version number 2. Shall I assume that the current docs are valid forv1 or for v2?

**Comment by jondubois** [comment]
The docs are valid for both v1 and v2 - The general pattern hasn't changed. I should probably update that page to make it sound more current.

You can setup a channel for each user and also have group channels shared between multiple users. So you could have a channel called 'web_developers' and all users who are web developers could subscribe to it. You can have more than one channel per client, in fact SC lets you have up to 1000 per client by default (you can configure this to be even higher if you need).

SC is efficient about how messages are delivered so you don't have to worry about subscribing to lots of channels per client.

**Comment by bguiz** [comment]
Thanks for the super quick answer!

W: http://bguiz.com
