### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by IngwiePhoenix** [SocketCluster/socketcluster#83]
I'd like to use a logo of sorts when crediting SocketCluster in my [BIRD3](https://github.com/DragonsInn/BIRD3) project. Can you provide one?

**Comment by jondubois** [comment]
There is a small one with text from the website: http://socketcluster.io/assets/img/logo.png
Or you can get the logo on its own:
https://camo.githubusercontent.com/1e6a52dbf401b60f5979aec6416967a42aab8e53/68747470733a2f2f7261772e6769746875622e636f6d2f536f636b6574436c75737465722f736f636b6574636c75737465722f6d61737465722f6173736574732f6c6f676f2e706e67

**Comment by IngwiePhoenix** [comment]
Ahh great, the second one will do! :) Thanks.

I'll make sure to list my software in the "using socketcluster" repo once its running at least in Beta.
