### ISSUE TITLE
Secretly changing the `http.globalAgent` properties

### ISSUE THREAD

**Issue by mscdex** [SocketCluster/socketcluster#84]
Modifying `http.globalAgent` properties in a module like [this](https://github.com/SocketCluster/socketcluster/blob/43db7a892fed95441079bcd09f0fbc989cd4f1f7/lib/scworker.js#L65) should be avoided. IMHO it's akin to a module modifying prototypes of built-in JS objects.

I couldn't even find where http client requests are performed in the code base that would need that kind of behavior.

**Comment by jondubois** [comment]
@mscdex Yes, that's actually completely useless. Thanks for spotting this. Fixed.
