### ISSUE TITLE
Horizontal scaling. Losing connection when server is closed?

### ISSUE THREAD

**Issue by Llorx** [SocketCluster/socketcluster#85]
I have a question. Looking everywhere for it and don't really find a solution.

Simply, I have a webpage that having almost 0 connections along the week, can raise thousands of connections in the weekend (live sports events broadcasting). The site is behind a CDN so I can handle all these connections without problems.

The problem is that I've created my own node.js chat. It works flawlessy but I'm aware that having only one server for this will be a bottleneck in the future, so I'm moving the chat to a cloud server where I can balance the load.

I know that I can do some things, but the main problem that I see is that, for example, if I use Amazon EC2 I'm only going to have 1 instance along the week (almost 0 users connected) but in the weeked Amazon will launch some instances when an event starts streaming and will route each connection to a different server. I know that this engine can "talk" with all the servers like being only one, and that's perfect for me. The problem that I see is, when an event ends and people starts quitting, the load balancer will start closing instances and people still connected to those instances will start losing connection to the chat. I know that I can overcome this simply by reconnecting the people but is possible that they lose some messages meanwhile they reconnect.

My question is, how this engine can overcome that problem? Thank you!

**Comment by jondubois** [comment]
@Llorx the general pattern which I follow with SC (when dealing with data instead of messages) is that immediately after connecting (or reconnecting), I request for a fresh snapshot of the data and then use pub/sub to subscribe to further changes afterwards - This works with data because I keep it stored in a database so getting that fresh copy of it is easy.

You could use the same approach by storing messages in an external database (even if only for a minute, or only for servers which are about to be shut down).

The other approach is to open a second socket (concurrently) from the client while the the first one is being shutdown but it seems like a bit of a hack.

**Comment by Llorx** [comment]
Just that is what I was thinking for. In this way: The chat server will have a backlog of 30 seconds with a timestamp for each chat message, and when a user reconnects, it will send the timestamp of the last message received, so the server will know what data has to send to have the user up to date. I don't think that a reconnect will last more than a few seconds in the worst scenario, that's why I only will have a backlog of 30 seconds. If someone lasts more than 30 seconds in reconnecting, then he will be treated like he has a connection problem and his chat client will show so. Fairly reasonable because a server having 1000 messages per second (that's a bunch of messages) and each message being a maximum of half a Kb, that only makes 15 Mb of data.

The second approach is not that bad. The server will send a message that is going to be closed in 30 seconds to the clients. The clients then will reconnect to another server and when they reconnect to a second server they will close the connection to the first server. The same as above, in the worst scenario, if an user lasts so many seconds in reconnecting to another server he will be treated like he has a connection problem, just what is actually happening.

I think that I'm going for the first one, but you gave me a great idea for the future in applications that manage great amounts of data where storing them for future fetch can eat big amounts of memory or where is a bit difficult to have timestamps and check them in each reconnect whitout eating too much CPU. Also the second approach is good for ultra realtime applications, because there will be all the time a writable and readable socket, so they don't have a small pause when one socket loses the connection and reconnects to another server.

Thank you for your reply.
