### ISSUE TITLE
Example of how to use SCChannel (server)

### ISSUE THREAD

**Issue by leedium** [SocketCluster/socketcluster#86]
Hey dudes, not sure how to implement this on the the server side.  

Any examples would be great.

Thanks!

**Comment by jondubois** [comment]
@leedium On the server side, you have to use the Global client ```scServer.global``` see http://socketcluster.io/#!/docs/api-global - It behaves similarily to the socket on the client side. You can just go ```var myChannel = scServer.global.subscribe('myChannelName');```

**Comment by leedium** [comment]
Wonderful!  Thanks mang!  Great Work by the way.  You've saved me NUFF time with what I'm trying to do.

Cheers!

**Comment by leedium** [comment]
OK so..... need some assistance here, am I missing something

```javascript
  scServer.addMiddleware(scServer.MIDDLEWARE_SUBSCRIBE, function (socket, channel, next) {

    if(!socket.isSubscribed(channel)){
      socket.global.unsubscribe();
      socket.global.subscribe(channel);
      next();
    }else{
      next('sorry you are already subscribed to this channel');
    }
   });
```
The failure condition never fires even though i'm unsubscribing on the client side.  It just keeps subscribing to new Channels which are pending.  If  I don't add the server subscribe it just keeps appending to the same channel, so when messages are sent I get multiple.  Do I need to subscribe through the server using the middleware as well?


Thoughts?

**Comment by jondubois** [comment]
@leedium The client will not try to subscribe to a channel which is it already subscribed to so it won't even hit the server in this case (so your if condition will always evaluate to true).

You shouldn't need to call ```socket.global.subscribe()``` or ```socket.global.unsubscribe()``` inside your middleware - SC already handles the subcribe/unsubscribe logic for you. Middleware is just there to allow you to accept/request particular events.

You shouldn't get duplicate messages though - I will check if this is an issue.

**Comment by jondubois** [comment]
@leedium I couldn't reproduce your issue. Maybe it's something somewhere else your code (maybe in your worker.js)?

Also, calling ```socket.global.unsubscribe()``` does nothing - The first channelName argument is required - Right now SC tries to unsubscribe from a channel with value: undefined. I should change this to throw an error instead.

There is no quick way to unsubscribe from all channels in SC - This feature was too dangerous. If you want to do this, you can get a list of channels and use a for loop to unsubscribe from each one.

**Comment by jondubois** [comment]
About your question regarding whether ```socket.global.subscribe()```, ```global.publish()```, etc... will pass through middleware - The answer is no - Any code which is running on the server has full access privileges so it shouldn't have to pass through middleware.

Middleware only sits between clients and the server.

Let me know if you managed to resolve this issue. Thanks for raising an issue :)

**Comment by leedium** [comment]
Hey Jon! Trust me, it's probably my code.
Thanks for the great response and explanations.  I will try your suggestions and let you know.
Lovin' SC!

D.

**Comment by seiyria** [comment]
Is this still a valid way to get a ref to a channel on the server side? The global api link above is broken.

**Comment by jondubois** [comment]
@seiyria The global API was renamed to Exchange. http://socketcluster.io/#!/docs/api-exchange

**Comment by seiyria** [comment]
Ah, of course, thank you.
