### ISSUE TITLE
Elastic Scaling Possible?

### ISSUE THREAD

**Issue by mastayoda** [SocketCluster/socketcluster#88]
Hello SocketCluster team,

I was wondering if elastic scaling is possible. Vertical elastic scaling will be a good feature, and horizontal will be more complicated but also possible, for example:

-Server with 4 workers.
-All workers reach maximum, load, spawn a 5th worker.

I think the only current way to do this is by setting a local redis sub/pub and spawn a new socket cluster that connects to that same redis backend.

**Comment by jondubois** [comment]
@mastayoda SC doesn't currently support vertical elastic scaling, but of course it does support elastic horizontal scaling. It should be fairly easy to implement elastic scaling for the number of workers, but it will be tricky to implement elastic scaling for store processes.

Each store process holds a somewhat equal portion of all channels used throughout SC, the Global server-side client (responsible for interacting with the cluster of stores) uses a hash function of the channel name to decide which specific store should handle what channel. If you change the number of stores at runtime (and they already hold some subscriptions internally) - Then the hash function will need to be updated and that will cause existing mappings to be wrong. We would have to come up with a strategy to either redistribute the channels according to the new mapping or do some kind of redirection (I think redirection is the approach Redis uses).

It would be nice to implement it at some point. That said, as far as I know, the number of CPU cores on an instance cannot change at runtime, so having a fixed number of processes shouldn't be too much of a problem.

**Comment by happilymarrieddad** [comment]
You can always run a redis server and just dynamically hook up instances as you scale up and down. I made a quick video that explains the connection if you are interested. Here is the link. 

Without a loadbalancer:
https://www.youtube.com/watch?v=swjwNsEGz9g&list=PLTxFJWe_410zNJJD0o8njNLv7HidG1CHq&index=18

With SC-Loadbalancer
https://www.youtube.com/watch?v=zmCdIg7NNUg&list=PLTxFJWe_410zNJJD0o8njNLv7HidG1CHq&index=19

**Comment by happilymarrieddad** [comment]
Another thing you can do is monitor the cpu usage of the instances using a channel to broadcast the cpu utilization with   require('os').cpus()  for each instance and then use something like hubot to spin up and spin down AWS servers based on load.. you'd have to find a good way to attach them to the load balancer but that shouldn't be too hard.

**Comment by jondubois** [comment]
We now have released Kubernetes config files so you can now run and scale SC horizontally on any Kubernetes infrastructure. See https://github.com/SocketCluster/socketcluster/tree/master/kubernetes

**Comment by poppahorse** [comment]
@jondubois was this ever documented? Looking at SCC for its scaling properties using K8s, but need to understand if scaling is something that needs to be handled manually.

**Comment by jondubois** [comment]
@poppahorse You can do it manually if you like; this is feasible if you have a small cluster consisting of only a few machines but it's generally much easier to deploy it to Kubernetes. You can scale using a few simple `kubectl` commands. This is documented here: https://github.com/SocketCluster/socketcluster/blob/master/scc-guide.md
