### ISSUE TITLE
Function expected error in (sc1) socketcluster.js 

### ISSUE THREAD

**Issue by investis-webcast** [SocketCluster/socketcluster#90]
Error stack in ie8:
Message: Function expected
Line: 545
Char: 1
Code: 0
URI: http://192.168.225.158/socketcluster.js

Message: 'socketCluster' is undefined
Line: 74
Char: 5
Code: 0
URI: http://192.168.225.158/

While loading sc1 myapp example in ie8. We want our application to support ie8 socket long polling functionality, however client library don't seem to work.

I have used npm -g install sc1
and sc1 create myApp commands to create sample app. And running python simple server at port inside public folder 80. Also running node server.js at app folder level.

**Comment by jondubois** [comment]
This is an issue with the client so I'm closing this issue in favor of this one: https://github.com/SocketCluster/socketcluster-client/issues/13
