### ISSUE TITLE
getStatus() of all workers

### ISSUE THREAD

**Issue by mlmarius** [SocketCluster/socketcluster#91]
Hi. the scWorker.getStatus() method seems to have what i want. Kind of because the information only refers to one worker. But how do i get a sum of all stats across all workers in order to show stats for the entire socketCluster ? Can I do this from a worker ? How can one worker speak to all other workers ? Thanks !

**Comment by jondubois** [comment]
@mlmarius I just made an update to SC v2.3.4 which makes communicating between workers and master much easier. See sendToMaster() method here: http://socketcluster.io/#!/docs/api-scworker

**Comment by jondubois** [comment]
Generally though, it's better if each worker sends stats individually to your New Relic (or to whatever other monitoring service you might be using).
