### ISSUE TITLE
How to run a worker is that physically separated?

### ISSUE THREAD

**Issue by batazor** [SocketCluster/socketcluster#94]
How to run a worker is that physically separated?

**Comment by jondubois** [comment]
@batazor What do yo mean by that?

**Comment by batazor** [comment]
I have a few workers https://gist.github.com/batazor/0bb20efe76f8ab858179
I get so many messages as I launched workers, I can get only one message at
a running vorkers?
Sorry for my English.

**Comment by jondubois** [comment]
Thebidea of workers is that they share the same code so if u only want one worker to do something, u should check worker.id

**Comment by batazor** [comment]
Thanks. This option is not very suitable. Probably you will need to use
something else.

2015-07-30 16:34 GMT+03:00 Jonathan Gros-Dubois <notifications@github.com>:

**Comment by batazor** [comment]
Sorry.
Thanks. This option is not very suitable. Probably you will need to use
something else. -> Maybe I need to use something else.

2015-07-30 16:49 GMT+03:00 Виктор Логин <batazor111@gmail.com>:

**Comment by slidenerd** [comment]
Interesting, if that is the case, what would be great is if you can add another article in addition to your "SocketCluster patterns for chat" that shows a setup involving workers that do different tasks and relay everything to the server which can forward it to all clients, would be a solid usecase
