### ISSUE TITLE
Add item to data in middleware

### ISSUE THREAD

**Issue by KCypher13** [SocketCluster/socketcluster#95]
Good Morning,

First, Thanks a lot for SocketCluster, it's an amazing solution :)

I use the middleware to add the published data in my database.
There is no problem about that, I add a middleware PUBLISH_IN, and I create entry in my database.
But I would like to add item in the data publish by SC(e.g. the id send by my database).
Something like that : 

>scServer.addMiddleware(scServer.MIDDLEWARE_PUBLISH_IN, function(socket, channel, data, next){
>&nbsp;&nbsp;item.create(data, function(err, item);
>&nbsp;&nbsp;&nbsp;&nbsp;data.id = item.id;
>&nbsp;&nbsp;&nbsp;&nbsp;next()
>&nbsp;&nbsp;});
>});

Is that possible ?

**Comment by jondubois** [comment]
@KCypher13 Thanks for the positive feedback :)
Yes, modifying published data inside your middleware function is supported - You should definitely be able to add an id like this. After the publish action is processed by the SC server, all subscribers should be able to see the id there.

**Comment by KCypher13** [comment]
Thanks for the quick answer.
Indeed it's work very well.
I've tried before, but it didn't work, that's why I've ask...
I don't know why it's working now...

Thanks again !
