### ISSUE TITLE
Cannot set property 'encryptedAuthToken' of null

### ISSUE THREAD

**Issue by vnistor** [SocketCluster/socketcluster#96]
This seems to have been introduced in 2.3.8
1438893804751 - Origin: Worker (PID 2951)
    [Error] TypeError: Cannot set property 'encryptedAuthToken' of null
    at /root/node_modules/sc/cleanup/node_modules/socketcluster/lib/server/scserver.js:193:30
    at /root/node_modules/sc/cleanup/node_modules/socketcluster/node_modules/jsonwebtoken/index.js:86:18
    at process._tickDomainCallback (node.js:381:11)
1438893804766 - Worker 0 exited - Exit code: 0

Seems to occur every time a client tries to connect and already has a token.

**Comment by jondubois** [comment]
@vnistor Whoops. Fixed in v2.3.9

**Comment by vnistor** [comment]
Seems to have fixed the issue. Much appreciated.
