### ISSUE TITLE
How to detect disconnected client IP address?

### ISSUE THREAD

**Issue by kaviproject** [SocketCluster/socketcluster#98]
I am working on implementation chat room application. I am not able find a way to detect disconnect user from chat room. I tried to use the socket.remoteAddress on server side but it did not work. I tried to use the Chrome debugger but it did not  hit the break point. 

Can you guys please help me with the issue?

```js

worker.js

   var self=this;
    socket.on('disconnect', function () {
      debugger;
      console.log(self.socket.remoteAddress);
      console.log('User disconnected');
    });
```

**Comment by jondubois** [comment]
@kaviproject This works fine for me. Maybe try ```console.log(socket.remoteAddress)``` instead of ```console.log(self.socket.remoteAddress)```?

**Comment by kaviproject** [comment]
Its working. Thank you for your time.

**Comment by kaviproject** [comment]
I have other question related to server side debugging. I am not able to hit debugging point on worker.js code.
I am running node-debug worker.js in one window and other window node server --debug-workers.

Please let me know how to debug worker.js on server side.
```javascript
  socket.on('disconnect', function () {
      debugger;
      console.log(socket.remoteAddress);
      console.log('User disconnected');
    });
```
Its printing user disconnected message on the server but its not hitting debugger statement.

**Comment by jondubois** [comment]
You should be running ```node-inspector``` in the other window instead of ```node-debug worker.js```.
When you run SC with ```node server --debug-workers``` - node-inspector will give you a URL which you can use to debug from Chrome.

See this guide: http://socketcluster.io/#!/docs/debugging

**Comment by kaviproject** [comment]
Thank you for the information.
