### ISSUE TITLE
How to  debug worker.js on server side in socketcluster API?

### ISSUE THREAD

**Issue by kaviproject** [SocketCluster/socketcluster#99]
In the chat application I am trying to debug worker.js on server side. I am not able to hit debugging point on worker.js code.
I am running #h1 node-debug worker.js # in one window and other window #h1node server --debug-workers#.

Please let me know how to debug worker.js on server side.
```javascript
  socket.on('disconnect', function () {
      debugger;
      console.log(socket.remoteAddress);
      console.log('User disconnected');
    });
```
Its printing user disconnected message on the server but its not hitting debugger statement.

**Comment by jondubois** [comment]
@kaviproject You should try to follow all the steps here exactly: http://socketcluster.io/#!/docs/debugging

You need to run the ```node-inspector``` command in a separate console window or in the background. It needs to stay running throughout the entire debugging session.

**Comment by jondubois** [comment]
Reopen if this is a legitimate issue (using node-inspector can be tricky).
